// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

/// Wire type `GameRule`.
pub const GameRule = struct {
    rule_name: []const u8,
    rule_can_be_modified: bool,
    rule_value: types.GameRuleRuleValue,

    pub fn decode(r: *Reader) DecodeError!GameRule {
        var value: GameRule = undefined;
        value.rule_name = try r.readString();
        value.rule_can_be_modified = try r.readBool();
        value.rule_value = try types.GameRuleRuleValue.decode(r);
        return value;
    }

    pub fn encode(self: GameRule, w: anytype) EncodeError!void {
        try w.writeString(self.rule_name);
        try w.writeBool(self.rule_can_be_modified);
        try self.rule_value.encode(w);
    }
};
