// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

/// Wire type `SerializedAbilitiesData`.
pub const AbilityData = struct {
    target_player_raw_id: i64,
    player_permissions: types.PlayerPermissionLevel,
    command_permissions: types.CommandPermissionLevel,
    layers: codec.List(SerializedAbilitiesDataSerializedLayer, SerializedAbilitiesDataSerializedLayer),

    pub const actor_refs = .{
        .target_player_raw_id = codec.ActorRef.unique,
    };

    pub fn decode(r: *Reader) DecodeError!AbilityData {
        var value: AbilityData = undefined;
        value.target_player_raw_id = try r.readI64();
        value.player_permissions = try types.PlayerPermissionLevel.decode(r);
        value.command_permissions = try types.CommandPermissionLevel.decode(r);
        value.layers = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(SerializedAbilitiesDataSerializedLayer, SerializedAbilitiesDataSerializedLayer).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: AbilityData, w: anytype) EncodeError!void {
        try w.writeI64(self.target_player_raw_id);
        try self.player_permissions.encode(w);
        try self.command_permissions.encode(w);
        try w.writeCount(.var_u32, self.layers.len);
        try self.layers.encode(w);
    }
};

/// Wire type `AnimatedImageData`.
pub const AnimatedImageData = struct {
    skin_image: types.SkinImage,
    animated_texture_type: PersonaAnimatedTextureType,
    frames: f32,
    animation_expression: PersonaAnimationExpression,

    pub fn decode(r: *Reader) DecodeError!AnimatedImageData {
        var value: AnimatedImageData = undefined;
        value.skin_image = try types.SkinImage.decode(r);
        value.animated_texture_type = try PersonaAnimatedTextureType.decode(r);
        value.frames = try r.readF32();
        value.animation_expression = try PersonaAnimationExpression.decode(r);
        return value;
    }

    pub fn encode(self: AnimatedImageData, w: anytype) EncodeError!void {
        try self.skin_image.encode(w);
        try self.animated_texture_type.encode(w);
        try w.writeF32(self.frames);
        try self.animation_expression.encode(w);
    }
};

/// Wire type `AnimationMode`.
pub const AnimationMode = enum(u8) {
    none = 0,
    layers = 1,
    blocks = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!AnimationMode {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: AnimationMode, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `BuildPlatform`.
pub const BuildPlatform = enum(i32) {
    unknown = -1,
    google = 1,
    ios = 2,
    osx = 3,
    amazon = 4,
    gearvr = 5,
    uwp = 7,
    win32 = 8,
    dedicated = 9,
    tvos = 10,
    sony = 11,
    nintendo = 12,
    xbox = 13,
    windowsphone = 14,
    linux = 15,
    _,

    pub fn decode(r: *Reader) DecodeError!BuildPlatform {
        return @fromBackingInt(@intCast(try r.readI32()));
    }

    pub fn encode(self: BuildPlatform, w: anytype) EncodeError!void {
        try w.writeI32(@backingInt(self));
    }
};

/// Wire type `ControlScheme::Scheme`.
pub const ControlSchemeScheme = enum(u8) {
    locked_player_relative_strafe = 0,
    camera_relative = 1,
    camera_relative_strafe = 2,
    player_relative = 3,
    player_relative_strafe = 4,
    _,

    pub fn decode(r: *Reader) DecodeError!ControlSchemeScheme {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: ControlSchemeScheme, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `ItemStackRequestCereal::CraftLoomActionData`.
pub const CraftLoomStackRequestAction = struct {
    action_type: types.ItemStackRequestActionType,
    pattern_name_id: []const u8,
    num_crafts: u8,

    pub fn decode(r: *Reader) DecodeError!CraftLoomStackRequestAction {
        var value: CraftLoomStackRequestAction = undefined;
        value.action_type = try types.ItemStackRequestActionType.decode(r);
        switch (value.action_type) {
            .craftloom => {},
            else => return error.InvalidValue,
        }
        value.pattern_name_id = try r.readString();
        value.num_crafts = try r.readU8();
        if (value.num_crafts < 1) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: CraftLoomStackRequestAction, w: anytype) EncodeError!void {
        switch (self.action_type) {
            .craftloom => {},
            else => return error.InvalidValue,
        }
        try self.action_type.encode(w);
        try w.writeString(self.pattern_name_id);
        if (self.num_crafts < 1) return error.InvalidValue;
        try w.writeU8(self.num_crafts);
    }
};

/// Wire type `ItemStackRequestCereal::CraftRepairAndDisenchantActionData`.
pub const CraftRepairAndDisenchantStackRequestAction = struct {
    action_type: types.ItemStackRequestActionType,
    recipe_net_id: i32,
    number_of_requested_crafts: u8,
    repair_cost: i32,

    pub fn decode(r: *Reader) DecodeError!CraftRepairAndDisenchantStackRequestAction {
        var value: CraftRepairAndDisenchantStackRequestAction = undefined;
        value.action_type = try types.ItemStackRequestActionType.decode(r);
        switch (value.action_type) {
            .craftrepairanddisenchant => {},
            else => return error.InvalidValue,
        }
        value.recipe_net_id = try r.readI32();
        value.number_of_requested_crafts = try r.readU8();
        if (value.number_of_requested_crafts < 1) return error.InvalidValue;
        value.repair_cost = try r.readVarI32();
        if (value.repair_cost < 0) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: CraftRepairAndDisenchantStackRequestAction, w: anytype) EncodeError!void {
        switch (self.action_type) {
            .craftrepairanddisenchant => {},
            else => return error.InvalidValue,
        }
        try self.action_type.encode(w);
        try w.writeI32(self.recipe_net_id);
        if (self.number_of_requested_crafts < 1) return error.InvalidValue;
        try w.writeU8(self.number_of_requested_crafts);
        if (self.repair_cost < 0) return error.InvalidValue;
        try w.writeVarI32(self.repair_cost);
    }
};

/// Wire type `DataItemBytePayload`.
pub const DataItemBytePayload = struct {
    type: DataItemType,
    value: i8,

    pub fn decode(r: *Reader) DecodeError!DataItemBytePayload {
        var value: DataItemBytePayload = undefined;
        value.type = try DataItemType.decode(r);
        switch (value.type) {
            .byte => {},
            else => return error.InvalidValue,
        }
        value.value = try r.readI8();
        return value;
    }

    pub fn encode(self: DataItemBytePayload, w: anytype) EncodeError!void {
        switch (self.type) {
            .byte => {},
            else => return error.InvalidValue,
        }
        try self.type.encode(w);
        try w.writeI8(self.value);
    }
};

/// Wire type `DataItemCompoundTagPayload`.
pub const DataItemCompoundTagPayload = struct {
    type: DataItemType,
    value: []const u8,

    pub fn decode(r: *Reader) DecodeError!DataItemCompoundTagPayload {
        var value: DataItemCompoundTagPayload = undefined;
        value.type = try DataItemType.decode(r);
        switch (value.type) {
            .compoundtag => {},
            else => return error.InvalidValue,
        }
        value.value = try r.readNbt();
        return value;
    }

    pub fn encode(self: DataItemCompoundTagPayload, w: anytype) EncodeError!void {
        switch (self.type) {
            .compoundtag => {},
            else => return error.InvalidValue,
        }
        try self.type.encode(w);
        try w.writeNbt(self.value);
    }
};

/// Wire type `DataItemEntry`.
pub const DataItemEntry = struct {
    id: u32,
    payload: DataItemEntryPayload,

    pub fn decode(r: *Reader) DecodeError!DataItemEntry {
        var value: DataItemEntry = undefined;
        value.id = try r.readVarU32();
        value.payload = try DataItemEntryPayload.decode(r);
        return value;
    }

    pub fn encode(self: DataItemEntry, w: anytype) EncodeError!void {
        try w.writeVarU32(self.id);
        try self.payload.encode(w);
    }
};

pub const DataItemEntryPayload = union(enum(u32)) {
    byte: DataItemBytePayload,
    short: DataItemShortPayload,
    int: DataItemIntPayload,
    float: DataItemFloatPayload,
    string: DataItemStringPayload,
    compound_tag: DataItemCompoundTagPayload,
    pos: DataItemPosPayload,
    int64: DataItemInt64Payload,
    vec3: DataItemVec3Payload,

    pub fn decode(r: *Reader) DecodeError!DataItemEntryPayload {
        switch (try r.readVarU32()) {
            0 => return .{ .byte = try DataItemBytePayload.decode(r) },
            1 => return .{ .short = try DataItemShortPayload.decode(r) },
            2 => return .{ .int = try DataItemIntPayload.decode(r) },
            3 => return .{ .float = try DataItemFloatPayload.decode(r) },
            4 => return .{ .string = try DataItemStringPayload.decode(r) },
            5 => return .{ .compound_tag = try DataItemCompoundTagPayload.decode(r) },
            6 => return .{ .pos = try DataItemPosPayload.decode(r) },
            7 => return .{ .int64 = try DataItemInt64Payload.decode(r) },
            8 => return .{ .vec3 = try DataItemVec3Payload.decode(r) },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: DataItemEntryPayload, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .byte => |value| {
                try value.encode(w);
            },
            .short => |value| {
                try value.encode(w);
            },
            .int => |value| {
                try value.encode(w);
            },
            .float => |value| {
                try value.encode(w);
            },
            .string => |value| {
                try value.encode(w);
            },
            .compound_tag => |value| {
                try value.encode(w);
            },
            .pos => |value| {
                try value.encode(w);
            },
            .int64 => |value| {
                try value.encode(w);
            },
            .vec3 => |value| {
                try value.encode(w);
            },
        }
    }
};

/// Wire type `DataItemFloatPayload`.
pub const DataItemFloatPayload = struct {
    type: DataItemType,
    value: f32,

    pub fn decode(r: *Reader) DecodeError!DataItemFloatPayload {
        var value: DataItemFloatPayload = undefined;
        value.type = try DataItemType.decode(r);
        switch (value.type) {
            .float => {},
            else => return error.InvalidValue,
        }
        value.value = try r.readF32();
        return value;
    }

    pub fn encode(self: DataItemFloatPayload, w: anytype) EncodeError!void {
        switch (self.type) {
            .float => {},
            else => return error.InvalidValue,
        }
        try self.type.encode(w);
        try w.writeF32(self.value);
    }
};

/// Wire type `DataItemInt64Payload`.
pub const DataItemInt64Payload = struct {
    type: DataItemType,
    value: i64,

    pub fn decode(r: *Reader) DecodeError!DataItemInt64Payload {
        var value: DataItemInt64Payload = undefined;
        value.type = try DataItemType.decode(r);
        switch (value.type) {
            .int64 => {},
            else => return error.InvalidValue,
        }
        value.value = try r.readVarI64();
        return value;
    }

    pub fn encode(self: DataItemInt64Payload, w: anytype) EncodeError!void {
        switch (self.type) {
            .int64 => {},
            else => return error.InvalidValue,
        }
        try self.type.encode(w);
        try w.writeVarI64(self.value);
    }
};

/// Wire type `DataItemIntPayload`.
pub const DataItemIntPayload = struct {
    type: DataItemType,
    value: i32,

    pub fn decode(r: *Reader) DecodeError!DataItemIntPayload {
        var value: DataItemIntPayload = undefined;
        value.type = try DataItemType.decode(r);
        switch (value.type) {
            .int => {},
            else => return error.InvalidValue,
        }
        value.value = try r.readVarI32();
        return value;
    }

    pub fn encode(self: DataItemIntPayload, w: anytype) EncodeError!void {
        switch (self.type) {
            .int => {},
            else => return error.InvalidValue,
        }
        try self.type.encode(w);
        try w.writeVarI32(self.value);
    }
};

/// Wire type `DataItemPosPayload`.
pub const DataItemPosPayload = struct {
    type: DataItemType,
    value: codec.BlockPosition,

    pub fn decode(r: *Reader) DecodeError!DataItemPosPayload {
        var value: DataItemPosPayload = undefined;
        value.type = try DataItemType.decode(r);
        switch (value.type) {
            .pos => {},
            else => return error.InvalidValue,
        }
        value.value = try r.readBlockPosition();
        return value;
    }

    pub fn encode(self: DataItemPosPayload, w: anytype) EncodeError!void {
        switch (self.type) {
            .pos => {},
            else => return error.InvalidValue,
        }
        try self.type.encode(w);
        try w.writeBlockPosition(self.value);
    }
};

/// Wire type `DataItemShortPayload`.
pub const DataItemShortPayload = struct {
    type: DataItemType,
    value: i16,

    pub fn decode(r: *Reader) DecodeError!DataItemShortPayload {
        var value: DataItemShortPayload = undefined;
        value.type = try DataItemType.decode(r);
        switch (value.type) {
            .short => {},
            else => return error.InvalidValue,
        }
        value.value = try r.readI16();
        return value;
    }

    pub fn encode(self: DataItemShortPayload, w: anytype) EncodeError!void {
        switch (self.type) {
            .short => {},
            else => return error.InvalidValue,
        }
        try self.type.encode(w);
        try w.writeI16(self.value);
    }
};

/// Wire type `DataItemStringPayload`.
pub const DataItemStringPayload = struct {
    type: DataItemType,
    value: []const u8,

    pub fn decode(r: *Reader) DecodeError!DataItemStringPayload {
        var value: DataItemStringPayload = undefined;
        value.type = try DataItemType.decode(r);
        switch (value.type) {
            .string => {},
            else => return error.InvalidValue,
        }
        value.value = try r.readString();
        return value;
    }

    pub fn encode(self: DataItemStringPayload, w: anytype) EncodeError!void {
        switch (self.type) {
            .string => {},
            else => return error.InvalidValue,
        }
        try self.type.encode(w);
        try w.writeString(self.value);
    }
};

/// Wire type `DataItemType`.
pub const DataItemType = enum(u8) {
    byte = 0,
    short = 1,
    int = 2,
    float = 3,
    string = 4,
    compoundtag = 5,
    pos = 6,
    int64 = 7,
    vec3 = 8,
    _,

    pub fn decode(r: *Reader) DecodeError!DataItemType {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: DataItemType, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `DataItemVec3Payload`.
pub const DataItemVec3Payload = struct {
    type: DataItemType,
    value: codec.Vec3f,

    pub fn decode(r: *Reader) DecodeError!DataItemVec3Payload {
        var value: DataItemVec3Payload = undefined;
        value.type = try DataItemType.decode(r);
        switch (value.type) {
            .vec3 => {},
            else => return error.InvalidValue,
        }
        value.value = try r.readVec3f();
        return value;
    }

    pub fn encode(self: DataItemVec3Payload, w: anytype) EncodeError!void {
        switch (self.type) {
            .vec3 => {},
            else => return error.InvalidValue,
        }
        try self.type.encode(w);
        try w.writeVec3f(self.value);
    }
};

/// Wire type `Bedrock::DDUI::DataStoreUpdate`.
pub const DduiDataStoreUpdate = struct {
    data_store_name: []const u8,
    property: []const u8,
    path: []const u8,
    data: DduiDataStoreUpdateData,
    property_update_count: u32,
    path_update_count: u32,

    pub fn decode(r: *Reader) DecodeError!DduiDataStoreUpdate {
        var value: DduiDataStoreUpdate = undefined;
        value.data_store_name = try r.readString();
        if (value.data_store_name.len < 1) return error.InvalidValue;
        if (value.data_store_name.len > 1000) return error.InvalidValue;
        value.property = try r.readString();
        if (value.property.len < 1) return error.InvalidValue;
        if (value.property.len > 1000) return error.InvalidValue;
        value.path = try r.readString();
        if (value.path.len > 1000) return error.InvalidValue;
        value.data = try DduiDataStoreUpdateData.decode(r);
        value.property_update_count = try r.readU32();
        if (value.property_update_count > 4294967294) return error.InvalidValue;
        value.path_update_count = try r.readU32();
        if (value.path_update_count > 4294967294) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: DduiDataStoreUpdate, w: anytype) EncodeError!void {
        if (self.data_store_name.len < 1) return error.InvalidValue;
        if (self.data_store_name.len > 1000) return error.InvalidValue;
        try w.writeString(self.data_store_name);
        if (self.property.len < 1) return error.InvalidValue;
        if (self.property.len > 1000) return error.InvalidValue;
        try w.writeString(self.property);
        if (self.path.len > 1000) return error.InvalidValue;
        try w.writeString(self.path);
        try self.data.encode(w);
        if (self.property_update_count > 4294967294) return error.InvalidValue;
        try w.writeU32(self.property_update_count);
        if (self.path_update_count > 4294967294) return error.InvalidValue;
        try w.writeU32(self.path_update_count);
    }
};

pub const DduiDataStoreUpdateData = union(enum(u32)) {
    double: f64,
    bool: bool,
    string: []const u8,

    pub fn decode(r: *Reader) DecodeError!DduiDataStoreUpdateData {
        switch (try r.readVarU32()) {
            0 => return .{ .double = try r.readF64() },
            1 => return .{ .bool = try r.readBool() },
            2 => {
                var value: []const u8 = undefined;
                value = try r.readString();
                if (value.len > 5000) return error.InvalidValue;
                return .{ .string = value };
            },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: DduiDataStoreUpdateData, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .double => |value| {
                try w.writeF64(value);
            },
            .bool => |value| {
                try w.writeBool(value);
            },
            .string => |value| {
                if (value.len > 5000) return error.InvalidValue;
                try w.writeString(value);
            },
        }
    }
};

/// Wire type `EduSharedUriResource`.
pub const EducationSharedResourceURI = struct {
    button_name: []const u8,
    link_uri: []const u8,

    pub fn decode(r: *Reader) DecodeError!EducationSharedResourceURI {
        var value: EducationSharedResourceURI = undefined;
        value.button_name = try r.readString();
        value.link_uri = try r.readString();
        return value;
    }

    pub fn encode(self: EducationSharedResourceURI, w: anytype) EncodeError!void {
        try w.writeString(self.button_name);
        try w.writeString(self.link_uri);
    }
};

/// Wire type `Experiments`.
pub const Experiments = struct {
    toggles: codec.List(types.ExperimentData, types.ExperimentData),
    experiments_ever_toggled: bool,

    pub fn decode(r: *Reader) DecodeError!Experiments {
        var value: Experiments = undefined;
        value.toggles = blk: {
            const count = try r.readCount(.u32le);
            break :blk try codec.List(types.ExperimentData, types.ExperimentData).decode(r, count);
        };
        value.experiments_ever_toggled = try r.readBool();
        return value;
    }

    pub fn encode(self: Experiments, w: anytype) EncodeError!void {
        try w.writeCount(.u32le, self.toggles.len);
        try self.toggles.encode(w);
        try w.writeBool(self.experiments_ever_toggled);
    }
};

pub const GameRuleRuleValue = union(enum(u32)) {
    empty,
    bool: bool,
    int32: i32,
    float: f32,

    pub fn decode(r: *Reader) DecodeError!GameRuleRuleValue {
        switch (try r.readVarU32()) {
            0 => return .empty,
            1 => return .{ .bool = try r.readBool() },
            2 => return .{ .int32 = try r.readI32() },
            3 => return .{ .float = try r.readF32() },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: GameRuleRuleValue, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .empty => {},
            .bool => |value| {
                try w.writeBool(value);
            },
            .int32 => |value| {
                try w.writeI32(value);
            },
            .float => |value| {
                try w.writeF32(value);
            },
        }
    }
};

/// Wire type `GameType`.
pub const GameType = enum(i32) {
    undefined = -1,
    survival = 0,
    creative = 1,
    adventure = 2,
    default = 5,
    spectator = 6,
    _,

    pub fn decode(r: *Reader) DecodeError!GameType {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: GameType, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

/// Wire type `ServerConfiguration::GatheringsConfigurationJoinInfo`.
pub const GatheringJoinInfo = struct {
    experience_id: [16]u8,
    experience_name: []const u8,
    world_id: ?[16]u8,
    world_name: ?[]const u8,
    creator_id: []const u8,
    target_id: ?[16]u8,
    scenario_id: ?[]const u8,
    server_id: ?[]const u8,

    pub fn decode(r: *Reader) DecodeError!GatheringJoinInfo {
        var value: GatheringJoinInfo = undefined;
        value.experience_id = try r.readUuid();
        value.experience_name = try r.readString();
        if (value.experience_name.len < 1) return error.InvalidValue;
        if (value.experience_name.len > 29) return error.InvalidValue;
        value.world_id = if (try r.readBool()) try r.readUuid() else null;
        value.world_name = null;
        if (try r.readBool()) {
            var present: []const u8 = undefined;
            present = try r.readString();
            if (present.len < 1) return error.InvalidValue;
            if (present.len > 29) return error.InvalidValue;
            value.world_name = present;
        }
        value.creator_id = try r.readString();
        if (value.creator_id.len < 1) return error.InvalidValue;
        if (value.creator_id.len > 60) return error.InvalidValue;
        value.target_id = if (try r.readBool()) try r.readUuid() else null;
        value.scenario_id = null;
        if (try r.readBool()) {
            var present: []const u8 = undefined;
            present = try r.readString();
            if (present.len < 1) return error.InvalidValue;
            if (present.len > 100) return error.InvalidValue;
            value.scenario_id = present;
        }
        value.server_id = null;
        if (try r.readBool()) {
            var present: []const u8 = undefined;
            present = try r.readString();
            if (present.len < 1) return error.InvalidValue;
            if (present.len > 100) return error.InvalidValue;
            value.server_id = present;
        }
        return value;
    }

    pub fn encode(self: GatheringJoinInfo, w: anytype) EncodeError!void {
        try w.writeUuid(self.experience_id);
        if (self.experience_name.len < 1) return error.InvalidValue;
        if (self.experience_name.len > 29) return error.InvalidValue;
        try w.writeString(self.experience_name);
        try w.writeBool(self.world_id != null);
        if (self.world_id) |present| {
            try w.writeUuid(present);
        }
        try w.writeBool(self.world_name != null);
        if (self.world_name) |present| {
            if (present.len < 1) return error.InvalidValue;
            if (present.len > 29) return error.InvalidValue;
            try w.writeString(present);
        }
        if (self.creator_id.len < 1) return error.InvalidValue;
        if (self.creator_id.len > 60) return error.InvalidValue;
        try w.writeString(self.creator_id);
        try w.writeBool(self.target_id != null);
        if (self.target_id) |present| {
            try w.writeUuid(present);
        }
        try w.writeBool(self.scenario_id != null);
        if (self.scenario_id) |present| {
            if (present.len < 1) return error.InvalidValue;
            if (present.len > 100) return error.InvalidValue;
            try w.writeString(present);
        }
        try w.writeBool(self.server_id != null);
        if (self.server_id) |present| {
            if (present.len < 1) return error.InvalidValue;
            if (present.len > 100) return error.InvalidValue;
            try w.writeString(present);
        }
    }
};

/// Wire type `GeneratorType`.
pub const GeneratorType = enum(i32) {
    legacy = 0,
    overworld = 1,
    flat = 2,
    nether = 3,
    theend = 4,
    void = 5,
    undefined = 6,
    _,

    pub fn decode(r: *Reader) DecodeError!GeneratorType {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: GeneratorType, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

pub const ItemDescriptor = union(enum(u32)) {
    empty_item: types.ItemDescriptorType,
    item_name: types.DefaultItemDescriptor,
    molang_item: types.MoLangItemDescriptor,
    item_tag: types.ItemTagItemDescriptor,

    pub fn decode(r: *Reader) DecodeError!ItemDescriptor {
        switch (try r.readVarU32()) {
            0 => {
                var value: types.ItemDescriptorType = undefined;
                value = try types.ItemDescriptorType.decode(r);
                switch (value) {
                    .empty => {},
                    else => return error.InvalidValue,
                }
                return .{ .empty_item = value };
            },
            1 => return .{ .item_name = try types.DefaultItemDescriptor.decode(r) },
            2 => return .{ .molang_item = try types.MoLangItemDescriptor.decode(r) },
            3 => return .{ .item_tag = try types.ItemTagItemDescriptor.decode(r) },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: ItemDescriptor, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .empty_item => |value| {
                switch (value) {
                    .empty => {},
                    else => return error.InvalidValue,
                }
                try value.encode(w);
            },
            .item_name => |value| {
                try value.encode(w);
            },
            .molang_item => |value| {
                try value.encode(w);
            },
            .item_tag => |value| {
                try value.encode(w);
            },
        }
    }
};

/// Wire type `LegacySetSlot`.
pub const LegacySetSlot = struct {
    container_enum: types.ContainerEnumName,
    slots: []const u8,

    pub fn decode(r: *Reader) DecodeError!LegacySetSlot {
        var value: LegacySetSlot = undefined;
        value.container_enum = try types.ContainerEnumName.decode(r);
        value.slots = try r.readByteArray();
        return value;
    }

    pub fn encode(self: LegacySetSlot, w: anytype) EncodeError!void {
        try self.container_enum.encode(w);
        try w.writeByteArray(self.slots);
    }
};

/// Wire type `Mirror`.
pub const Mirror = enum(u8) {
    none = 0,
    x = 1,
    z = 2,
    xz = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!Mirror {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: Mirror, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `MolangVersion`.
pub const MolangVersion = enum(i16) {
    invalid = -1,
    beforeversioning = 0,
    initial = 1,
    fixeditemremainingusedurationquery = 2,
    expressionerrormessages = 3,
    unexpectedoperatorerrors = 4,
    conditionaloperatorassociativity = 5,
    comparisonandlogicaloperatorprecedence = 6,
    dividebynegativevalue = 7,
    fixedcapeflapamountquery = 8,
    queryblockpropertyrenamedtostate = 9,
    deprecateoldblockquerynames = 10,
    deprecatedsnifferandcamelqueries = 11,
    leafsupportinginfirstsolidblockbelow = 12,
    latest = 13,
    numvalidversions = 14,
    _,

    pub fn decode(r: *Reader) DecodeError!MolangVersion {
        return @fromBackingInt(@intCast(try r.readI16()));
    }

    pub fn encode(self: MolangVersion, w: anytype) EncodeError!void {
        try w.writeI16(@backingInt(self));
    }
};

/// Wire type `cerealizer<NetworkItemInstanceDescriptor>::SerializedData`.
pub const NetworkItemInstanceDescriptor = struct {
    id: i32,
    stack_size: u16,
    aux_value: u32,
    block_runtime_id: i32,
    user_data_buffer: []const u8,

    pub fn decode(r: *Reader) DecodeError!NetworkItemInstanceDescriptor {
        var value: NetworkItemInstanceDescriptor = undefined;
        value.id = try r.readVarI32();
        if (value.id < -32768) return error.InvalidValue;
        if (value.id > 32767) return error.InvalidValue;
        value.stack_size = try r.readU16();
        value.aux_value = try r.readVarU32();
        if (value.aux_value > 32767) return error.InvalidValue;
        value.block_runtime_id = try r.readVarI32();
        value.user_data_buffer = try r.readByteArray();
        return value;
    }

    pub fn encode(self: NetworkItemInstanceDescriptor, w: anytype) EncodeError!void {
        if (self.id < -32768) return error.InvalidValue;
        if (self.id > 32767) return error.InvalidValue;
        try w.writeVarI32(self.id);
        try w.writeU16(self.stack_size);
        if (self.aux_value > 32767) return error.InvalidValue;
        try w.writeVarU32(self.aux_value);
        try w.writeVarI32(self.block_runtime_id);
        try w.writeByteArray(self.user_data_buffer);
    }
};

/// Wire type `cerealizer<NetworkItemStackDescriptor>::SerializedData`.
pub const NetworkItemStackDescriptor = struct {
    id: i16,
    stack_size: u16,
    aux_value: u32,
    net_id_variant: ?i32,
    block_runtime_id: u32,
    user_data_buffer: []const u8,

    pub fn decode(r: *Reader) DecodeError!NetworkItemStackDescriptor {
        var value: NetworkItemStackDescriptor = undefined;
        value.id = try r.readI16();
        value.stack_size = try r.readU16();
        value.aux_value = try r.readVarU32();
        if (value.aux_value > 32767) return error.InvalidValue;
        value.net_id_variant = if (try r.readBool()) try r.readVarI32() else null;
        value.block_runtime_id = try r.readVarU32();
        value.user_data_buffer = try r.readByteArray();
        return value;
    }

    pub fn encode(self: NetworkItemStackDescriptor, w: anytype) EncodeError!void {
        try w.writeI16(self.id);
        try w.writeU16(self.stack_size);
        if (self.aux_value > 32767) return error.InvalidValue;
        try w.writeVarU32(self.aux_value);
        try w.writeBool(self.net_id_variant != null);
        if (self.net_id_variant) |present| {
            try w.writeVarI32(present);
        }
        try w.writeVarU32(self.block_runtime_id);
        try w.writeByteArray(self.user_data_buffer);
    }
};

/// Wire type `persona::AnimatedTextureType`.
pub const PersonaAnimatedTextureType = enum(u32) {
    none = 0,
    face = 1,
    body32x32 = 2,
    body128x128 = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!PersonaAnimatedTextureType {
        return @fromBackingInt(@intCast(try r.readVarU32()));
    }

    pub fn encode(self: PersonaAnimatedTextureType, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
    }
};

/// Wire type `persona::AnimationExpression`.
pub const PersonaAnimationExpression = enum(u32) {
    linear = 0,
    blinking = 1,
    _,

    pub fn decode(r: *Reader) DecodeError!PersonaAnimationExpression {
        return @fromBackingInt(@intCast(try r.readVarU32()));
    }

    pub fn encode(self: PersonaAnimationExpression, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
    }
};

/// Wire type `SharedTypes::persona::ArmSizeType`.
pub const PersonaArmSizeType = enum(u8) {
    slim = 0,
    wide = 1,
    _,

    pub fn decode(r: *Reader) DecodeError!PersonaArmSizeType {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: PersonaArmSizeType, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `SerializedPersonaPieceHandle`.
pub const PersonaPiece = struct {
    piece_id: []const u8,
    piece_type: types.PersonaPieceType,
    pack_id: [16]u8,
    is_default_piece: bool,
    product_id: []const u8,

    pub fn decode(r: *Reader) DecodeError!PersonaPiece {
        var value: PersonaPiece = undefined;
        value.piece_id = try r.readString();
        value.piece_type = try types.PersonaPieceType.decode(r);
        value.pack_id = try r.readUuid();
        value.is_default_piece = try r.readBool();
        value.product_id = try r.readString();
        return value;
    }

    pub fn encode(self: PersonaPiece, w: anytype) EncodeError!void {
        try w.writeString(self.piece_id);
        try self.piece_type.encode(w);
        try w.writeUuid(self.pack_id);
        try w.writeBool(self.is_default_piece);
        try w.writeString(self.product_id);
    }
};

/// Wire type `PropertySyncData`.
pub const PropertySyncData = struct {
    int_entries_list: codec.List(PropertySyncDataPropertySyncIntEntry, PropertySyncDataPropertySyncIntEntry),
    float_entries_list: codec.List(PropertySyncDataPropertySyncFloatEntry, PropertySyncDataPropertySyncFloatEntry),

    pub fn decode(r: *Reader) DecodeError!PropertySyncData {
        var value: PropertySyncData = undefined;
        value.int_entries_list = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(PropertySyncDataPropertySyncIntEntry, PropertySyncDataPropertySyncIntEntry).decode(r, count);
        };
        value.float_entries_list = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(PropertySyncDataPropertySyncFloatEntry, PropertySyncDataPropertySyncFloatEntry).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: PropertySyncData, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.int_entries_list.len);
        try self.int_entries_list.encode(w);
        try w.writeCount(.var_u32, self.float_entries_list.len);
        try self.float_entries_list.encode(w);
    }
};

/// Wire type `PropertySyncData::PropertySyncFloatEntry`.
pub const PropertySyncDataPropertySyncFloatEntry = struct {
    property_index: u32,
    data: f32,

    pub fn decode(r: *Reader) DecodeError!PropertySyncDataPropertySyncFloatEntry {
        var value: PropertySyncDataPropertySyncFloatEntry = undefined;
        value.property_index = try r.readVarU32();
        value.data = try r.readF32();
        return value;
    }

    pub fn encode(self: PropertySyncDataPropertySyncFloatEntry, w: anytype) EncodeError!void {
        try w.writeVarU32(self.property_index);
        try w.writeF32(self.data);
    }
};

/// Wire type `PropertySyncData::PropertySyncIntEntry`.
pub const PropertySyncDataPropertySyncIntEntry = struct {
    property_index: u32,
    data: i32,

    pub fn decode(r: *Reader) DecodeError!PropertySyncDataPropertySyncIntEntry {
        var value: PropertySyncDataPropertySyncIntEntry = undefined;
        value.property_index = try r.readVarU32();
        value.data = try r.readVarI32();
        return value;
    }

    pub fn encode(self: PropertySyncDataPropertySyncIntEntry, w: anytype) EncodeError!void {
        try w.writeVarU32(self.property_index);
        try w.writeVarI32(self.data);
    }
};

/// Wire type `Rotation`.
pub const Rotation = enum(u8) {
    none = 0,
    rotate90 = 1,
    rotate180 = 2,
    rotate270 = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!Rotation {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: Rotation, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `SerializedAbilitiesData::SerializedLayer`.
pub const SerializedAbilitiesDataSerializedLayer = struct {
    serialized_layer: u16,
    abilities_set: u32,
    ability_values: u32,
    fly_speed: f32,
    vertical_fly_speed: f32,
    walk_speed: f32,

    pub fn decode(r: *Reader) DecodeError!SerializedAbilitiesDataSerializedLayer {
        var value: SerializedAbilitiesDataSerializedLayer = undefined;
        value.serialized_layer = try r.readU16();
        value.abilities_set = try r.readU32();
        value.ability_values = try r.readU32();
        value.fly_speed = try r.readF32();
        value.vertical_fly_speed = try r.readF32();
        value.walk_speed = try r.readF32();
        return value;
    }

    pub fn encode(self: SerializedAbilitiesDataSerializedLayer, w: anytype) EncodeError!void {
        try w.writeU16(self.serialized_layer);
        try w.writeU32(self.abilities_set);
        try w.writeU32(self.ability_values);
        try w.writeF32(self.fly_speed);
        try w.writeF32(self.vertical_fly_speed);
        try w.writeF32(self.walk_speed);
    }
};

/// Wire type `SerializedSkinRef`.
pub const SerializedSkinRef = struct {
    id: []const u8,
    play_fab_id: []const u8,
    resource_patch: []const u8,
    image_data: types.SkinImage,
    animated_image_data: codec.List(AnimatedImageData, AnimatedImageData),
    cape_image_data: types.SkinImage,
    geometry_data: []const u8,
    geometry_data_min_engine_version: []const u8,
    animation_data: []const u8,
    cape_id: []const u8,
    full_id: []const u8,
    arm_size: PersonaArmSizeType,
    skin_color: i32,
    persona_pieces: codec.List(PersonaPiece, PersonaPiece),
    piece_tint_colors: codec.List(SerializedSkinRefPieceTintColorsEntry, SerializedSkinRefPieceTintColorsEntry),
    is_premium: bool,
    is_persona: bool,
    is_persona_cape_on_classic_skin: bool,
    is_primary_user: bool,
    overrides_player_appearance: bool,
    trusted_skin_flag: []const u8,
    profile_hash: []const u8,

    pub fn decode(r: *Reader) DecodeError!SerializedSkinRef {
        var value: SerializedSkinRef = undefined;
        value.id = try r.readString();
        value.play_fab_id = try r.readString();
        value.resource_patch = try r.readString();
        value.image_data = try types.SkinImage.decode(r);
        value.animated_image_data = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(AnimatedImageData, AnimatedImageData).decode(r, count);
        };
        value.cape_image_data = try types.SkinImage.decode(r);
        value.geometry_data = try r.readString();
        value.geometry_data_min_engine_version = try r.readString();
        value.animation_data = try r.readString();
        value.cape_id = try r.readString();
        value.full_id = try r.readString();
        value.arm_size = try PersonaArmSizeType.decode(r);
        value.skin_color = try r.readI32();
        value.persona_pieces = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(PersonaPiece, PersonaPiece).decode(r, count);
        };
        value.piece_tint_colors = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(SerializedSkinRefPieceTintColorsEntry, SerializedSkinRefPieceTintColorsEntry).decode(r, count);
        };
        value.is_premium = try r.readBool();
        value.is_persona = try r.readBool();
        value.is_persona_cape_on_classic_skin = try r.readBool();
        value.is_primary_user = try r.readBool();
        value.overrides_player_appearance = try r.readBool();
        value.trusted_skin_flag = try r.readString();
        value.profile_hash = try r.readString();
        return value;
    }

    pub fn encode(self: SerializedSkinRef, w: anytype) EncodeError!void {
        try w.writeString(self.id);
        try w.writeString(self.play_fab_id);
        try w.writeString(self.resource_patch);
        try self.image_data.encode(w);
        try w.writeCount(.var_u32, self.animated_image_data.len);
        try self.animated_image_data.encode(w);
        try self.cape_image_data.encode(w);
        try w.writeString(self.geometry_data);
        try w.writeString(self.geometry_data_min_engine_version);
        try w.writeString(self.animation_data);
        try w.writeString(self.cape_id);
        try w.writeString(self.full_id);
        try self.arm_size.encode(w);
        try w.writeI32(self.skin_color);
        try w.writeCount(.var_u32, self.persona_pieces.len);
        try self.persona_pieces.encode(w);
        try w.writeCount(.var_u32, self.piece_tint_colors.len);
        try self.piece_tint_colors.encode(w);
        try w.writeBool(self.is_premium);
        try w.writeBool(self.is_persona);
        try w.writeBool(self.is_persona_cape_on_classic_skin);
        try w.writeBool(self.is_primary_user);
        try w.writeBool(self.overrides_player_appearance);
        try w.writeString(self.trusted_skin_flag);
        try w.writeString(self.profile_hash);
    }
};

pub const StackRequestAction = union(enum(u32)) {
    take: types.TakeStackRequestAction,
    place: types.PlaceStackRequestAction,
    swap: types.SwapStackRequestAction,
    drop: types.DropStackRequestAction,
    destroy: types.DestroyStackRequestAction,
    consume: types.ConsumeStackRequestAction,
    create: types.CreateStackRequestAction,
    lab_table_combine: types.ItemStackRequestActionType,
    beacon_payment: types.BeaconPaymentStackRequestAction,
    mine_block: types.MineBlockStackRequestAction,
    craft_recipe: types.CraftRecipeStackRequestAction,
    craft_recipe_auto: types.AutoCraftRecipeStackRequestAction,
    craft_creative: types.CraftCreativeStackRequestAction,
    craft_recipe_optional: types.CraftRecipeOptionalStackRequestAction,
    craft_repair_and_disenchant: CraftRepairAndDisenchantStackRequestAction,
    craft_loom: CraftLoomStackRequestAction,
    craft_non_implemented: types.ItemStackRequestActionType,
    craft_results: types.CraftResultsDeprecatedStackRequestAction,

    pub fn decode(r: *Reader) DecodeError!StackRequestAction {
        switch (try r.readVarU32()) {
            0 => return .{ .take = try types.TakeStackRequestAction.decode(r) },
            1 => return .{ .place = try types.PlaceStackRequestAction.decode(r) },
            2 => return .{ .swap = try types.SwapStackRequestAction.decode(r) },
            3 => return .{ .drop = try types.DropStackRequestAction.decode(r) },
            4 => return .{ .destroy = try types.DestroyStackRequestAction.decode(r) },
            5 => return .{ .consume = try types.ConsumeStackRequestAction.decode(r) },
            6 => return .{ .create = try types.CreateStackRequestAction.decode(r) },
            7 => {
                var value: types.ItemStackRequestActionType = undefined;
                value = try types.ItemStackRequestActionType.decode(r);
                switch (value) {
                    .screenlabtablecombine => {},
                    else => return error.InvalidValue,
                }
                return .{ .lab_table_combine = value };
            },
            8 => return .{ .beacon_payment = try types.BeaconPaymentStackRequestAction.decode(r) },
            9 => return .{ .mine_block = try types.MineBlockStackRequestAction.decode(r) },
            10 => return .{ .craft_recipe = try types.CraftRecipeStackRequestAction.decode(r) },
            11 => return .{ .craft_recipe_auto = try types.AutoCraftRecipeStackRequestAction.decode(r) },
            12 => return .{ .craft_creative = try types.CraftCreativeStackRequestAction.decode(r) },
            13 => return .{ .craft_recipe_optional = try types.CraftRecipeOptionalStackRequestAction.decode(r) },
            14 => return .{ .craft_repair_and_disenchant = try CraftRepairAndDisenchantStackRequestAction.decode(r) },
            15 => return .{ .craft_loom = try CraftLoomStackRequestAction.decode(r) },
            16 => {
                var value: types.ItemStackRequestActionType = undefined;
                value = try types.ItemStackRequestActionType.decode(r);
                switch (value) {
                    .craftnonimplemented => {},
                    else => return error.InvalidValue,
                }
                return .{ .craft_non_implemented = value };
            },
            17 => return .{ .craft_results = try types.CraftResultsDeprecatedStackRequestAction.decode(r) },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: StackRequestAction, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .take => |value| {
                try value.encode(w);
            },
            .place => |value| {
                try value.encode(w);
            },
            .swap => |value| {
                try value.encode(w);
            },
            .drop => |value| {
                try value.encode(w);
            },
            .destroy => |value| {
                try value.encode(w);
            },
            .consume => |value| {
                try value.encode(w);
            },
            .create => |value| {
                try value.encode(w);
            },
            .lab_table_combine => |value| {
                switch (value) {
                    .screenlabtablecombine => {},
                    else => return error.InvalidValue,
                }
                try value.encode(w);
            },
            .beacon_payment => |value| {
                try value.encode(w);
            },
            .mine_block => |value| {
                try value.encode(w);
            },
            .craft_recipe => |value| {
                try value.encode(w);
            },
            .craft_recipe_auto => |value| {
                try value.encode(w);
            },
            .craft_creative => |value| {
                try value.encode(w);
            },
            .craft_recipe_optional => |value| {
                try value.encode(w);
            },
            .craft_repair_and_disenchant => |value| {
                try value.encode(w);
            },
            .craft_loom => |value| {
                try value.encode(w);
            },
            .craft_non_implemented => |value| {
                switch (value) {
                    .craftnonimplemented => {},
                    else => return error.InvalidValue,
                }
                try value.encode(w);
            },
            .craft_results => |value| {
                try value.encode(w);
            },
        }
    }
};

/// Wire type `ServerConfiguration::ClientStoreEntryPointConfiguration`.
pub const StoreEntryPointInfo = struct {
    store_id: []const u8,
    store_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!StoreEntryPointInfo {
        var value: StoreEntryPointInfo = undefined;
        value.store_id = try r.readString();
        value.store_name = try r.readString();
        return value;
    }

    pub fn encode(self: StoreEntryPointInfo, w: anytype) EncodeError!void {
        try w.writeString(self.store_id);
        try w.writeString(self.store_name);
    }
};

pub const SerializedSkinRefPieceTintColorsEntry = struct {
    key: []const u8,
    value: [4]i32,

    pub fn decode(r: *Reader) DecodeError!SerializedSkinRefPieceTintColorsEntry {
        var value: SerializedSkinRefPieceTintColorsEntry = undefined;
        value.key = try r.readString();
        for (&value.value) |*item| {
            item.* = try r.readI32();
        }
        return value;
    }

    pub fn encode(self: SerializedSkinRefPieceTintColorsEntry, w: anytype) EncodeError!void {
        try w.writeString(self.key);
        for (self.value) |item| {
            try w.writeI32(item);
        }
    }
};
