// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

/// Wire type `StructureSettings`.
pub const StructureSettings = struct {
    structure_palette_name: []const u8,
    should_ignore_entities: bool,
    should_ignore_blocks: bool,
    should_allow_non_ticking_player_and_ticking_area_chunks: bool,
    structure_size: codec.BlockPosition,
    structure_offset: codec.BlockPosition,
    last_edit_player: i64,
    rotation: types.Rotation,
    mirror: types.Mirror,
    animation_mode: types.AnimationMode,
    animation_seconds: f32,
    integrity_value: f32,
    integrity_seed: u32,
    rotation_pivot: codec.Vec3f,

    pub const actor_refs = .{
        .last_edit_player = codec.ActorRef.unique,
    };

    pub fn decode(r: *Reader) DecodeError!StructureSettings {
        var value: StructureSettings = undefined;
        value.structure_palette_name = try r.readString();
        if (value.structure_palette_name.len > 256) return error.InvalidValue;
        value.should_ignore_entities = try r.readBool();
        value.should_ignore_blocks = try r.readBool();
        value.should_allow_non_ticking_player_and_ticking_area_chunks = try r.readBool();
        value.structure_size = try r.readBlockPosition();
        value.structure_offset = try r.readBlockPosition();
        value.last_edit_player = try r.readVarI64();
        value.rotation = try types.Rotation.decode(r);
        value.mirror = try types.Mirror.decode(r);
        value.animation_mode = try types.AnimationMode.decode(r);
        value.animation_seconds = try r.readF32();
        value.integrity_value = try r.readF32();
        value.integrity_seed = try r.readU32();
        value.rotation_pivot = try r.readVec3f();
        return value;
    }

    pub fn encode(self: StructureSettings, w: anytype) EncodeError!void {
        if (self.structure_palette_name.len > 256) return error.InvalidValue;
        try w.writeString(self.structure_palette_name);
        try w.writeBool(self.should_ignore_entities);
        try w.writeBool(self.should_ignore_blocks);
        try w.writeBool(self.should_allow_non_ticking_player_and_ticking_area_chunks);
        try w.writeBlockPosition(self.structure_size);
        try w.writeBlockPosition(self.structure_offset);
        try w.writeVarI64(self.last_edit_player);
        try self.rotation.encode(w);
        try self.mirror.encode(w);
        try self.animation_mode.encode(w);
        try w.writeF32(self.animation_seconds);
        try w.writeF32(self.integrity_value);
        try w.writeU32(self.integrity_seed);
        try w.writeVec3f(self.rotation_pivot);
    }
};
