package main

import (
	"fmt"
	"math/big"
	"sort"
	"strings"
)

// patternMatchers maps each reviewed schema pattern to its hand-written Zig
// matcher in src/codec/patterns.zig; an unknown pattern fails validation.
var patternMatchers = map[string]string{
	`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.jpeg$`: "uuidJpeg",
	`^\w+:\w+$`:               "namespacedWord",
	`^(?:catmullrom|linear)$`: "splineType",
}

// builtin maps schema types onto the hand-written shared vector and position
// types, provided their wire fields match exactly.
type builtin struct {
	zig    string
	method string
	fields []string // expected "name:kind" in order
}

var builtins = map[string]builtin{
	"Vec2":        {"codec.Vec2f", "Vec2f", []string{"x:f32le", "y:f32le"}},
	"Vec3":        {"codec.Vec3f", "Vec3f", []string{"x:f32le", "y:f32le", "z:f32le"}},
	"BlockPos":    {"codec.BlockPosition", "BlockPosition", []string{"x:zigzag_i32", "y:zigzag_i32", "z:zigzag_i32"}},
	"ChunkPos":    {"codec.ChunkPosition", "ChunkPosition", []string{"x:zigzag_i32", "z:zigzag_i32"}},
	"SubChunkPos": {"codec.SubChunkPosition", "SubChunkPosition", []string{"subchunk_position_x:i32le", "subchunk_position_y:i32le", "subchunk_position_z:i32le"}},
}

func header() string {
	return "// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.\n"
}

type emitter struct {
	s         Schema
	types     map[string]*TypeDef
	recursive map[string]bool
}

type file struct {
	e       *emitter
	path    string
	domain  string // domain for shared type files; empty for packet files
	body    strings.Builder
	helpers []string
	names   map[string]bool
	memo    map[string]string // site hint -> generated helper name
}

func generate(s Schema) map[string]string {
	e := &emitter{s: s, types: s.typeMap(), recursive: map[string]bool{}}
	for name, b := range builtins {
		t := e.types[name]
		if t == nil {
			continue
		}
		var got []string
		for _, f := range t.Fields {
			got = append(got, f.Name+":"+f.Type.Kind)
		}
		if t.Kind != "struct" || strings.Join(got, ",") != strings.Join(b.fields, ",") {
			panic(fmt.Errorf("builtin %s has wire fields %v, want %v", name, got, b.fields))
		}
	}
	e.findRecursive()
	dir := "src/generated/"
	out := map[string]string{}

	byOwner := map[string][]*TypeDef{}
	byDomain := map[string][]*TypeDef{}
	for i := range s.Types {
		t := &s.Types[i]
		if _, ok := builtins[t.Name]; ok {
			continue
		}
		if t.Owner != "" {
			byOwner[t.Owner] = append(byOwner[t.Owner], t)
		} else {
			byDomain[t.Domain] = append(byDomain[t.Domain], t)
		}
	}

	for _, p := range s.Packets {
		f := e.newFile(dir+"packets/"+snake(p.Name)+".zig", "")
		f.line("//! %s (ID %d), sent by %s.", p.Wire, p.ID, describeDirections(p.Directions))
		f.imports("../../codec/support.zig", "../types.zig")
		f.line("")
		f.structDef("Packet", p.Fields, false)
		for _, t := range byOwner[p.Name] {
			f.typeDef(t)
		}
		out[f.path] = f.finish()
	}

	domains := make([]string, 0, len(byDomain))
	for d := range byDomain {
		domains = append(domains, d)
	}
	sort.Strings(domains)
	var index strings.Builder
	index.WriteString("//! Protocol types shared by more than one packet.\n" + header())
	index.WriteString("const codec = @import(\"../codec/support.zig\");\n\n")
	var builtinNames []string
	for name := range builtins {
		if e.types[name] != nil {
			builtinNames = append(builtinNames, name)
		}
	}
	sort.Strings(builtinNames)
	for _, name := range builtinNames {
		fmt.Fprintf(&index, "pub const %s = %s;\n", name, builtins[name].zig)
	}
	for _, d := range domains {
		f := e.newFile(dir+"types/"+d+".zig", d)
		f.imports("../../codec/support.zig", "../types.zig")
		for _, t := range byDomain[d] {
			f.typeDef(t)
			fmt.Fprintf(&index, "pub const %s = @import(\"types/%s.zig\").%s;\n", t.Name, d, t.Name)
		}
		out[f.path] = f.finish()
	}
	out[dir+"types.zig"] = index.String()
	out[dir+"root.zig"] = e.root()
	return out
}

func describeDirections(d []string) string {
	if len(d) == 2 {
		return "either peer"
	}
	return "the " + d[0]
}

// findRecursive marks types that can reach themselves; their codecs count
// nesting depth so hostile input cannot exhaust the stack.
func (e *emitter) findRecursive() {
	var reaches func(from, target string, seen map[string]bool) bool
	var nodeReaches func(n Node, target string, seen map[string]bool) bool
	nodeReaches = func(n Node, target string, seen map[string]bool) bool {
		for _, c := range []*Node{n.Element, n.Key, n.Value} {
			if c != nil && nodeReaches(*c, target, seen) {
				return true
			}
		}
		return n.Kind == "ref" && (n.Ref == target || reaches(n.Ref, target, seen))
	}
	reaches = func(from, target string, seen map[string]bool) bool {
		if seen[from] {
			return false
		}
		seen[from] = true
		t := e.types[from]
		for _, f := range t.Fields {
			if nodeReaches(f.Type, target, seen) {
				return true
			}
		}
		for _, v := range t.Variants {
			if v.Type != nil && nodeReaches(*v.Type, target, seen) {
				return true
			}
		}
		return false
	}
	for name := range e.types {
		if reaches(name, name, map[string]bool{}) {
			e.recursive[name] = true
		}
	}
}

func (e *emitter) newFile(path, domain string) *file {
	return &file{e: e, path: path, domain: domain, names: map[string]bool{}, memo: map[string]string{}}
}

func (f *file) line(format string, args ...any) {
	fmt.Fprintf(&f.body, format+"\n", args...)
}

func (f *file) imports(support, types string) {
	f.line("const codec = @import(%q);", support)
	f.line("const types = @import(%q);", types)
	f.line("const custom = @import(%q);", strings.Replace(support, "codec/support.zig", "custom/root.zig", 1))
	f.line("const Reader = codec.Reader;")
	f.line("const DecodeError = codec.DecodeError;")
	f.line("const EncodeError = codec.EncodeError;")
}

func (f *file) finish() string {
	var b strings.Builder
	body := f.body.String()
	if strings.HasPrefix(body, "//!") {
		end := strings.IndexByte(body, '\n') + 1
		b.WriteString(body[:end])
		body = body[end:]
	}
	b.WriteString(header())
	b.WriteString(body)
	for _, h := range f.helpers {
		b.WriteString("\n")
		b.WriteString(h)
	}
	return b.String()
}

func (f *file) typeRef(name string) string {
	if b, ok := builtins[name]; ok {
		return b.zig
	}
	t := f.e.types[name]
	if t.Owner != "" || (f.domain != "" && t.Domain == f.domain) {
		return name
	}
	return "types." + name
}

func (f *file) zigType(n Node, hint string) string {
	switch n.Kind {
	case "string", "bytes", "nbt":
		return "[]const u8"
	case "bitset":
		return fmt.Sprintf("codec.Bitset(%d)", n.Len)
	case "list":
		return fmt.Sprintf("codec.List(%s, %s)", f.zigType(*n.Element, hint+"Item"), f.codecType(*n.Element, hint+"Item"))
	case "map":
		entry := f.mapEntry(n, hint)
		return fmt.Sprintf("codec.List(%s, %s)", entry, entry)
	case "fixed":
		return fmt.Sprintf("[%d]%s", n.Len, f.zigType(*n.Element, hint))
	case "optional":
		return "?" + f.zigType(*n.Value, hint)
	case "ref":
		return f.typeRef(n.Ref)
	case "custom":
		return "custom." + n.Ref
	default:
		return primitives[n.Kind].zig
	}
}

// codecType names a type with decode/encode functions for list elements.
// Named types are their own codec; anything carrying constraints gets a
// small generated helper so the checks apply to every element.
func (f *file) codecType(n Node, hint string) string {
	plain := n.Min == nil && n.Max == nil && n.MinLen == nil && n.MaxLen == nil && n.Pattern == "" && len(n.Allowed) == 0
	switch {
	case n.Kind == "custom":
		return "custom." + n.Ref
	case n.Kind == "ref" && plain:
		if b, ok := builtins[n.Ref]; ok {
			return fmt.Sprintf("codec.Prim(.%s)", strings.ToLower(b.method[:1])+b.method[1:])
		}
		return f.typeRef(n.Ref)
	case plain && (isPrimitive(n.Kind) || n.Kind == "string" || n.Kind == "bytes"):
		return fmt.Sprintf("codec.Prim(.%s)", n.Kind)
	}
	if name, ok := f.memo["codec:"+hint]; ok {
		return name
	}
	name := f.helperName(hint + "Codec")
	f.memo["codec:"+hint] = name
	value := f.zigType(n, hint)
	var b strings.Builder
	fmt.Fprintf(&b, "const %s = struct {\n", name)
	fmt.Fprintf(&b, "    pub fn decode(r: *Reader) DecodeError!%s {\n", value)
	fmt.Fprintf(&b, "        var value: %s = undefined;\n", value)
	for _, l := range f.decode(n, "value", hint, 2) {
		b.WriteString(l)
	}
	b.WriteString("        return value;\n    }\n\n")
	fmt.Fprintf(&b, "    pub fn encode(value: %s, w: anytype) EncodeError!void {\n", value)
	for _, l := range f.encode(n, "value", hint, 2) {
		b.WriteString(l)
	}
	b.WriteString("    }\n};\n")
	f.helpers = append(f.helpers, b.String())
	return name
}

func (f *file) helperName(base string) string {
	name := base
	for i := 2; f.names[name] || f.e.types[name] != nil; i++ {
		name = fmt.Sprintf("%s%d", base, i)
	}
	f.names[name] = true
	return name
}

func (f *file) mapEntry(n Node, hint string) string {
	if name, ok := f.memo["entry:"+hint]; ok {
		return name
	}
	name := f.helperName(hint + "Entry")
	f.memo["entry:"+hint] = name
	sub := &file{e: f.e, domain: f.domain, names: f.names, memo: f.memo}
	sub.structDef(name, []Field{{Name: "key", Type: *n.Key}, {Name: "value", Type: *n.Value}}, false)
	f.helpers = append(f.helpers, sub.body.String())
	f.helpers = append(f.helpers, sub.helpers...)
	return name
}

func indent(depth int) string { return strings.Repeat("    ", depth) }

// local names a block-scoped variable; nested blocks get distinct names
// because Zig forbids shadowing.
func local(base string, depth int) string {
	if depth <= 2 {
		return base
	}
	return fmt.Sprintf("%s%d", base, depth-2)
}

func (f *file) decode(n Node, target, hint string, depth int) []string {
	in := indent(depth)
	var out []string
	add := func(format string, args ...any) { out = append(out, in+fmt.Sprintf(format, args...)+"\n") }
	switch n.Kind {
	case "string":
		add("%s = try r.readString();", target)
		out = append(out, f.lengthChecks(n, target, depth)...)
	case "bytes":
		add("%s = try r.readByteArray();", target)
		out = append(out, f.lengthChecks(n, target, depth)...)
	case "nbt":
		add("%s = try r.readNbt();", target)
	case "custom":
		add("%s = try custom.%s.decode(r);", target, n.Ref)
	case "bitset":
		add("%s = try %s.decode(r);", target, f.zigType(n, hint))
	case "list", "map":
		add("%s = blk: {", target)
		add("    const count = try r.readCount(.%s);", n.Prefix)
		out = append(out, f.itemChecks(n, "count", depth+1)...)
		add("    break :blk try %s.decode(r, count);", f.zigType(n, hint))
		add("};")
	case "fixed":
		item := local("item", depth)
		add("for (&%s) |*%s| {", target, item)
		out = append(out, f.decode(*n.Element, item+".*", hint, depth+1)...)
		add("}")
	case "optional":
		present := local("present", depth)
		inner := f.decode(*n.Value, present, hint, depth+1)
		if single := strings.TrimSpace(inner[0]); len(inner) == 1 && strings.HasPrefix(single, present+" = ") {
			add("%s = if (try r.readBool()) %s else null;", target, strings.TrimSuffix(strings.TrimPrefix(single, present+" = "), ";"))
			break
		}
		add("%s = null;", target)
		add("if (try r.readBool()) {")
		add("    var %s: %s = undefined;", present, f.zigType(*n.Value, hint))
		out = append(out, inner...)
		add("    %s = %s;", target, present)
		add("}")
	case "ref":
		if b, ok := builtins[n.Ref]; ok {
			add("%s = try r.read%s();", target, b.method)
			break
		}
		add("%s = try %s.decode(r);", target, f.typeRef(n.Ref))
		out = append(out, f.allowedCheck(n, target, depth)...)
	default:
		add("%s = try r.%s();", target, primitives[n.Kind].read)
		out = append(out, f.boundChecks(n, target, depth)...)
	}
	return out
}

func (f *file) encode(n Node, value, hint string, depth int) []string {
	in := indent(depth)
	var out []string
	add := func(format string, args ...any) { out = append(out, in+fmt.Sprintf(format, args...)+"\n") }
	switch n.Kind {
	case "string":
		out = append(out, f.lengthChecks(n, value, depth)...)
		add("try w.writeString(%s);", value)
	case "bytes":
		out = append(out, f.lengthChecks(n, value, depth)...)
		add("try w.writeByteArray(%s);", value)
	case "nbt":
		add("try w.writeNbt(%s);", value)
	case "custom":
		add("try %s.encode(w);", value)
	case "bitset":
		add("try %s.encode(w);", value)
	case "list", "map":
		out = append(out, f.itemChecks(n, value+".len", depth)...)
		add("try w.writeCount(.%s, %s.len);", n.Prefix, value)
		add("try %s.encode(w);", value)
	case "fixed":
		item := local("item", depth)
		add("for (%s) |%s| {", value, item)
		out = append(out, f.encode(*n.Element, item, hint, depth+1)...)
		add("}")
	case "optional":
		present := local("present", depth)
		add("try w.writeBool(%s != null);", value)
		add("if (%s) |%s| {", value, present)
		out = append(out, f.encode(*n.Value, present, hint, depth+1)...)
		add("}")
	case "ref":
		if b, ok := builtins[n.Ref]; ok {
			add("try w.write%s(%s);", b.method, value)
			break
		}
		out = append(out, f.allowedCheck(n, value, depth)...)
		add("try %s.encode(w);", value)
	default:
		out = append(out, f.boundChecks(n, value, depth)...)
		add("try w.%s(%s);", primitives[n.Kind].write, value)
	}
	return out
}

func (f *file) lengthChecks(n Node, value string, depth int) []string {
	var out []string
	in := indent(depth)
	if n.MinLen != nil && *n.MinLen > 0 {
		out = append(out, fmt.Sprintf("%sif (%s.len < %d) return error.InvalidValue;\n", in, value, *n.MinLen))
	}
	if n.MaxLen != nil {
		out = append(out, fmt.Sprintf("%sif (%s.len > %d) return error.InvalidValue;\n", in, value, *n.MaxLen))
	}
	if n.Pattern != "" {
		out = append(out, fmt.Sprintf("%sif (!codec.patterns.%s(%s)) return error.InvalidValue;\n", in, patternMatchers[n.Pattern], value))
	}
	return out
}

func (f *file) itemChecks(n Node, count string, depth int) []string {
	var out []string
	in := indent(depth)
	if n.MinItems != nil && *n.MinItems > 0 {
		out = append(out, fmt.Sprintf("%sif (%s < %d) return error.InvalidValue;\n", in, count, *n.MinItems))
	}
	if n.MaxItems != nil && *n.MaxItems < 1<<32 {
		out = append(out, fmt.Sprintf("%sif (%s > %d) return error.InvalidValue;\n", in, count, *n.MaxItems))
	}
	return out
}

func integerRange(zig string) (*big.Int, *big.Int) {
	bits := map[string]uint{"u8": 8, "i8": 8, "u16": 16, "i16": 16, "u32": 32, "i32": 32, "u64": 64, "i64": 64}[zig]
	one := big.NewInt(1)
	if strings.HasPrefix(zig, "i") {
		limit := new(big.Int).Lsh(one, bits-1)
		return new(big.Int).Neg(limit), new(big.Int).Sub(limit, one)
	}
	return big.NewInt(0), new(big.Int).Sub(new(big.Int).Lsh(one, bits), one)
}

// boundChecks enforces schema numeric bounds. Integer bounds outside the
// field's range are rejected at generation time; float bounds also reject NaN.
func (f *file) boundChecks(n Node, value string, depth int) []string {
	var out []string
	in := indent(depth)
	zig := primitives[n.Kind].zig
	if zig == "f32" || zig == "f64" {
		if n.Min != nil {
			out = append(out, fmt.Sprintf("%sif (!(%s >= %s)) return error.InvalidValue;\n", in, value, n.Min.String()))
		}
		if n.Max != nil {
			out = append(out, fmt.Sprintf("%sif (!(%s <= %s)) return error.InvalidValue;\n", in, value, n.Max.String()))
		}
		return out
	}
	lo, hi := integerRange(zig)
	parse := func(s string) *big.Int {
		v, ok := new(big.Int).SetString(s, 10)
		if !ok {
			panic(fmt.Errorf("integer bound %q on %s is not an integer", s, value))
		}
		return v
	}
	if n.Min != nil {
		if v := parse(n.Min.String()); v.Cmp(hi) > 0 {
			panic(fmt.Errorf("minimum %s cannot be satisfied by %s", v, zig))
		} else if v.Cmp(lo) > 0 {
			out = append(out, fmt.Sprintf("%sif (%s < %s) return error.InvalidValue;\n", in, value, v))
		}
	}
	if n.Max != nil {
		if v := parse(n.Max.String()); v.Cmp(lo) < 0 {
			panic(fmt.Errorf("maximum %s cannot be satisfied by %s", v, zig))
		} else if v.Cmp(hi) < 0 {
			out = append(out, fmt.Sprintf("%sif (%s > %s) return error.InvalidValue;\n", in, value, v))
		}
	}
	return out
}

func (f *file) allowedCheck(n Node, value string, depth int) []string {
	if len(n.Allowed) == 0 {
		return nil
	}
	t := f.e.types[n.Ref]
	var names []string
	for _, a := range n.Allowed {
		for _, v := range t.Values {
			if v.Value == a {
				names = append(names, "."+ident(v.Name))
			}
		}
	}
	in := indent(depth)
	return []string{
		fmt.Sprintf("%sswitch (%s) {\n", in, value),
		fmt.Sprintf("%s    %s => {},\n", in, strings.Join(names, ", ")),
		fmt.Sprintf("%s    else => return error.InvalidValue,\n", in),
		fmt.Sprintf("%s}\n", in),
	}
}

func (f *file) typeDef(t *TypeDef) {
	f.line("")
	if len(t.Wire) != 0 {
		f.line("/// Wire type `%s`.", t.Wire[0])
	}
	switch t.Kind {
	case "struct":
		f.structDef(t.Name, t.Fields, f.e.recursive[t.Name], t.Checks...)
	case "enum":
		f.enumDef(t)
	case "union":
		f.unionDef(t)
	}
}

func (f *file) structDef(name string, fields []Field, recursive bool, checks ...Check) {
	f.names[name] = true
	f.line("pub const %s = struct {", name)
	for _, field := range fields {
		f.line("    %s: %s,", ident(field.Name), f.zigType(field.Type, name+pascal(field.Name)))
	}
	if len(fields) != 0 {
		f.line("")
	}
	f.line("    pub fn decode(r: *Reader) DecodeError!%s {", name)
	if len(fields) == 0 {
		f.line("        _ = r;")
		f.line("        return .{};")
	} else {
		if recursive {
			f.line("        try r.enter();")
			f.line("        defer r.leave();")
		}
		f.line("        var value: %s = undefined;", name)
		for _, field := range fields {
			for _, l := range f.decode(field.Type, "value."+ident(field.Name), name+pascal(field.Name), 2) {
				f.body.WriteString(l)
			}
		}
		f.checks(checks, "value")
		f.line("        return value;")
	}
	f.line("    }")
	f.line("")
	f.line("    pub fn encode(self: %s, w: anytype) EncodeError!void {", name)
	if len(fields) == 0 {
		f.line("        _ = self;")
		f.line("        _ = w;")
	} else {
		if recursive {
			f.line("        try w.enter();")
			f.line("        defer w.leave();")
		}
		f.checks(checks, "self")
		for _, field := range fields {
			for _, l := range f.encode(field.Type, "self."+ident(field.Name), name+pascal(field.Name), 2) {
				f.body.WriteString(l)
			}
		}
	}
	f.line("    }")
	f.line("};")
}

func (f *file) checks(checks []Check, v string) {
	for _, c := range checks {
		factors := make([]string, len(c.Factors))
		for i, factor := range c.Factors {
			factors[i] = v + "." + ident(factor)
		}
		scale := c.Scale
		if scale == 0 {
			scale = 1
		}
		f.line("        if (!codec.lengthIsProduct(%s.%s.len, .{ %s }, %d)) return error.InvalidValue;", v, ident(c.Field), strings.Join(factors, ", "), scale)
	}
}

func (f *file) enumDef(t *TypeDef) {
	info := primitives[t.Repr]
	f.line("pub const %s = enum(%s) {", t.Name, info.zig)
	for _, v := range t.Values {
		f.line("    %s = %d,", ident(v.Name), v.Value)
	}
	lo, hi := integerRange(info.zig)
	span := new(big.Int).Add(new(big.Int).Sub(hi, lo), big.NewInt(1))
	if span.Cmp(big.NewInt(int64(len(t.Values)))) != 0 {
		f.line("    _,")
	}
	f.line("")
	f.line("    pub fn decode(r: *Reader) DecodeError!%s {", t.Name)
	f.line("        return @fromBackingInt(@intCast(try r.%s()));", info.read)
	f.line("    }")
	f.line("")
	f.line("    pub fn encode(self: %s, w: anytype) EncodeError!void {", t.Name)
	f.line("        try w.%s(@backingInt(self));", info.write)
	f.line("    }")
	f.line("};")
}

func (f *file) unionDef(t *TypeDef) {
	info := primitives[t.Repr]
	sequential := true
	for i, v := range t.Variants {
		sequential = sequential && v.Value == int64(i)
	}
	tag := fmt.Sprintf("enum(%s)", info.zig)
	if !sequential {
		tag = t.Name + "Tag"
		f.line("pub const %s = enum(%s) {", tag, info.zig)
		for _, v := range t.Variants {
			f.line("    %s = %d,", ident(v.Name), v.Value)
		}
		f.line("};")
		f.line("")
	}
	f.line("pub const %s = union(%s) {", t.Name, tag)
	for _, v := range t.Variants {
		if v.Type == nil {
			f.line("    %s,", ident(v.Name))
		} else {
			f.line("    %s: %s,", ident(v.Name), f.zigType(*v.Type, t.Name+pascal(v.Name)))
		}
	}
	recursive := f.e.recursive[t.Name]
	f.line("")
	f.line("    pub fn decode(r: *Reader) DecodeError!%s {", t.Name)
	if recursive {
		f.line("        try r.enter();")
		f.line("        defer r.leave();")
	}
	f.line("        switch (try r.%s()) {", info.read)
	for _, v := range t.Variants {
		if v.Type == nil {
			f.line("            %d => return .%s,", v.Value, ident(v.Name))
			continue
		}
		lines := f.decode(*v.Type, "value", t.Name+pascal(v.Name), 4)
		if single := strings.TrimSpace(lines[0]); len(lines) == 1 && strings.HasPrefix(single, "value = ") {
			f.line("            %d => return .{ .%s = %s },", v.Value, ident(v.Name), strings.TrimSuffix(strings.TrimPrefix(single, "value = "), ";"))
			continue
		}
		f.line("            %d => {", v.Value)
		f.line("                var value: %s = undefined;", f.zigType(*v.Type, t.Name+pascal(v.Name)))
		for _, l := range lines {
			f.body.WriteString(l)
		}
		f.line("                return .{ .%s = value };", ident(v.Name))
		f.line("            },")
	}
	f.line("            else => return error.InvalidEnum,")
	f.line("        }")
	f.line("    }")
	f.line("")
	f.line("    pub fn encode(self: %s, w: anytype) EncodeError!void {", t.Name)
	if recursive {
		f.line("        try w.enter();")
		f.line("        defer w.leave();")
	}
	f.line("        try w.%s(@backingInt(self));", info.write)
	f.line("        switch (self) {")
	for _, v := range t.Variants {
		if v.Type == nil {
			f.line("            .%s => {},", ident(v.Name))
			continue
		}
		f.line("            .%s => |value| {", ident(v.Name))
		for _, l := range f.encode(*v.Type, "value", t.Name+pascal(v.Name), 4) {
			f.body.WriteString(l)
		}
		f.line("            },")
	}
	f.line("        }")
	f.line("    }")
	f.line("};")
}

var zigKeywords = map[string]bool{
	"addrspace": true, "align": true, "allowzero": true, "and": true, "anyframe": true, "anytype": true, "asm": true,
	"break": true, "callconv": true, "catch": true, "comptime": true, "const": true, "continue": true, "defer": true,
	"else": true, "enum": true, "errdefer": true, "error": true, "export": true, "extern": true, "fn": true, "for": true,
	"if": true, "inline": true, "linksection": true, "noalias": true, "noinline": true, "nosuspend": true, "opaque": true,
	"or": true, "orelse": true, "packed": true, "pub": true, "resume": true, "return": true, "struct": true,
	"suspend": true, "switch": true, "test": true, "threadlocal": true, "try": true, "union": true, "unreachable": true,
	"var": true, "volatile": true, "while": true,
}

func ident(name string) string {
	if zigKeywords[name] {
		return "@\"" + name + "\""
	}
	return name
}

func (e *emitter) root() string {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	p("//! Minecraft %s, protocol %d.", e.s.Target.MinecraftVersion, e.s.Target.ProtocolVersion)
	b.WriteString(header())
	p("const codec = @import(\"../codec/support.zig\");")
	p("")
	p("pub const protocol_version: u32 = %d;", e.s.Target.ProtocolVersion)
	p("pub const minecraft_version = %q;", e.s.Target.MinecraftVersion)
	p("pub const types = @import(\"types.zig\");")
	p("")
	p("pub const packets = struct {")
	for _, pk := range e.s.Packets {
		p("    pub const %s = @import(\"packets/%s.zig\");", ident(snake(pk.Name)), snake(pk.Name))
	}
	p("};")
	p("")
	p("/// Every packet this protocol version defines. Ordinals are not wire IDs.")
	p("pub const Kind = enum {")
	for _, pk := range e.s.Packets {
		p("    %s,", ident(snake(pk.Name)))
	}
	p("};")
	p("")
	p("/// Wire packet IDs, open so unknown IDs remain representable.")
	p("pub const Id = enum(u10) {")
	for _, pk := range e.s.Packets {
		p("    %s = %d,", ident(snake(pk.Name)), pk.ID)
	}
	p("    _,")
	p("};")
	p("")
	p("pub const Direction = enum { client_to_server, server_to_client, bidirectional };")
	p("")
	p("pub fn packetKind(id: u10) ?Kind {")
	p("    return switch (id) {")
	for _, pk := range e.s.Packets {
		p("        %d => .%s,", pk.ID, ident(snake(pk.Name)))
	}
	p("        else => null,")
	p("    };")
	p("}")
	p("")
	p("pub fn packetId(kind: Kind) u10 {")
	p("    return switch (kind) {")
	for _, pk := range e.s.Packets {
		p("        .%s => %d,", ident(snake(pk.Name)), pk.ID)
	}
	p("    };")
	p("}")
	p("")
	p("pub fn packetDirection(kind: Kind) Direction {")
	p("    return switch (kind) {")
	for _, pk := range e.s.Packets {
		d := "bidirectional"
		if len(pk.Directions) == 1 {
			d = map[string]string{"client": "client_to_server", "server": "server_to_client"}[pk.Directions[0]]
		}
		p("        .%s => .%s,", ident(snake(pk.Name)), d)
	}
	p("    };")
	p("}")
	p("")
	p("/// A decoded packet payload. Slices and lists borrow the decoded input.")
	p("pub const Packet = union(Kind) {")
	for _, pk := range e.s.Packets {
		p("    %s: packets.%s.Packet,", ident(snake(pk.Name)), ident(snake(pk.Name)))
	}
	p("};")
	p("")
	p("pub fn decodePayload(r: *codec.Reader, kind: Kind) codec.DecodeError!Packet {")
	p("    switch (kind) {")
	p("        inline else => |tag| return @unionInit(Packet, @tagName(tag), try @field(packets, @tagName(tag)).Packet.decode(r)),")
	p("    }")
	p("}")
	p("")
	p("pub fn encodePayload(w: anytype, value: Packet) codec.EncodeError!void {")
	p("    switch (value) {")
	p("        inline else => |payload| try payload.encode(w),")
	p("    }")
	p("}")
	return b.String()
}
