// Generated current protocol registry. Semantic ordinals are not wire IDs.
pub const PacketKind = enum {
    login,
    play_status,
    server_to_client_handshake,
    client_to_server_handshake,
    disconnect,
    resource_packs_info,
    resource_pack_stack,
    resource_pack_client_response,
    text,
    set_time,
    start_game,
    add_player,
    add_actor,
    remove_actor,
    add_item_actor,
    server_player_post_move_position,
    take_item_actor,
    move_actor_absolute,
    move_player,
    update_block,
    add_painting,
    level_event,
    block_event,
    actor_event,
    mob_effect,
    update_attributes,
    inventory_transaction,
    mob_equipment,
    mob_armour_equipment,
    interact,
    block_pick_request,
    actor_pick_request,
    player_action,
    hurt_armour,
    set_actor_data,
    set_actor_motion,
    set_actor_link,
    set_health,
    set_spawn_position,
    animate,
    respawn,
    container_open,
    container_close,
    player_hot_bar,
    inventory_content,
    inventory_slot,
    container_set_data,
    crafting_data,
    g_u_i_data_pick_item,
    adventure_settings,
    block_actor_data,
    level_chunk,
    set_commands_enabled,
    set_difficulty,
    change_dimension,
    set_player_game_type,
    player_list,
    simple_event,
    event,
    spawn_experience_orb,
    client_bound_map_item_data,
    map_info_request,
    request_chunk_radius,
    chunk_radius_updated,
    game_rules_changed,
    camera,
    boss_event,
    show_credits,
    available_commands,
    command_request,
    command_block_update,
    command_output,
    update_trade,
    update_equip,
    resource_pack_data_info,
    resource_pack_chunk_data,
    resource_pack_chunk_request,
    transfer,
    play_sound,
    stop_sound,
    set_title,
    add_behaviour_tree,
    structure_block_update,
    show_store_offer,
    purchase_receipt,
    player_skin,
    sub_client_login,
    automation_client_connect,
    set_last_hurt_by,
    book_edit,
    n_p_c_request,
    photo_transfer,
    modal_form_request,
    modal_form_response,
    server_settings_request,
    server_settings_response,
    show_profile,
    set_default_game_type,
    remove_objective,
    set_display_objective,
    set_score,
    lab_table,
    update_block_synced,
    move_actor_delta,
    set_scoreboard_identity,
    set_local_player_as_initialised,
    update_soft_enum,
    network_stack_latency,
    script_custom_event,
    spawn_particle_effect,
    available_actor_identifiers,
    network_chunk_publisher_update,
    biome_definition_list,
    level_sound_event,
    level_event_generic,
    lectern_update,
    client_cache_status,
    on_screen_texture_animation,
    map_create_locked_copy,
    structure_template_data_request,
    structure_template_data_response,
    client_cache_blob_status,
    client_cache_miss_response,
    education_settings,
    emote,
    multi_player_settings,
    settings_command,
    anvil_damage,
    completed_using_item,
    network_settings,
    player_auth_input,
    creative_content,
    player_enchant_options,
    item_stack_request,
    item_stack_response,
    player_armour_damage,
    code_builder,
    update_player_game_type,
    emote_list,
    position_tracking_d_b_server_broadcast,
    position_tracking_d_b_client_request,
    debug_info,
    packet_violation_warning,
    motion_prediction_hints,
    animate_entity,
    camera_shake,
    player_fog,
    correct_player_move_prediction,
    item_registry,
    filter_text,
    client_bound_debug_renderer,
    sync_actor_property,
    add_volume_entity,
    remove_volume_entity,
    simulation_type,
    n_p_c_dialogue,
    education_resource_u_r_i,
    create_photo,
    update_sub_chunk_blocks,
    photo_info_request,
    sub_chunk,
    sub_chunk_request,
    client_start_item_cooldown,
    script_message,
    code_builder_source,
    ticking_areas_load_status,
    dimension_data,
    agent_action,
    change_mob_property,
    lesson_progress,
    request_ability,
    request_permissions,
    toast_request,
    update_abilities,
    update_adventure_settings,
    death_info,
    editor_network,
    feature_registry,
    server_stats,
    request_network_settings,
    game_test_request,
    game_test_results,
    update_client_input_locks,
    client_cheat_ability,
    camera_presets,
    unlocked_recipes,
    camera_instruction,
    trim_data,
    open_sign,
    agent_animation,
    refresh_entitlements,
    player_toggle_crafter_slot_request,
    set_player_inventory_options,
    set_hud,
    award_achievement,
    client_bound_close_form,
    server_bound_loading_screen,
    jigsaw_structure_data,
    current_structure_feature,
    server_bound_diagnostics,
    camera_aim_assist,
    container_registry_cleanup,
    movement_effect,
    camera_aim_assist_presets,
    client_camera_aim_assist,
    client_movement_prediction_sync,
    update_client_options,
    player_video_capture,
    player_update_entity_overrides,
    player_location,
    client_bound_control_scheme_set,
    primitive_shapes,
    server_bound_pack_setting_change,
    client_bound_data_store,
    graphics_override_parameter,
    server_bound_data_store,
    client_bound_data_driven_u_i_show_screen,
    client_bound_data_driven_u_i_close_screen,
    client_bound_data_driven_u_i_reload,
    client_bound_texture_shift,
    voxel_shapes,
    camera_spline,
    camera_aim_assist_actor_priority,
    resource_packs_ready_for_validation,
    locator_bar,
    party_changed,
    server_bound_data_driven_screen_closed,
    sync_world_clocks,
    client_bound_attribute_layer_sync,
    server_store_info,
    server_presence_info,
    clientbound_update_sound_data,
    send_party_destination_cookie,
    party_destination_cookie_response,
    set_player_furnace_options,
    record_started,
};
pub fn packetKind(id: u10) ?PacketKind {
    return switch (id) {
        1 => .login,
        2 => .play_status,
        3 => .server_to_client_handshake,
        4 => .client_to_server_handshake,
        5 => .disconnect,
        6 => .resource_packs_info,
        7 => .resource_pack_stack,
        8 => .resource_pack_client_response,
        9 => .text,
        10 => .set_time,
        11 => .start_game,
        12 => .add_player,
        13 => .add_actor,
        14 => .remove_actor,
        15 => .add_item_actor,
        16 => .server_player_post_move_position,
        17 => .take_item_actor,
        18 => .move_actor_absolute,
        19 => .move_player,
        21 => .update_block,
        22 => .add_painting,
        25 => .level_event,
        26 => .block_event,
        27 => .actor_event,
        28 => .mob_effect,
        29 => .update_attributes,
        30 => .inventory_transaction,
        31 => .mob_equipment,
        32 => .mob_armour_equipment,
        33 => .interact,
        34 => .block_pick_request,
        35 => .actor_pick_request,
        36 => .player_action,
        38 => .hurt_armour,
        39 => .set_actor_data,
        40 => .set_actor_motion,
        41 => .set_actor_link,
        42 => .set_health,
        43 => .set_spawn_position,
        44 => .animate,
        45 => .respawn,
        46 => .container_open,
        47 => .container_close,
        48 => .player_hot_bar,
        49 => .inventory_content,
        50 => .inventory_slot,
        51 => .container_set_data,
        52 => .crafting_data,
        54 => .g_u_i_data_pick_item,
        55 => .adventure_settings,
        56 => .block_actor_data,
        58 => .level_chunk,
        59 => .set_commands_enabled,
        60 => .set_difficulty,
        61 => .change_dimension,
        62 => .set_player_game_type,
        63 => .player_list,
        64 => .simple_event,
        65 => .event,
        66 => .spawn_experience_orb,
        67 => .client_bound_map_item_data,
        68 => .map_info_request,
        69 => .request_chunk_radius,
        70 => .chunk_radius_updated,
        72 => .game_rules_changed,
        73 => .camera,
        74 => .boss_event,
        75 => .show_credits,
        76 => .available_commands,
        77 => .command_request,
        78 => .command_block_update,
        79 => .command_output,
        80 => .update_trade,
        81 => .update_equip,
        82 => .resource_pack_data_info,
        83 => .resource_pack_chunk_data,
        84 => .resource_pack_chunk_request,
        85 => .transfer,
        86 => .play_sound,
        87 => .stop_sound,
        88 => .set_title,
        89 => .add_behaviour_tree,
        90 => .structure_block_update,
        91 => .show_store_offer,
        92 => .purchase_receipt,
        93 => .player_skin,
        94 => .sub_client_login,
        95 => .automation_client_connect,
        96 => .set_last_hurt_by,
        97 => .book_edit,
        98 => .n_p_c_request,
        99 => .photo_transfer,
        100 => .modal_form_request,
        101 => .modal_form_response,
        102 => .server_settings_request,
        103 => .server_settings_response,
        104 => .show_profile,
        105 => .set_default_game_type,
        106 => .remove_objective,
        107 => .set_display_objective,
        108 => .set_score,
        109 => .lab_table,
        110 => .update_block_synced,
        111 => .move_actor_delta,
        112 => .set_scoreboard_identity,
        113 => .set_local_player_as_initialised,
        114 => .update_soft_enum,
        115 => .network_stack_latency,
        117 => .script_custom_event,
        118 => .spawn_particle_effect,
        119 => .available_actor_identifiers,
        121 => .network_chunk_publisher_update,
        122 => .biome_definition_list,
        123 => .level_sound_event,
        124 => .level_event_generic,
        125 => .lectern_update,
        129 => .client_cache_status,
        130 => .on_screen_texture_animation,
        131 => .map_create_locked_copy,
        132 => .structure_template_data_request,
        133 => .structure_template_data_response,
        135 => .client_cache_blob_status,
        136 => .client_cache_miss_response,
        137 => .education_settings,
        138 => .emote,
        139 => .multi_player_settings,
        140 => .settings_command,
        141 => .anvil_damage,
        142 => .completed_using_item,
        143 => .network_settings,
        144 => .player_auth_input,
        145 => .creative_content,
        146 => .player_enchant_options,
        147 => .item_stack_request,
        148 => .item_stack_response,
        149 => .player_armour_damage,
        150 => .code_builder,
        151 => .update_player_game_type,
        152 => .emote_list,
        153 => .position_tracking_d_b_server_broadcast,
        154 => .position_tracking_d_b_client_request,
        155 => .debug_info,
        156 => .packet_violation_warning,
        157 => .motion_prediction_hints,
        158 => .animate_entity,
        159 => .camera_shake,
        160 => .player_fog,
        161 => .correct_player_move_prediction,
        162 => .item_registry,
        163 => .filter_text,
        164 => .client_bound_debug_renderer,
        165 => .sync_actor_property,
        166 => .add_volume_entity,
        167 => .remove_volume_entity,
        168 => .simulation_type,
        169 => .n_p_c_dialogue,
        170 => .education_resource_u_r_i,
        171 => .create_photo,
        172 => .update_sub_chunk_blocks,
        173 => .photo_info_request,
        174 => .sub_chunk,
        175 => .sub_chunk_request,
        176 => .client_start_item_cooldown,
        177 => .script_message,
        178 => .code_builder_source,
        179 => .ticking_areas_load_status,
        180 => .dimension_data,
        181 => .agent_action,
        182 => .change_mob_property,
        183 => .lesson_progress,
        184 => .request_ability,
        185 => .request_permissions,
        186 => .toast_request,
        187 => .update_abilities,
        188 => .update_adventure_settings,
        189 => .death_info,
        190 => .editor_network,
        191 => .feature_registry,
        192 => .server_stats,
        193 => .request_network_settings,
        194 => .game_test_request,
        195 => .game_test_results,
        196 => .update_client_input_locks,
        197 => .client_cheat_ability,
        198 => .camera_presets,
        199 => .unlocked_recipes,
        300 => .camera_instruction,
        302 => .trim_data,
        303 => .open_sign,
        304 => .agent_animation,
        305 => .refresh_entitlements,
        306 => .player_toggle_crafter_slot_request,
        307 => .set_player_inventory_options,
        308 => .set_hud,
        309 => .award_achievement,
        310 => .client_bound_close_form,
        312 => .server_bound_loading_screen,
        313 => .jigsaw_structure_data,
        314 => .current_structure_feature,
        315 => .server_bound_diagnostics,
        316 => .camera_aim_assist,
        317 => .container_registry_cleanup,
        318 => .movement_effect,
        320 => .camera_aim_assist_presets,
        321 => .client_camera_aim_assist,
        322 => .client_movement_prediction_sync,
        323 => .update_client_options,
        324 => .player_video_capture,
        325 => .player_update_entity_overrides,
        326 => .player_location,
        327 => .client_bound_control_scheme_set,
        328 => .primitive_shapes,
        329 => .server_bound_pack_setting_change,
        330 => .client_bound_data_store,
        331 => .graphics_override_parameter,
        332 => .server_bound_data_store,
        333 => .client_bound_data_driven_u_i_show_screen,
        334 => .client_bound_data_driven_u_i_close_screen,
        335 => .client_bound_data_driven_u_i_reload,
        336 => .client_bound_texture_shift,
        337 => .voxel_shapes,
        338 => .camera_spline,
        339 => .camera_aim_assist_actor_priority,
        340 => .resource_packs_ready_for_validation,
        341 => .locator_bar,
        342 => .party_changed,
        343 => .server_bound_data_driven_screen_closed,
        344 => .sync_world_clocks,
        345 => .client_bound_attribute_layer_sync,
        346 => .server_store_info,
        347 => .server_presence_info,
        348 => .clientbound_update_sound_data,
        349 => .send_party_destination_cookie,
        350 => .party_destination_cookie_response,
        351 => .set_player_furnace_options,
        352 => .record_started,
        else => null,
    };
}
pub fn packetId(kind: PacketKind) ?u10 {
    return switch (kind) {
        .login => 1,
        .play_status => 2,
        .server_to_client_handshake => 3,
        .client_to_server_handshake => 4,
        .disconnect => 5,
        .resource_packs_info => 6,
        .resource_pack_stack => 7,
        .resource_pack_client_response => 8,
        .text => 9,
        .set_time => 10,
        .start_game => 11,
        .add_player => 12,
        .add_actor => 13,
        .remove_actor => 14,
        .add_item_actor => 15,
        .server_player_post_move_position => 16,
        .take_item_actor => 17,
        .move_actor_absolute => 18,
        .move_player => 19,
        .update_block => 21,
        .add_painting => 22,
        .level_event => 25,
        .block_event => 26,
        .actor_event => 27,
        .mob_effect => 28,
        .update_attributes => 29,
        .inventory_transaction => 30,
        .mob_equipment => 31,
        .mob_armour_equipment => 32,
        .interact => 33,
        .block_pick_request => 34,
        .actor_pick_request => 35,
        .player_action => 36,
        .hurt_armour => 38,
        .set_actor_data => 39,
        .set_actor_motion => 40,
        .set_actor_link => 41,
        .set_health => 42,
        .set_spawn_position => 43,
        .animate => 44,
        .respawn => 45,
        .container_open => 46,
        .container_close => 47,
        .player_hot_bar => 48,
        .inventory_content => 49,
        .inventory_slot => 50,
        .container_set_data => 51,
        .crafting_data => 52,
        .g_u_i_data_pick_item => 54,
        .adventure_settings => 55,
        .block_actor_data => 56,
        .level_chunk => 58,
        .set_commands_enabled => 59,
        .set_difficulty => 60,
        .change_dimension => 61,
        .set_player_game_type => 62,
        .player_list => 63,
        .simple_event => 64,
        .event => 65,
        .spawn_experience_orb => 66,
        .client_bound_map_item_data => 67,
        .map_info_request => 68,
        .request_chunk_radius => 69,
        .chunk_radius_updated => 70,
        .game_rules_changed => 72,
        .camera => 73,
        .boss_event => 74,
        .show_credits => 75,
        .available_commands => 76,
        .command_request => 77,
        .command_block_update => 78,
        .command_output => 79,
        .update_trade => 80,
        .update_equip => 81,
        .resource_pack_data_info => 82,
        .resource_pack_chunk_data => 83,
        .resource_pack_chunk_request => 84,
        .transfer => 85,
        .play_sound => 86,
        .stop_sound => 87,
        .set_title => 88,
        .add_behaviour_tree => 89,
        .structure_block_update => 90,
        .show_store_offer => 91,
        .purchase_receipt => 92,
        .player_skin => 93,
        .sub_client_login => 94,
        .automation_client_connect => 95,
        .set_last_hurt_by => 96,
        .book_edit => 97,
        .n_p_c_request => 98,
        .photo_transfer => 99,
        .modal_form_request => 100,
        .modal_form_response => 101,
        .server_settings_request => 102,
        .server_settings_response => 103,
        .show_profile => 104,
        .set_default_game_type => 105,
        .remove_objective => 106,
        .set_display_objective => 107,
        .set_score => 108,
        .lab_table => 109,
        .update_block_synced => 110,
        .move_actor_delta => 111,
        .set_scoreboard_identity => 112,
        .set_local_player_as_initialised => 113,
        .update_soft_enum => 114,
        .network_stack_latency => 115,
        .script_custom_event => 117,
        .spawn_particle_effect => 118,
        .available_actor_identifiers => 119,
        .network_chunk_publisher_update => 121,
        .biome_definition_list => 122,
        .level_sound_event => 123,
        .level_event_generic => 124,
        .lectern_update => 125,
        .client_cache_status => 129,
        .on_screen_texture_animation => 130,
        .map_create_locked_copy => 131,
        .structure_template_data_request => 132,
        .structure_template_data_response => 133,
        .client_cache_blob_status => 135,
        .client_cache_miss_response => 136,
        .education_settings => 137,
        .emote => 138,
        .multi_player_settings => 139,
        .settings_command => 140,
        .anvil_damage => 141,
        .completed_using_item => 142,
        .network_settings => 143,
        .player_auth_input => 144,
        .creative_content => 145,
        .player_enchant_options => 146,
        .item_stack_request => 147,
        .item_stack_response => 148,
        .player_armour_damage => 149,
        .code_builder => 150,
        .update_player_game_type => 151,
        .emote_list => 152,
        .position_tracking_d_b_server_broadcast => 153,
        .position_tracking_d_b_client_request => 154,
        .debug_info => 155,
        .packet_violation_warning => 156,
        .motion_prediction_hints => 157,
        .animate_entity => 158,
        .camera_shake => 159,
        .player_fog => 160,
        .correct_player_move_prediction => 161,
        .item_registry => 162,
        .filter_text => 163,
        .client_bound_debug_renderer => 164,
        .sync_actor_property => 165,
        .add_volume_entity => 166,
        .remove_volume_entity => 167,
        .simulation_type => 168,
        .n_p_c_dialogue => 169,
        .education_resource_u_r_i => 170,
        .create_photo => 171,
        .update_sub_chunk_blocks => 172,
        .photo_info_request => 173,
        .sub_chunk => 174,
        .sub_chunk_request => 175,
        .client_start_item_cooldown => 176,
        .script_message => 177,
        .code_builder_source => 178,
        .ticking_areas_load_status => 179,
        .dimension_data => 180,
        .agent_action => 181,
        .change_mob_property => 182,
        .lesson_progress => 183,
        .request_ability => 184,
        .request_permissions => 185,
        .toast_request => 186,
        .update_abilities => 187,
        .update_adventure_settings => 188,
        .death_info => 189,
        .editor_network => 190,
        .feature_registry => 191,
        .server_stats => 192,
        .request_network_settings => 193,
        .game_test_request => 194,
        .game_test_results => 195,
        .update_client_input_locks => 196,
        .client_cheat_ability => 197,
        .camera_presets => 198,
        .unlocked_recipes => 199,
        .camera_instruction => 300,
        .trim_data => 302,
        .open_sign => 303,
        .agent_animation => 304,
        .refresh_entitlements => 305,
        .player_toggle_crafter_slot_request => 306,
        .set_player_inventory_options => 307,
        .set_hud => 308,
        .award_achievement => 309,
        .client_bound_close_form => 310,
        .server_bound_loading_screen => 312,
        .jigsaw_structure_data => 313,
        .current_structure_feature => 314,
        .server_bound_diagnostics => 315,
        .camera_aim_assist => 316,
        .container_registry_cleanup => 317,
        .movement_effect => 318,
        .camera_aim_assist_presets => 320,
        .client_camera_aim_assist => 321,
        .client_movement_prediction_sync => 322,
        .update_client_options => 323,
        .player_video_capture => 324,
        .player_update_entity_overrides => 325,
        .player_location => 326,
        .client_bound_control_scheme_set => 327,
        .primitive_shapes => 328,
        .server_bound_pack_setting_change => 329,
        .client_bound_data_store => 330,
        .graphics_override_parameter => 331,
        .server_bound_data_store => 332,
        .client_bound_data_driven_u_i_show_screen => 333,
        .client_bound_data_driven_u_i_close_screen => 334,
        .client_bound_data_driven_u_i_reload => 335,
        .client_bound_texture_shift => 336,
        .voxel_shapes => 337,
        .camera_spline => 338,
        .camera_aim_assist_actor_priority => 339,
        .resource_packs_ready_for_validation => 340,
        .locator_bar => 341,
        .party_changed => 342,
        .server_bound_data_driven_screen_closed => 343,
        .sync_world_clocks => 344,
        .client_bound_attribute_layer_sync => 345,
        .server_store_info => 346,
        .server_presence_info => 347,
        .clientbound_update_sound_data => 348,
        .send_party_destination_cookie => 349,
        .party_destination_cookie_response => 350,
        .set_player_furnace_options => 351,
        .record_started => 352,
    };
}
pub const Direction = enum { client, server, both };
pub fn direction(kind: PacketKind) Direction {
    return switch (kind) {
        .login => .both,
        .play_status => .server,
        .server_to_client_handshake => .server,
        .client_to_server_handshake => .both,
        .disconnect => .server,
        .resource_packs_info => .server,
        .resource_pack_stack => .server,
        .resource_pack_client_response => .both,
        .text => .both,
        .set_time => .server,
        .start_game => .server,
        .add_player => .server,
        .add_actor => .server,
        .remove_actor => .server,
        .add_item_actor => .server,
        .server_player_post_move_position => .server,
        .take_item_actor => .server,
        .move_actor_absolute => .server,
        .move_player => .both,
        .update_block => .both,
        .add_painting => .server,
        .level_event => .server,
        .block_event => .server,
        .actor_event => .both,
        .mob_effect => .server,
        .update_attributes => .server,
        .inventory_transaction => .both,
        .mob_equipment => .both,
        .mob_armour_equipment => .server,
        .interact => .both,
        .block_pick_request => .both,
        .actor_pick_request => .both,
        .player_action => .both,
        .hurt_armour => .server,
        .set_actor_data => .server,
        .set_actor_motion => .server,
        .set_actor_link => .both,
        .set_health => .server,
        .set_spawn_position => .server,
        .animate => .both,
        .respawn => .both,
        .container_open => .both,
        .container_close => .both,
        .player_hot_bar => .server,
        .inventory_content => .server,
        .inventory_slot => .server,
        .container_set_data => .server,
        .crafting_data => .server,
        .g_u_i_data_pick_item => .server,
        .adventure_settings => .both,
        .block_actor_data => .both,
        .level_chunk => .server,
        .set_commands_enabled => .server,
        .set_difficulty => .server,
        .change_dimension => .server,
        .set_player_game_type => .both,
        .player_list => .server,
        .simple_event => .both,
        .event => .server,
        .spawn_experience_orb => .server,
        .client_bound_map_item_data => .server,
        .map_info_request => .both,
        .request_chunk_radius => .client,
        .chunk_radius_updated => .server,
        .game_rules_changed => .server,
        .camera => .server,
        .boss_event => .both,
        .show_credits => .both,
        .available_commands => .server,
        .command_request => .both,
        .command_block_update => .both,
        .command_output => .server,
        .update_trade => .server,
        .update_equip => .server,
        .resource_pack_data_info => .server,
        .resource_pack_chunk_data => .server,
        .resource_pack_chunk_request => .both,
        .transfer => .server,
        .play_sound => .server,
        .stop_sound => .server,
        .set_title => .server,
        .add_behaviour_tree => .server,
        .structure_block_update => .both,
        .show_store_offer => .server,
        .purchase_receipt => .both,
        .player_skin => .both,
        .sub_client_login => .both,
        .automation_client_connect => .both,
        .set_last_hurt_by => .server,
        .book_edit => .both,
        .n_p_c_request => .both,
        .photo_transfer => .server,
        .modal_form_request => .server,
        .modal_form_response => .both,
        .server_settings_request => .both,
        .server_settings_response => .server,
        .show_profile => .server,
        .set_default_game_type => .both,
        .remove_objective => .server,
        .set_display_objective => .server,
        .set_score => .server,
        .lab_table => .both,
        .update_block_synced => .server,
        .move_actor_delta => .server,
        .set_scoreboard_identity => .server,
        .set_local_player_as_initialised => .both,
        .update_soft_enum => .server,
        .network_stack_latency => .both,
        .script_custom_event => .both,
        .spawn_particle_effect => .server,
        .available_actor_identifiers => .server,
        .network_chunk_publisher_update => .server,
        .biome_definition_list => .server,
        .level_sound_event => .both,
        .level_event_generic => .server,
        .lectern_update => .both,
        .client_cache_status => .both,
        .on_screen_texture_animation => .server,
        .map_create_locked_copy => .both,
        .structure_template_data_request => .both,
        .structure_template_data_response => .both,
        .client_cache_blob_status => .both,
        .client_cache_miss_response => .server,
        .education_settings => .server,
        .emote => .both,
        .multi_player_settings => .both,
        .settings_command => .both,
        .anvil_damage => .both,
        .completed_using_item => .server,
        .network_settings => .server,
        .player_auth_input => .both,
        .creative_content => .server,
        .player_enchant_options => .server,
        .item_stack_request => .both,
        .item_stack_response => .server,
        .player_armour_damage => .server,
        .code_builder => .server,
        .update_player_game_type => .both,
        .emote_list => .both,
        .position_tracking_d_b_server_broadcast => .server,
        .position_tracking_d_b_client_request => .both,
        .debug_info => .both,
        .packet_violation_warning => .both,
        .motion_prediction_hints => .server,
        .animate_entity => .server,
        .camera_shake => .server,
        .player_fog => .server,
        .correct_player_move_prediction => .server,
        .item_registry => .server,
        .filter_text => .both,
        .client_bound_debug_renderer => .server,
        .sync_actor_property => .server,
        .add_volume_entity => .server,
        .remove_volume_entity => .server,
        .simulation_type => .server,
        .n_p_c_dialogue => .server,
        .education_resource_u_r_i => .server,
        .create_photo => .both,
        .update_sub_chunk_blocks => .server,
        .photo_info_request => .both,
        .sub_chunk => .server,
        .sub_chunk_request => .both,
        .client_start_item_cooldown => .server,
        .script_message => .both,
        .code_builder_source => .both,
        .ticking_areas_load_status => .server,
        .dimension_data => .server,
        .agent_action => .server,
        .change_mob_property => .server,
        .lesson_progress => .server,
        .request_ability => .both,
        .request_permissions => .both,
        .toast_request => .server,
        .update_abilities => .server,
        .update_adventure_settings => .server,
        .death_info => .server,
        .editor_network => .both,
        .feature_registry => .server,
        .server_stats => .server,
        .request_network_settings => .both,
        .game_test_request => .server,
        .game_test_results => .both,
        .update_client_input_locks => .server,
        .client_cheat_ability => .server,
        .camera_presets => .server,
        .unlocked_recipes => .server,
        .camera_instruction => .server,
        .trim_data => .server,
        .open_sign => .both,
        .agent_animation => .server,
        .refresh_entitlements => .server,
        .player_toggle_crafter_slot_request => .both,
        .set_player_inventory_options => .both,
        .set_hud => .server,
        .award_achievement => .server,
        .client_bound_close_form => .server,
        .server_bound_loading_screen => .both,
        .jigsaw_structure_data => .server,
        .current_structure_feature => .server,
        .server_bound_diagnostics => .both,
        .camera_aim_assist => .server,
        .container_registry_cleanup => .server,
        .movement_effect => .server,
        .camera_aim_assist_presets => .server,
        .client_camera_aim_assist => .both,
        .client_movement_prediction_sync => .both,
        .update_client_options => .both,
        .player_video_capture => .server,
        .player_update_entity_overrides => .server,
        .player_location => .server,
        .client_bound_control_scheme_set => .server,
        .primitive_shapes => .server,
        .server_bound_pack_setting_change => .both,
        .client_bound_data_store => .server,
        .graphics_override_parameter => .server,
        .server_bound_data_store => .client,
        .client_bound_data_driven_u_i_show_screen => .server,
        .client_bound_data_driven_u_i_close_screen => .server,
        .client_bound_data_driven_u_i_reload => .server,
        .client_bound_texture_shift => .server,
        .voxel_shapes => .server,
        .camera_spline => .server,
        .camera_aim_assist_actor_priority => .server,
        .resource_packs_ready_for_validation => .client,
        .locator_bar => .server,
        .party_changed => .client,
        .server_bound_data_driven_screen_closed => .client,
        .sync_world_clocks => .server,
        .client_bound_attribute_layer_sync => .server,
        .server_store_info => .server,
        .server_presence_info => .server,
        .clientbound_update_sound_data => .server,
        .send_party_destination_cookie => .server,
        .party_destination_cookie_response => .client,
        .set_player_furnace_options => .server,
        .record_started => .server,
    };
}
