//! AgentAnimationPacket (ID 304), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    agent_animation: AgentAnimationType,
    runtime_id: u64,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.agent_animation = try AgentAnimationType.decode(r);
        value.runtime_id = try r.readVarU64();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.agent_animation.encode(w);
        try w.writeVarU64(self.runtime_id);
    }
};

/// Wire type `AgentAnimation`.
pub const AgentAnimationType = enum(u8) {
    armswing = 0,
    shrug = 1,
    _,

    pub fn decode(r: *Reader) DecodeError!AgentAnimationType {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: AgentAnimationType, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};
