//! AvailableCommandsPacket (ID 76), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    enum_values: codec.List([]const u8, codec.Prim(.string)),
    chained_subcommand_values: codec.List([]const u8, codec.Prim(.string)),
    post_fixes: codec.List([]const u8, codec.Prim(.string)),
    enum_data: codec.List(CommandEnum, CommandEnum),
    chained_subcommand_data: codec.List(ChainedSubcommand, ChainedSubcommand),
    commands: codec.List(Command, Command),
    soft_enums: codec.List(DynamicEnum, DynamicEnum),
    constraints: codec.List(CommandEnumConstraint, CommandEnumConstraint),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.enum_values = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        value.chained_subcommand_values = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        value.post_fixes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        value.enum_data = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CommandEnum, CommandEnum).decode(r, count);
        };
        value.chained_subcommand_data = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 16) return error.InvalidValue;
            break :blk try codec.List(ChainedSubcommand, ChainedSubcommand).decode(r, count);
        };
        value.commands = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(Command, Command).decode(r, count);
        };
        value.soft_enums = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(DynamicEnum, DynamicEnum).decode(r, count);
        };
        value.constraints = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CommandEnumConstraint, CommandEnumConstraint).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.enum_values.len);
        try self.enum_values.encode(w);
        try w.writeCount(.var_u32, self.chained_subcommand_values.len);
        try self.chained_subcommand_values.encode(w);
        try w.writeCount(.var_u32, self.post_fixes.len);
        try self.post_fixes.encode(w);
        try w.writeCount(.var_u32, self.enum_data.len);
        try self.enum_data.encode(w);
        if (self.chained_subcommand_data.len > 16) return error.InvalidValue;
        try w.writeCount(.var_u32, self.chained_subcommand_data.len);
        try self.chained_subcommand_data.encode(w);
        try w.writeCount(.var_u32, self.commands.len);
        try self.commands.encode(w);
        try w.writeCount(.var_u32, self.soft_enums.len);
        try self.soft_enums.encode(w);
        try w.writeCount(.var_u32, self.constraints.len);
        try self.constraints.encode(w);
    }
};

/// Wire type `AvailableCommandsPacketPayload::ChainedSubcommandData`.
pub const ChainedSubcommand = struct {
    name: []const u8,
    sub_command_values: codec.List(ChainedSubcommandValue, ChainedSubcommandValue),

    pub fn decode(r: *Reader) DecodeError!ChainedSubcommand {
        var value: ChainedSubcommand = undefined;
        value.name = try r.readString();
        if (value.name.len > 512) return error.InvalidValue;
        value.sub_command_values = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 32) return error.InvalidValue;
            break :blk try codec.List(ChainedSubcommandValue, ChainedSubcommandValue).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: ChainedSubcommand, w: anytype) EncodeError!void {
        if (self.name.len > 512) return error.InvalidValue;
        try w.writeString(self.name);
        if (self.sub_command_values.len > 32) return error.InvalidValue;
        try w.writeCount(.var_u32, self.sub_command_values.len);
        try self.sub_command_values.encode(w);
    }
};

/// Wire type `AvailableCommandsPacketPayload::ChainedSubcommandRelationship`.
pub const ChainedSubcommandValue = struct {
    sub_command_first_value: u32,
    sub_command_second_value: u32,

    pub fn decode(r: *Reader) DecodeError!ChainedSubcommandValue {
        var value: ChainedSubcommandValue = undefined;
        value.sub_command_first_value = try r.readVarU32();
        value.sub_command_second_value = try r.readVarU32();
        return value;
    }

    pub fn encode(self: ChainedSubcommandValue, w: anytype) EncodeError!void {
        try w.writeVarU32(self.sub_command_first_value);
        try w.writeVarU32(self.sub_command_second_value);
    }
};

/// Wire type `AvailableCommandsPacketCommandData`.
pub const Command = struct {
    name: []const u8,
    description: []const u8,
    flags: u16,
    permission_level: []const u8,
    alias_enum: i32,
    command_data_chained_subcommand_indexes: codec.List(u32, codec.Prim(.u32le)),
    overloads: codec.List(CommandOverload, CommandOverload),

    pub fn decode(r: *Reader) DecodeError!Command {
        var value: Command = undefined;
        value.name = try r.readString();
        if (value.name.len > 1000) return error.InvalidValue;
        value.description = try r.readString();
        if (value.description.len > 1000) return error.InvalidValue;
        value.flags = try r.readU16();
        value.permission_level = try r.readString();
        value.alias_enum = try r.readI32();
        value.command_data_chained_subcommand_indexes = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 250) return error.InvalidValue;
            break :blk try codec.List(u32, codec.Prim(.u32le)).decode(r, count);
        };
        value.overloads = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 250) return error.InvalidValue;
            break :blk try codec.List(CommandOverload, CommandOverload).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Command, w: anytype) EncodeError!void {
        if (self.name.len > 1000) return error.InvalidValue;
        try w.writeString(self.name);
        if (self.description.len > 1000) return error.InvalidValue;
        try w.writeString(self.description);
        try w.writeU16(self.flags);
        try w.writeString(self.permission_level);
        try w.writeI32(self.alias_enum);
        if (self.command_data_chained_subcommand_indexes.len > 250) return error.InvalidValue;
        try w.writeCount(.var_u32, self.command_data_chained_subcommand_indexes.len);
        try self.command_data_chained_subcommand_indexes.encode(w);
        if (self.overloads.len > 250) return error.InvalidValue;
        try w.writeCount(.var_u32, self.overloads.len);
        try self.overloads.encode(w);
    }
};

/// Wire type `AvailableCommandsPacketPayload::EnumData`.
pub const CommandEnum = struct {
    name: []const u8,
    values: codec.List(u32, codec.Prim(.u32le)),

    pub fn decode(r: *Reader) DecodeError!CommandEnum {
        var value: CommandEnum = undefined;
        value.name = try r.readString();
        value.values = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(u32, codec.Prim(.u32le)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: CommandEnum, w: anytype) EncodeError!void {
        try w.writeString(self.name);
        try w.writeCount(.var_u32, self.values.len);
        try self.values.encode(w);
    }
};

/// Wire type `AvailableCommandsPacketPayload::ConstrainedValueData`.
pub const CommandEnumConstraint = struct {
    enum_value_symbol: u32,
    enum_symbol: u32,
    constraint_indices: []const u8,

    pub fn decode(r: *Reader) DecodeError!CommandEnumConstraint {
        var value: CommandEnumConstraint = undefined;
        value.enum_value_symbol = try r.readU32();
        value.enum_symbol = try r.readU32();
        value.constraint_indices = try r.readByteArray();
        if (value.constraint_indices.len > 250) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: CommandEnumConstraint, w: anytype) EncodeError!void {
        try w.writeU32(self.enum_value_symbol);
        try w.writeU32(self.enum_symbol);
        if (self.constraint_indices.len > 250) return error.InvalidValue;
        try w.writeByteArray(self.constraint_indices);
    }
};

/// Wire type `AvailableCommandsPacketPayload::OverloadData`.
pub const CommandOverload = struct {
    is_chaining: bool,
    parameter_data: codec.List(CommandParameter, CommandParameter),

    pub fn decode(r: *Reader) DecodeError!CommandOverload {
        var value: CommandOverload = undefined;
        value.is_chaining = try r.readBool();
        value.parameter_data = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CommandParameter, CommandParameter).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: CommandOverload, w: anytype) EncodeError!void {
        try w.writeBool(self.is_chaining);
        try w.writeCount(.var_u32, self.parameter_data.len);
        try self.parameter_data.encode(w);
    }
};

/// Wire type `AvailableCommandsPacketPayload::ParamData`.
pub const CommandParameter = struct {
    name: []const u8,
    parse_symbol: u32,
    is_optional: bool,
    options: u8,

    pub fn decode(r: *Reader) DecodeError!CommandParameter {
        var value: CommandParameter = undefined;
        value.name = try r.readString();
        value.parse_symbol = try r.readU32();
        value.is_optional = try r.readBool();
        value.options = try r.readU8();
        return value;
    }

    pub fn encode(self: CommandParameter, w: anytype) EncodeError!void {
        try w.writeString(self.name);
        try w.writeU32(self.parse_symbol);
        try w.writeBool(self.is_optional);
        try w.writeU8(self.options);
    }
};

/// Wire type `AvailableCommandsPacketPayload::SoftEnumData`.
pub const DynamicEnum = struct {
    enum_name: []const u8,
    enum_options: codec.List([]const u8, codec.Prim(.string)),

    pub fn decode(r: *Reader) DecodeError!DynamicEnum {
        var value: DynamicEnum = undefined;
        value.enum_name = try r.readString();
        if (value.enum_name.len > 512) return error.InvalidValue;
        value.enum_options = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: DynamicEnum, w: anytype) EncodeError!void {
        if (self.enum_name.len > 512) return error.InvalidValue;
        try w.writeString(self.enum_name);
        try w.writeCount(.var_u32, self.enum_options.len);
        try self.enum_options.encode(w);
    }
};
