//! AwardAchievementPacket (ID 309), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    achievement_id: i32,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.achievement_id = try r.readI32();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeI32(self.achievement_id);
    }
};
