//! BookEditPacket (ID 97), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    book_slot: i32,
    operation: BookEditOperation,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.book_slot = try r.readVarI32();
        value.operation = try BookEditOperation.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI32(self.book_slot);
        try self.operation.encode(w);
    }
};

/// Wire type `BookEditAction::AddPage`.
pub const BookEditActionAddPage = struct {
    page_index: i32,
    page_text: []const u8,
    photo_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!BookEditActionAddPage {
        var value: BookEditActionAddPage = undefined;
        value.page_index = try r.readVarI32();
        value.page_text = try r.readString();
        if (value.page_text.len > 768) return error.InvalidValue;
        value.photo_name = try r.readString();
        if (value.photo_name.len > 768) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: BookEditActionAddPage, w: anytype) EncodeError!void {
        try w.writeVarI32(self.page_index);
        if (self.page_text.len > 768) return error.InvalidValue;
        try w.writeString(self.page_text);
        if (self.photo_name.len > 768) return error.InvalidValue;
        try w.writeString(self.photo_name);
    }
};

/// Wire type `BookEditAction::Finalize`.
pub const BookEditActionFinalize = struct {
    title: []const u8,
    author: []const u8,
    xuid: []const u8,

    pub fn decode(r: *Reader) DecodeError!BookEditActionFinalize {
        var value: BookEditActionFinalize = undefined;
        value.title = try r.readString();
        if (value.title.len > 768) return error.InvalidValue;
        value.author = try r.readString();
        if (value.author.len > 768) return error.InvalidValue;
        value.xuid = try r.readString();
        if (value.xuid.len > 768) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: BookEditActionFinalize, w: anytype) EncodeError!void {
        if (self.title.len > 768) return error.InvalidValue;
        try w.writeString(self.title);
        if (self.author.len > 768) return error.InvalidValue;
        try w.writeString(self.author);
        if (self.xuid.len > 768) return error.InvalidValue;
        try w.writeString(self.xuid);
    }
};

/// Wire type `BookEditAction::ReplacePage`.
pub const BookEditActionReplacePage = struct {
    page_index: i32,
    page_text: []const u8,
    photo_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!BookEditActionReplacePage {
        var value: BookEditActionReplacePage = undefined;
        value.page_index = try r.readVarI32();
        value.page_text = try r.readString();
        if (value.page_text.len > 768) return error.InvalidValue;
        value.photo_name = try r.readString();
        if (value.photo_name.len > 768) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: BookEditActionReplacePage, w: anytype) EncodeError!void {
        try w.writeVarI32(self.page_index);
        if (self.page_text.len > 768) return error.InvalidValue;
        try w.writeString(self.page_text);
        if (self.photo_name.len > 768) return error.InvalidValue;
        try w.writeString(self.photo_name);
    }
};

/// Wire type `BookEditAction::SwapPages`.
pub const BookEditActionSwapPages = struct {
    page_index: i32,
    swap_with_index: i32,

    pub fn decode(r: *Reader) DecodeError!BookEditActionSwapPages {
        var value: BookEditActionSwapPages = undefined;
        value.page_index = try r.readVarI32();
        value.swap_with_index = try r.readVarI32();
        return value;
    }

    pub fn encode(self: BookEditActionSwapPages, w: anytype) EncodeError!void {
        try w.writeVarI32(self.page_index);
        try w.writeVarI32(self.swap_with_index);
    }
};

pub const BookEditOperation = union(enum(u32)) {
    replace_page: BookEditActionReplacePage,
    add_page: BookEditActionAddPage,
    delete_page: i32,
    swap_pages: BookEditActionSwapPages,
    finalize: BookEditActionFinalize,

    pub fn decode(r: *Reader) DecodeError!BookEditOperation {
        switch (try r.readVarU32()) {
            0 => return .{ .replace_page = try BookEditActionReplacePage.decode(r) },
            1 => return .{ .add_page = try BookEditActionAddPage.decode(r) },
            2 => return .{ .delete_page = try r.readVarI32() },
            3 => return .{ .swap_pages = try BookEditActionSwapPages.decode(r) },
            4 => return .{ .finalize = try BookEditActionFinalize.decode(r) },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: BookEditOperation, w: anytype) EncodeError!void {
        try w.writeVarU32(@intFromEnum(self));
        switch (self) {
            .replace_page => |value| {
                try value.encode(w);
            },
            .add_page => |value| {
                try value.encode(w);
            },
            .delete_page => |value| {
                try w.writeVarI32(value);
            },
            .swap_pages => |value| {
                try value.encode(w);
            },
            .finalize => |value| {
                try value.encode(w);
            },
        }
    }
};
