//! CameraAimAssistActorPriorityPacket (ID 339), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    camera_aim_assist_actor_priority_list: codec.List(CameraAimAssistActorPriorityPriorityData, CameraAimAssistActorPriorityPriorityData),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.camera_aim_assist_actor_priority_list = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraAimAssistActorPriorityPriorityData, CameraAimAssistActorPriorityPriorityData).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.camera_aim_assist_actor_priority_list.len);
        try self.camera_aim_assist_actor_priority_list.encode(w);
    }
};

/// Wire type `CameraAimAssistActorPriority::PriorityData`.
pub const CameraAimAssistActorPriorityPriorityData = struct {
    preset_index: i32,
    category_index: i32,
    actor_index: i32,
    priority_value: i32,

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistActorPriorityPriorityData {
        var value: CameraAimAssistActorPriorityPriorityData = undefined;
        value.preset_index = try r.readI32();
        value.category_index = try r.readI32();
        value.actor_index = try r.readI32();
        value.priority_value = try r.readI32();
        return value;
    }

    pub fn encode(self: CameraAimAssistActorPriorityPriorityData, w: anytype) EncodeError!void {
        try w.writeI32(self.preset_index);
        try w.writeI32(self.category_index);
        try w.writeI32(self.actor_index);
        try w.writeI32(self.priority_value);
    }
};
