//! ClientboundDataStorePacket (ID 330), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    updates: codec.List(ClientBoundDataStoreUpdatesItem, ClientBoundDataStoreUpdatesItem),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.updates = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 500) return error.InvalidValue;
            break :blk try codec.List(ClientBoundDataStoreUpdatesItem, ClientBoundDataStoreUpdatesItem).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        if (self.updates.len > 500) return error.InvalidValue;
        try w.writeCount(.var_u32, self.updates.len);
        try self.updates.encode(w);
    }
};

pub const ClientBoundDataStoreUpdatesItem = union(enum(u32)) {
    update: types.DduiDataStoreUpdate,
    change: DataStoreChange,
    removal: []const u8,

    pub fn decode(r: *Reader) DecodeError!ClientBoundDataStoreUpdatesItem {
        switch (try r.readVarU32()) {
            0 => return .{ .update = try types.DduiDataStoreUpdate.decode(r) },
            1 => return .{ .change = try DataStoreChange.decode(r) },
            2 => {
                var value: []const u8 = undefined;
                value = try r.readString();
                if (value.len < 1) return error.InvalidValue;
                if (value.len > 1000) return error.InvalidValue;
                return .{ .removal = value };
            },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: ClientBoundDataStoreUpdatesItem, w: anytype) EncodeError!void {
        try w.writeVarU32(@intFromEnum(self));
        switch (self) {
            .update => |value| {
                try value.encode(w);
            },
            .change => |value| {
                try value.encode(w);
            },
            .removal => |value| {
                if (value.len < 1) return error.InvalidValue;
                if (value.len > 1000) return error.InvalidValue;
                try w.writeString(value);
            },
        }
    }
};

/// Wire type `Bedrock::DDUI::DataStoreChange`.
pub const DataStoreChange = struct {
    data_store_name: []const u8,
    property: []const u8,
    update_count: u32,
    the_new_property_value: DynamicValue,

    pub fn decode(r: *Reader) DecodeError!DataStoreChange {
        var value: DataStoreChange = undefined;
        value.data_store_name = try r.readString();
        if (value.data_store_name.len < 1) return error.InvalidValue;
        if (value.data_store_name.len > 1000) return error.InvalidValue;
        value.property = try r.readString();
        if (value.property.len < 1) return error.InvalidValue;
        if (value.property.len > 1000) return error.InvalidValue;
        value.update_count = try r.readU32();
        if (value.update_count > 4294967294) return error.InvalidValue;
        value.the_new_property_value = try DynamicValue.decode(r);
        return value;
    }

    pub fn encode(self: DataStoreChange, w: anytype) EncodeError!void {
        if (self.data_store_name.len < 1) return error.InvalidValue;
        if (self.data_store_name.len > 1000) return error.InvalidValue;
        try w.writeString(self.data_store_name);
        if (self.property.len < 1) return error.InvalidValue;
        if (self.property.len > 1000) return error.InvalidValue;
        try w.writeString(self.property);
        if (self.update_count > 4294967294) return error.InvalidValue;
        try w.writeU32(self.update_count);
        try self.the_new_property_value.encode(w);
    }
};

/// Wire type `cereal::DynamicValue`.
pub const DynamicValue = union(enum(i32)) {
    none,
    bool: bool,
    int64: i64,
    double: f64,
    string: []const u8,
    list: codec.List(DynamicValue, DynamicValue),
    map: codec.List(DynamicValueMapEntry, DynamicValueMapEntry),

    pub fn decode(r: *Reader) DecodeError!DynamicValue {
        try r.enter();
        defer r.leave();
        switch (try r.readI32()) {
            0 => return .none,
            1 => return .{ .bool = try r.readBool() },
            2 => return .{ .int64 = try r.readI64() },
            3 => return .{ .double = try r.readF64() },
            4 => return .{ .string = try r.readString() },
            5 => {
                var value: codec.List(DynamicValue, DynamicValue) = undefined;
                value = blk: {
                    const count = try r.readCount(.var_u32);
                    break :blk try codec.List(DynamicValue, DynamicValue).decode(r, count);
                };
                return .{ .list = value };
            },
            6 => {
                var value: codec.List(DynamicValueMapEntry, DynamicValueMapEntry) = undefined;
                value = blk: {
                    const count = try r.readCount(.var_u32);
                    break :blk try codec.List(DynamicValueMapEntry, DynamicValueMapEntry).decode(r, count);
                };
                return .{ .map = value };
            },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: DynamicValue, w: anytype) EncodeError!void {
        try w.enter();
        defer w.leave();
        try w.writeI32(@intFromEnum(self));
        switch (self) {
            .none => {},
            .bool => |value| {
                try w.writeBool(value);
            },
            .int64 => |value| {
                try w.writeI64(value);
            },
            .double => |value| {
                try w.writeF64(value);
            },
            .string => |value| {
                try w.writeString(value);
            },
            .list => |value| {
                try w.writeCount(.var_u32, value.len);
                try value.encode(w);
            },
            .map => |value| {
                try w.writeCount(.var_u32, value.len);
                try value.encode(w);
            },
        }
    }
};

pub const DynamicValueMapEntry = struct {
    key: []const u8,
    value: DynamicValue,

    pub fn decode(r: *Reader) DecodeError!DynamicValueMapEntry {
        var value: DynamicValueMapEntry = undefined;
        value.key = try r.readString();
        value.value = try DynamicValue.decode(r);
        return value;
    }

    pub fn encode(self: DynamicValueMapEntry, w: anytype) EncodeError!void {
        try w.writeString(self.key);
        try self.value.encode(w);
    }
};
