//! ClientboundTextureShiftPacket (ID 336), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    action_id: ClientboundTextureShiftAction,
    collection_name: []const u8,
    from_step: []const u8,
    to_step: []const u8,
    all_steps: codec.List([]const u8, codec.Prim(.string)),
    current_length_in_ticks: u64,
    total_length_in_ticks: u64,
    enabled: bool,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.action_id = try ClientboundTextureShiftAction.decode(r);
        value.collection_name = try r.readString();
        value.from_step = try r.readString();
        value.to_step = try r.readString();
        value.all_steps = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        value.current_length_in_ticks = try r.readVarU64();
        value.total_length_in_ticks = try r.readVarU64();
        value.enabled = try r.readBool();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.action_id.encode(w);
        try w.writeString(self.collection_name);
        try w.writeString(self.from_step);
        try w.writeString(self.to_step);
        try w.writeCount(.var_u32, self.all_steps.len);
        try self.all_steps.encode(w);
        try w.writeVarU64(self.current_length_in_ticks);
        try w.writeVarU64(self.total_length_in_ticks);
        try w.writeBool(self.enabled);
    }
};

/// Wire type `ClientboundTextureShiftPacketPayload::Action`.
pub const ClientboundTextureShiftAction = enum(u8) {
    invalid = 0,
    initialize = 1,
    start = 2,
    setenabled = 3,
    sync = 4,
    _,

    pub fn decode(r: *Reader) DecodeError!ClientboundTextureShiftAction {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: ClientboundTextureShiftAction, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};
