//! CommandRequestPacket (ID 77), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    command: []const u8,
    origin: types.CommandOrigin,
    is_internal: bool,
    version: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.command = try r.readString();
        if (value.command.len > 1000) return error.InvalidValue;
        value.origin = try types.CommandOrigin.decode(r);
        value.is_internal = try r.readBool();
        value.version = try r.readString();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        if (self.command.len > 1000) return error.InvalidValue;
        try w.writeString(self.command);
        try self.origin.encode(w);
        try w.writeBool(self.is_internal);
        try w.writeString(self.version);
    }
};
