//! CommandOutputPacket (ID 79), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    origin_data: types.CommandOrigin,
    output: CommandOutputData,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.origin_data = try types.CommandOrigin.decode(r);
        value.output = try CommandOutputData.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.origin_data.encode(w);
        try self.output.encode(w);
    }
};

/// Wire type `CommandOutput`.
pub const CommandOutputData = struct {
    output_type: []const u8,
    success_count: u32,
    output_messages: codec.List(CommandOutputMessage, CommandOutputMessage),
    data_set: ?[]const u8,

    pub fn decode(r: *Reader) DecodeError!CommandOutputData {
        var value: CommandOutputData = undefined;
        value.output_type = try r.readString();
        value.success_count = try r.readU32();
        value.output_messages = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CommandOutputMessage, CommandOutputMessage).decode(r, count);
        };
        value.data_set = if (try r.readBool()) try r.readString() else null;
        return value;
    }

    pub fn encode(self: CommandOutputData, w: anytype) EncodeError!void {
        try w.writeString(self.output_type);
        try w.writeU32(self.success_count);
        try w.writeCount(.var_u32, self.output_messages.len);
        try self.output_messages.encode(w);
        try w.writeBool(self.data_set != null);
        if (self.data_set) |present| {
            try w.writeString(present);
        }
    }
};

/// Wire type `CommandOutputMessage`.
pub const CommandOutputMessage = struct {
    message_id: []const u8,
    successful: bool,
    parameters: codec.List([]const u8, codec.Prim(.string)),

    pub fn decode(r: *Reader) DecodeError!CommandOutputMessage {
        var value: CommandOutputMessage = undefined;
        value.message_id = try r.readString();
        value.successful = try r.readBool();
        value.parameters = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: CommandOutputMessage, w: anytype) EncodeError!void {
        try w.writeString(self.message_id);
        try w.writeBool(self.successful);
        try w.writeCount(.var_u32, self.parameters.len);
        try self.parameters.encode(w);
    }
};
