//! ContainerClosePacket (ID 47), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    container_id: u8,
    container_type: u8,
    server_initiated_close: bool,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.container_id = try r.readU8();
        value.container_type = try r.readU8();
        value.server_initiated_close = try r.readBool();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeU8(self.container_id);
        try w.writeU8(self.container_type);
        try w.writeBool(self.server_initiated_close);
    }
};
