//! ContainerSetDataPacket (ID 51), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    container_id: u8,
    id: i32,
    value: i32,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.container_id = try r.readU8();
        value.id = try r.readVarI32();
        value.value = try r.readVarI32();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeU8(self.container_id);
        try w.writeVarI32(self.id);
        try w.writeVarI32(self.value);
    }
};
