//! CraftingDataPacket (ID 52), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    shaped_recipes: codec.List(ShapedRecipePayload, ShapedRecipePayload),
    shapeless_recipes: codec.List(ShapelessRecipePayload, ShapelessRecipePayload),
    multi_recipes: codec.List(MultiRecipePayload, MultiRecipePayload),
    user_data_shapeless_recipes: codec.List(ShapelessRecipePayload, ShapelessRecipePayload),
    shapeless_chemistry_recipes: codec.List(ShapelessRecipePayload, ShapelessRecipePayload),
    shaped_chemistry_recipes: codec.List(ShapedRecipePayload, ShapedRecipePayload),
    smithing_transform_recipes: codec.List(SmithingTransformRecipePayload, SmithingTransformRecipePayload),
    smithing_trim_recipes: codec.List(SmithingTrimRecipePayload, SmithingTrimRecipePayload),
    potion_mixes: codec.List(PotionMixDataEntry, PotionMixDataEntry),
    container_mixes: codec.List(ContainerMixDataEntry, ContainerMixDataEntry),
    material_reducers: codec.List(MaterialReducerDataEntry, MaterialReducerDataEntry),
    clear_recipes: bool,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.shaped_recipes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(ShapedRecipePayload, ShapedRecipePayload).decode(r, count);
        };
        value.shapeless_recipes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(ShapelessRecipePayload, ShapelessRecipePayload).decode(r, count);
        };
        value.multi_recipes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(MultiRecipePayload, MultiRecipePayload).decode(r, count);
        };
        value.user_data_shapeless_recipes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(ShapelessRecipePayload, ShapelessRecipePayload).decode(r, count);
        };
        value.shapeless_chemistry_recipes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(ShapelessRecipePayload, ShapelessRecipePayload).decode(r, count);
        };
        value.shaped_chemistry_recipes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(ShapedRecipePayload, ShapedRecipePayload).decode(r, count);
        };
        value.smithing_transform_recipes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(SmithingTransformRecipePayload, SmithingTransformRecipePayload).decode(r, count);
        };
        value.smithing_trim_recipes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(SmithingTrimRecipePayload, SmithingTrimRecipePayload).decode(r, count);
        };
        value.potion_mixes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(PotionMixDataEntry, PotionMixDataEntry).decode(r, count);
        };
        value.container_mixes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(ContainerMixDataEntry, ContainerMixDataEntry).decode(r, count);
        };
        value.material_reducers = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(MaterialReducerDataEntry, MaterialReducerDataEntry).decode(r, count);
        };
        value.clear_recipes = try r.readBool();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.shaped_recipes.len);
        try self.shaped_recipes.encode(w);
        try w.writeCount(.var_u32, self.shapeless_recipes.len);
        try self.shapeless_recipes.encode(w);
        try w.writeCount(.var_u32, self.multi_recipes.len);
        try self.multi_recipes.encode(w);
        try w.writeCount(.var_u32, self.user_data_shapeless_recipes.len);
        try self.user_data_shapeless_recipes.encode(w);
        try w.writeCount(.var_u32, self.shapeless_chemistry_recipes.len);
        try self.shapeless_chemistry_recipes.encode(w);
        try w.writeCount(.var_u32, self.shaped_chemistry_recipes.len);
        try self.shaped_chemistry_recipes.encode(w);
        try w.writeCount(.var_u32, self.smithing_transform_recipes.len);
        try self.smithing_transform_recipes.encode(w);
        try w.writeCount(.var_u32, self.smithing_trim_recipes.len);
        try self.smithing_trim_recipes.encode(w);
        try w.writeCount(.var_u32, self.potion_mixes.len);
        try self.potion_mixes.encode(w);
        try w.writeCount(.var_u32, self.container_mixes.len);
        try self.container_mixes.encode(w);
        try w.writeCount(.var_u32, self.material_reducers.len);
        try self.material_reducers.encode(w);
        try w.writeBool(self.clear_recipes);
    }
};

/// Wire type `ContainerMixDataEntry`.
pub const ContainerMixDataEntry = struct {
    from_item_id: i32,
    reagent_item_id: i32,
    to_item_id: i32,

    pub fn decode(r: *Reader) DecodeError!ContainerMixDataEntry {
        var value: ContainerMixDataEntry = undefined;
        value.from_item_id = try r.readVarI32();
        value.reagent_item_id = try r.readVarI32();
        value.to_item_id = try r.readVarI32();
        return value;
    }

    pub fn encode(self: ContainerMixDataEntry, w: anytype) EncodeError!void {
        try w.writeVarI32(self.from_item_id);
        try w.writeVarI32(self.reagent_item_id);
        try w.writeVarI32(self.to_item_id);
    }
};

/// Wire type `MaterialReducerDataEntry`.
pub const MaterialReducerDataEntry = struct {
    from_item_key: i32,
    item_ids_and_counts: codec.List(MaterialReducerEntryOutput, MaterialReducerEntryOutput),

    pub fn decode(r: *Reader) DecodeError!MaterialReducerDataEntry {
        var value: MaterialReducerDataEntry = undefined;
        value.from_item_key = try r.readVarI32();
        value.item_ids_and_counts = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(MaterialReducerEntryOutput, MaterialReducerEntryOutput).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: MaterialReducerDataEntry, w: anytype) EncodeError!void {
        try w.writeVarI32(self.from_item_key);
        try w.writeCount(.var_u32, self.item_ids_and_counts.len);
        try self.item_ids_and_counts.encode(w);
    }
};

/// Wire type `MaterialReducerEntryOutput`.
pub const MaterialReducerEntryOutput = struct {
    item_id: i32,
    item_count: i32,

    pub fn decode(r: *Reader) DecodeError!MaterialReducerEntryOutput {
        var value: MaterialReducerEntryOutput = undefined;
        value.item_id = try r.readVarI32();
        value.item_count = try r.readVarI32();
        return value;
    }

    pub fn encode(self: MaterialReducerEntryOutput, w: anytype) EncodeError!void {
        try w.writeVarI32(self.item_id);
        try w.writeVarI32(self.item_count);
    }
};

/// Wire type `MultiRecipePayload`.
pub const MultiRecipePayload = struct {
    multi_recipe_uuid: [16]u8,
    net_id: u32,

    pub fn decode(r: *Reader) DecodeError!MultiRecipePayload {
        var value: MultiRecipePayload = undefined;
        value.multi_recipe_uuid = try r.readUuid();
        value.net_id = try r.readVarU32();
        return value;
    }

    pub fn encode(self: MultiRecipePayload, w: anytype) EncodeError!void {
        try w.writeUuid(self.multi_recipe_uuid);
        try w.writeVarU32(self.net_id);
    }
};

/// Wire type `PotionMixDataEntry`.
pub const PotionMixDataEntry = struct {
    from_potion_id: i32,
    from_item_aux: i32,
    reagent_item_id: i32,
    reagent_item_aux: i32,
    to_potion_id: i32,
    to_item_aux: i32,

    pub fn decode(r: *Reader) DecodeError!PotionMixDataEntry {
        var value: PotionMixDataEntry = undefined;
        value.from_potion_id = try r.readVarI32();
        value.from_item_aux = try r.readVarI32();
        value.reagent_item_id = try r.readVarI32();
        value.reagent_item_aux = try r.readVarI32();
        value.to_potion_id = try r.readVarI32();
        value.to_item_aux = try r.readVarI32();
        return value;
    }

    pub fn encode(self: PotionMixDataEntry, w: anytype) EncodeError!void {
        try w.writeVarI32(self.from_potion_id);
        try w.writeVarI32(self.from_item_aux);
        try w.writeVarI32(self.reagent_item_id);
        try w.writeVarI32(self.reagent_item_aux);
        try w.writeVarI32(self.to_potion_id);
        try w.writeVarI32(self.to_item_aux);
    }
};

/// Wire type `cerealizer<RecipeUnlockingRequirement>::SerializedData`.
pub const RecipeUnlockRequirementSerializedData = struct {
    unlocking_context: RecipeUnlockingRequirementUnlockingContext,
    unlocking_ingredients: ?codec.List(custom.RecipeIngredient, custom.RecipeIngredient),

    pub fn decode(r: *Reader) DecodeError!RecipeUnlockRequirementSerializedData {
        var value: RecipeUnlockRequirementSerializedData = undefined;
        value.unlocking_context = try RecipeUnlockingRequirementUnlockingContext.decode(r);
        value.unlocking_ingredients = null;
        if (try r.readBool()) {
            var present: codec.List(custom.RecipeIngredient, custom.RecipeIngredient) = undefined;
            present = blk: {
                const count = try r.readCount(.var_u32);
                if (count > 128) return error.InvalidValue;
                break :blk try codec.List(custom.RecipeIngredient, custom.RecipeIngredient).decode(r, count);
            };
            value.unlocking_ingredients = present;
        }
        return value;
    }

    pub fn encode(self: RecipeUnlockRequirementSerializedData, w: anytype) EncodeError!void {
        try self.unlocking_context.encode(w);
        try w.writeBool(self.unlocking_ingredients != null);
        if (self.unlocking_ingredients) |present| {
            if (present.len > 128) return error.InvalidValue;
            try w.writeCount(.var_u32, present.len);
            try present.encode(w);
        }
    }
};

/// Wire type `RecipeUnlockingRequirement::UnlockingContext`.
pub const RecipeUnlockingRequirementUnlockingContext = enum(i32) {
    none = 0,
    alwaysunlocked = 1,
    playerinwater = 2,
    playerhasmanyitems = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!RecipeUnlockingRequirementUnlockingContext {
        return @enumFromInt(try r.readVarI32());
    }

    pub fn encode(self: RecipeUnlockingRequirementUnlockingContext, w: anytype) EncodeError!void {
        try w.writeVarI32(@intFromEnum(self));
    }
};

/// Wire type `ShapedRecipePayload`.
pub const ShapedRecipePayload = struct {
    recipe_id: []const u8,
    width: i32,
    height: i32,
    ingredients: codec.List(custom.RecipeIngredient, custom.RecipeIngredient),
    results: codec.List(types.NetworkItemInstanceDescriptor, types.NetworkItemInstanceDescriptor),
    uuid: [16]u8,
    tag: []const u8,
    priority: i32,
    assume_symmetry: bool,
    unlocking_requirement: ?RecipeUnlockRequirementSerializedData,
    net_id: u32,

    pub fn decode(r: *Reader) DecodeError!ShapedRecipePayload {
        var value: ShapedRecipePayload = undefined;
        value.recipe_id = try r.readString();
        value.width = try r.readVarI32();
        value.height = try r.readVarI32();
        value.ingredients = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 128) return error.InvalidValue;
            break :blk try codec.List(custom.RecipeIngredient, custom.RecipeIngredient).decode(r, count);
        };
        value.results = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(types.NetworkItemInstanceDescriptor, types.NetworkItemInstanceDescriptor).decode(r, count);
        };
        value.uuid = try r.readUuid();
        value.tag = try r.readString();
        value.priority = try r.readVarI32();
        value.assume_symmetry = try r.readBool();
        value.unlocking_requirement = if (try r.readBool()) try RecipeUnlockRequirementSerializedData.decode(r) else null;
        value.net_id = try r.readVarU32();
        if (!codec.lengthIsProduct(value.ingredients.len, .{ value.width, value.height }, 1)) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: ShapedRecipePayload, w: anytype) EncodeError!void {
        if (!codec.lengthIsProduct(self.ingredients.len, .{ self.width, self.height }, 1)) return error.InvalidValue;
        try w.writeString(self.recipe_id);
        try w.writeVarI32(self.width);
        try w.writeVarI32(self.height);
        if (self.ingredients.len > 128) return error.InvalidValue;
        try w.writeCount(.var_u32, self.ingredients.len);
        try self.ingredients.encode(w);
        try w.writeCount(.var_u32, self.results.len);
        try self.results.encode(w);
        try w.writeUuid(self.uuid);
        try w.writeString(self.tag);
        try w.writeVarI32(self.priority);
        try w.writeBool(self.assume_symmetry);
        try w.writeBool(self.unlocking_requirement != null);
        if (self.unlocking_requirement) |present| {
            try present.encode(w);
        }
        try w.writeVarU32(self.net_id);
    }
};

/// Wire type `ShapelessRecipePayload`.
pub const ShapelessRecipePayload = struct {
    recipe_id: []const u8,
    ingredients: codec.List(custom.RecipeIngredient, custom.RecipeIngredient),
    results: codec.List(types.NetworkItemInstanceDescriptor, types.NetworkItemInstanceDescriptor),
    uuid: [16]u8,
    tag: []const u8,
    priority: i32,
    unlocking_requirement: ?RecipeUnlockRequirementSerializedData,
    net_id: u32,

    pub fn decode(r: *Reader) DecodeError!ShapelessRecipePayload {
        var value: ShapelessRecipePayload = undefined;
        value.recipe_id = try r.readString();
        value.ingredients = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 128) return error.InvalidValue;
            break :blk try codec.List(custom.RecipeIngredient, custom.RecipeIngredient).decode(r, count);
        };
        value.results = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(types.NetworkItemInstanceDescriptor, types.NetworkItemInstanceDescriptor).decode(r, count);
        };
        value.uuid = try r.readUuid();
        value.tag = try r.readString();
        value.priority = try r.readVarI32();
        value.unlocking_requirement = if (try r.readBool()) try RecipeUnlockRequirementSerializedData.decode(r) else null;
        value.net_id = try r.readVarU32();
        return value;
    }

    pub fn encode(self: ShapelessRecipePayload, w: anytype) EncodeError!void {
        try w.writeString(self.recipe_id);
        if (self.ingredients.len > 128) return error.InvalidValue;
        try w.writeCount(.var_u32, self.ingredients.len);
        try self.ingredients.encode(w);
        try w.writeCount(.var_u32, self.results.len);
        try self.results.encode(w);
        try w.writeUuid(self.uuid);
        try w.writeString(self.tag);
        try w.writeVarI32(self.priority);
        try w.writeBool(self.unlocking_requirement != null);
        if (self.unlocking_requirement) |present| {
            try present.encode(w);
        }
        try w.writeVarU32(self.net_id);
    }
};

/// Wire type `SmithingTransformRecipePayload`.
pub const SmithingTransformRecipePayload = struct {
    recipe_id: []const u8,
    template_ingredient: custom.RecipeIngredient,
    base_ingredient: custom.RecipeIngredient,
    addition_ingredient: custom.RecipeIngredient,
    result: types.NetworkItemInstanceDescriptor,
    tag: []const u8,
    net_id: u32,

    pub fn decode(r: *Reader) DecodeError!SmithingTransformRecipePayload {
        var value: SmithingTransformRecipePayload = undefined;
        value.recipe_id = try r.readString();
        value.template_ingredient = try custom.RecipeIngredient.decode(r);
        value.base_ingredient = try custom.RecipeIngredient.decode(r);
        value.addition_ingredient = try custom.RecipeIngredient.decode(r);
        value.result = try types.NetworkItemInstanceDescriptor.decode(r);
        value.tag = try r.readString();
        value.net_id = try r.readVarU32();
        return value;
    }

    pub fn encode(self: SmithingTransformRecipePayload, w: anytype) EncodeError!void {
        try w.writeString(self.recipe_id);
        try self.template_ingredient.encode(w);
        try self.base_ingredient.encode(w);
        try self.addition_ingredient.encode(w);
        try self.result.encode(w);
        try w.writeString(self.tag);
        try w.writeVarU32(self.net_id);
    }
};

/// Wire type `SmithingTrimRecipePayload`.
pub const SmithingTrimRecipePayload = struct {
    recipe_id: []const u8,
    template_ingredient: custom.RecipeIngredient,
    base_ingredient: custom.RecipeIngredient,
    addition_ingredient: custom.RecipeIngredient,
    tag: []const u8,
    net_id: u32,

    pub fn decode(r: *Reader) DecodeError!SmithingTrimRecipePayload {
        var value: SmithingTrimRecipePayload = undefined;
        value.recipe_id = try r.readString();
        value.template_ingredient = try custom.RecipeIngredient.decode(r);
        value.base_ingredient = try custom.RecipeIngredient.decode(r);
        value.addition_ingredient = try custom.RecipeIngredient.decode(r);
        value.tag = try r.readString();
        value.net_id = try r.readVarU32();
        return value;
    }

    pub fn encode(self: SmithingTrimRecipePayload, w: anytype) EncodeError!void {
        try w.writeString(self.recipe_id);
        try self.template_ingredient.encode(w);
        try self.base_ingredient.encode(w);
        try self.addition_ingredient.encode(w);
        try w.writeString(self.tag);
        try w.writeVarU32(self.net_id);
    }
};
