//! CreatePhotoPacket (ID 171), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    raw_id: u64,
    photo_name: []const u8,
    photo_item_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.raw_id = try r.readU64();
        value.photo_name = try r.readString();
        value.photo_item_name = try r.readString();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeU64(self.raw_id);
        try w.writeString(self.photo_name);
        try w.writeString(self.photo_item_name);
    }
};
