//! CreativeContentPacket (ID 145), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    groups: codec.List(CreativeGroup, CreativeGroup),
    entries: codec.List(CreativeItemEntryPayload, CreativeItemEntryPayload),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.groups = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CreativeGroup, CreativeGroup).decode(r, count);
        };
        value.entries = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CreativeItemEntryPayload, CreativeItemEntryPayload).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.groups.len);
        try self.groups.encode(w);
        try w.writeCount(.var_u32, self.entries.len);
        try self.entries.encode(w);
    }
};

/// Wire type `CreativeGroupInfoPayload`.
pub const CreativeGroup = struct {
    creative_category: CreativeItemCategory,
    name: []const u8,
    group_icon_item: types.NetworkItemInstanceDescriptor,

    pub fn decode(r: *Reader) DecodeError!CreativeGroup {
        var value: CreativeGroup = undefined;
        value.creative_category = try CreativeItemCategory.decode(r);
        value.name = try r.readString();
        value.group_icon_item = try types.NetworkItemInstanceDescriptor.decode(r);
        return value;
    }

    pub fn encode(self: CreativeGroup, w: anytype) EncodeError!void {
        try self.creative_category.encode(w);
        try w.writeString(self.name);
        try self.group_icon_item.encode(w);
    }
};

/// Wire type `SharedTypes::CreativeItemCategory`.
pub const CreativeItemCategory = enum(u8) {
    construction = 1,
    nature = 2,
    equipment = 3,
    items = 4,
    itemcommandonly = 5,
    _,

    pub fn decode(r: *Reader) DecodeError!CreativeItemCategory {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: CreativeItemCategory, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};

/// Wire type `CreativeItemEntryPayload`.
pub const CreativeItemEntryPayload = struct {
    creative_net_id: u32,
    item_instance: types.NetworkItemInstanceDescriptor,
    group_index: u32,

    pub fn decode(r: *Reader) DecodeError!CreativeItemEntryPayload {
        var value: CreativeItemEntryPayload = undefined;
        value.creative_net_id = try r.readVarU32();
        value.item_instance = try types.NetworkItemInstanceDescriptor.decode(r);
        value.group_index = try r.readVarU32();
        return value;
    }

    pub fn encode(self: CreativeItemEntryPayload, w: anytype) EncodeError!void {
        try w.writeVarU32(self.creative_net_id);
        try self.item_instance.encode(w);
        try w.writeVarU32(self.group_index);
    }
};
