//! EmoteListPacket (ID 152), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    runtime_id: u64,
    emote_piece_ids: codec.List([16]u8, codec.Prim(.uuid)),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.runtime_id = try r.readVarU64();
        value.emote_piece_ids = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([16]u8, codec.Prim(.uuid)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarU64(self.runtime_id);
        try w.writeCount(.var_u32, self.emote_piece_ids.len);
        try self.emote_piece_ids.encode(w);
    }
};
