//! EmotePacket (ID 138), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    actor_runtime_id: u64,
    emote_id: []const u8,
    emote_length_ticks: u32,
    xuid: []const u8,
    platform_id: []const u8,
    flags: u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.actor_runtime_id = try r.readVarU64();
        value.emote_id = try r.readString();
        value.emote_length_ticks = try r.readVarU32();
        value.xuid = try r.readString();
        value.platform_id = try r.readString();
        value.flags = try r.readU8();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarU64(self.actor_runtime_id);
        try w.writeString(self.emote_id);
        try w.writeVarU32(self.emote_length_ticks);
        try w.writeString(self.xuid);
        try w.writeString(self.platform_id);
        try w.writeU8(self.flags);
    }
};
