//! LegacyTelemetryEventPacket (ID 65), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    target_actor_id: i64,
    event_type: LegacyTelemetryType,
    use_player_id: bool,
    event_data: EventEventData,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.target_actor_id = try r.readVarI64();
        value.event_type = try LegacyTelemetryType.decode(r);
        value.use_player_id = try r.readBool();
        value.event_data = try EventEventData.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI64(self.target_actor_id);
        try self.event_type.encode(w);
        try w.writeBool(self.use_player_id);
        try self.event_data.encode(w);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::BossKilled`.
pub const BossKilledEvent = struct {
    boss_actor_id: i64,
    party_size: i32,
    boss_type: i32,

    pub fn decode(r: *Reader) DecodeError!BossKilledEvent {
        var value: BossKilledEvent = undefined;
        value.boss_actor_id = try r.readVarI64();
        value.party_size = try r.readVarI32();
        value.boss_type = try r.readVarI32();
        return value;
    }

    pub fn encode(self: BossKilledEvent, w: anytype) EncodeError!void {
        try w.writeVarI64(self.boss_actor_id);
        try w.writeVarI32(self.party_size);
        try w.writeVarI32(self.boss_type);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::POICauldronUsed`.
pub const CauldronInteractEvent = struct {
    block_interaction_type: MinecraftEventingPoiBlockInteractionType,
    item_id: i32,

    pub fn decode(r: *Reader) DecodeError!CauldronInteractEvent {
        var value: CauldronInteractEvent = undefined;
        value.block_interaction_type = try MinecraftEventingPoiBlockInteractionType.decode(r);
        value.item_id = try r.readVarI32();
        return value;
    }

    pub fn encode(self: CauldronInteractEvent, w: anytype) EncodeError!void {
        try self.block_interaction_type.encode(w);
        try w.writeVarI32(self.item_id);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::CauldronUsed`.
pub const CauldronUsedEvent = struct {
    contents_color: u32,
    contents_type: i32,
    fill_level: i32,

    pub fn decode(r: *Reader) DecodeError!CauldronUsedEvent {
        var value: CauldronUsedEvent = undefined;
        value.contents_color = try r.readVarU32();
        value.contents_type = try r.readVarI32();
        value.fill_level = try r.readVarI32();
        return value;
    }

    pub fn encode(self: CauldronUsedEvent, w: anytype) EncodeError!void {
        try w.writeVarU32(self.contents_color);
        try w.writeVarI32(self.contents_type);
        try w.writeVarI32(self.fill_level);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::CodeBuilderScoreboard`.
pub const CodeBuilderScoreboardEvent = struct {
    objective_name: []const u8,
    score: i32,

    pub fn decode(r: *Reader) DecodeError!CodeBuilderScoreboardEvent {
        var value: CodeBuilderScoreboardEvent = undefined;
        value.objective_name = try r.readString();
        if (value.objective_name.len > 256) return error.InvalidValue;
        value.score = try r.readVarI32();
        return value;
    }

    pub fn encode(self: CodeBuilderScoreboardEvent, w: anytype) EncodeError!void {
        if (self.objective_name.len > 256) return error.InvalidValue;
        try w.writeString(self.objective_name);
        try w.writeVarI32(self.score);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::ComposterUsed`.
pub const ComposterInteractEvent = struct {
    block_interaction_type: MinecraftEventingPoiBlockInteractionType,
    item_id: i32,

    pub fn decode(r: *Reader) DecodeError!ComposterInteractEvent {
        var value: ComposterInteractEvent = undefined;
        value.block_interaction_type = try MinecraftEventingPoiBlockInteractionType.decode(r);
        value.item_id = try r.readVarI32();
        return value;
    }

    pub fn encode(self: ComposterInteractEvent, w: anytype) EncodeError!void {
        try self.block_interaction_type.encode(w);
        try w.writeVarI32(self.item_id);
    }
};

pub const EventEventData = union(enum(u32)) {
    achievement: MinecraftEventingAchievementIds,
    interaction: LegacyTelemetryEventInteraction,
    portal_created: i32,
    portal_used: PortalUsedEvent,
    mob_killed: MobKilledEvent,
    cauldron_used: CauldronUsedEvent,
    player_died: PlayerDiedEvent,
    boss_killed: BossKilledEvent,
    slash_command: LegacyTelemetryEventSlashCommand,
    mob_born: MobBornEvent,
    poi_cauldron_used: CauldronInteractEvent,
    composter_used: ComposterInteractEvent,
    bell_used: i32,
    actor_definition: []const u8,
    raid_update: RaidUpdateEvent,
    target_block_hit: i32,
    piglin_barter: PiglinBarterEvent,
    player_waxed_or_unwaxed_copper: i32,
    code_builder_runtime_action: []const u8,
    code_builder_scoreboard: CodeBuilderScoreboardEvent,
    item_used: ItemUsedEvent,
    empty: LegacyTelemetryEventEmpty,

    pub fn decode(r: *Reader) DecodeError!EventEventData {
        switch (try r.readVarU32()) {
            0 => return .{ .achievement = try MinecraftEventingAchievementIds.decode(r) },
            1 => return .{ .interaction = try LegacyTelemetryEventInteraction.decode(r) },
            2 => return .{ .portal_created = try r.readVarI32() },
            3 => return .{ .portal_used = try PortalUsedEvent.decode(r) },
            4 => return .{ .mob_killed = try MobKilledEvent.decode(r) },
            5 => return .{ .cauldron_used = try CauldronUsedEvent.decode(r) },
            6 => return .{ .player_died = try PlayerDiedEvent.decode(r) },
            7 => return .{ .boss_killed = try BossKilledEvent.decode(r) },
            8 => return .{ .slash_command = try LegacyTelemetryEventSlashCommand.decode(r) },
            9 => return .{ .mob_born = try MobBornEvent.decode(r) },
            10 => return .{ .poi_cauldron_used = try CauldronInteractEvent.decode(r) },
            11 => return .{ .composter_used = try ComposterInteractEvent.decode(r) },
            12 => return .{ .bell_used = try r.readVarI32() },
            13 => {
                var value: []const u8 = undefined;
                value = try r.readString();
                if (value.len > 256) return error.InvalidValue;
                return .{ .actor_definition = value };
            },
            14 => return .{ .raid_update = try RaidUpdateEvent.decode(r) },
            15 => return .{ .target_block_hit = try r.readVarI32() },
            16 => return .{ .piglin_barter = try PiglinBarterEvent.decode(r) },
            17 => return .{ .player_waxed_or_unwaxed_copper = try r.readVarI32() },
            18 => {
                var value: []const u8 = undefined;
                value = try r.readString();
                if (value.len > 16) return error.InvalidValue;
                return .{ .code_builder_runtime_action = value };
            },
            19 => return .{ .code_builder_scoreboard = try CodeBuilderScoreboardEvent.decode(r) },
            20 => return .{ .item_used = try ItemUsedEvent.decode(r) },
            21 => return .{ .empty = try LegacyTelemetryEventEmpty.decode(r) },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: EventEventData, w: anytype) EncodeError!void {
        try w.writeVarU32(@intFromEnum(self));
        switch (self) {
            .achievement => |value| {
                try value.encode(w);
            },
            .interaction => |value| {
                try value.encode(w);
            },
            .portal_created => |value| {
                try w.writeVarI32(value);
            },
            .portal_used => |value| {
                try value.encode(w);
            },
            .mob_killed => |value| {
                try value.encode(w);
            },
            .cauldron_used => |value| {
                try value.encode(w);
            },
            .player_died => |value| {
                try value.encode(w);
            },
            .boss_killed => |value| {
                try value.encode(w);
            },
            .slash_command => |value| {
                try value.encode(w);
            },
            .mob_born => |value| {
                try value.encode(w);
            },
            .poi_cauldron_used => |value| {
                try value.encode(w);
            },
            .composter_used => |value| {
                try value.encode(w);
            },
            .bell_used => |value| {
                try w.writeVarI32(value);
            },
            .actor_definition => |value| {
                if (value.len > 256) return error.InvalidValue;
                try w.writeString(value);
            },
            .raid_update => |value| {
                try value.encode(w);
            },
            .target_block_hit => |value| {
                try w.writeVarI32(value);
            },
            .piglin_barter => |value| {
                try value.encode(w);
            },
            .player_waxed_or_unwaxed_copper => |value| {
                try w.writeVarI32(value);
            },
            .code_builder_runtime_action => |value| {
                if (value.len > 16) return error.InvalidValue;
                try w.writeString(value);
            },
            .code_builder_scoreboard => |value| {
                try value.encode(w);
            },
            .item_used => |value| {
                try value.encode(w);
            },
            .empty => |value| {
                try value.encode(w);
            },
        }
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::ItemUsed`.
pub const ItemUsedEvent = struct {
    item_id: i16,
    item_aux: i32,
    use_method: i32,
    count: i32,

    pub fn decode(r: *Reader) DecodeError!ItemUsedEvent {
        var value: ItemUsedEvent = undefined;
        value.item_id = try r.readI16();
        value.item_aux = try r.readI32();
        value.use_method = try r.readI32();
        value.count = try r.readI32();
        return value;
    }

    pub fn encode(self: ItemUsedEvent, w: anytype) EncodeError!void {
        try w.writeI16(self.item_id);
        try w.writeI32(self.item_aux);
        try w.writeI32(self.use_method);
        try w.writeI32(self.count);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::Empty`.
pub const LegacyTelemetryEventEmpty = struct {
    pub fn decode(r: *Reader) DecodeError!LegacyTelemetryEventEmpty {
        _ = r;
        return .{};
    }

    pub fn encode(self: LegacyTelemetryEventEmpty, w: anytype) EncodeError!void {
        _ = self;
        _ = w;
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::Interaction`.
pub const LegacyTelemetryEventInteraction = struct {
    interacted_entity_id: i64,
    interaction_type: MinecraftEventingInteractionType,
    interaction_actor_type: i32,
    interaction_actor_variant: i32,
    interaction_actor_color: u8,

    pub fn decode(r: *Reader) DecodeError!LegacyTelemetryEventInteraction {
        var value: LegacyTelemetryEventInteraction = undefined;
        value.interacted_entity_id = try r.readVarI64();
        value.interaction_type = try MinecraftEventingInteractionType.decode(r);
        value.interaction_actor_type = try r.readVarI32();
        value.interaction_actor_variant = try r.readVarI32();
        value.interaction_actor_color = try r.readU8();
        return value;
    }

    pub fn encode(self: LegacyTelemetryEventInteraction, w: anytype) EncodeError!void {
        try w.writeVarI64(self.interacted_entity_id);
        try self.interaction_type.encode(w);
        try w.writeVarI32(self.interaction_actor_type);
        try w.writeVarI32(self.interaction_actor_variant);
        try w.writeU8(self.interaction_actor_color);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::SlashCommand`.
pub const LegacyTelemetryEventSlashCommand = struct {
    success_count: i32,
    error_count: i32,
    command_name: []const u8,
    error_list: []const u8,

    pub fn decode(r: *Reader) DecodeError!LegacyTelemetryEventSlashCommand {
        var value: LegacyTelemetryEventSlashCommand = undefined;
        value.success_count = try r.readVarI32();
        value.error_count = try r.readVarI32();
        value.command_name = try r.readString();
        if (value.command_name.len > 512) return error.InvalidValue;
        value.error_list = try r.readString();
        if (value.error_list.len > 2048) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: LegacyTelemetryEventSlashCommand, w: anytype) EncodeError!void {
        try w.writeVarI32(self.success_count);
        try w.writeVarI32(self.error_count);
        if (self.command_name.len > 512) return error.InvalidValue;
        try w.writeString(self.command_name);
        if (self.error_list.len > 2048) return error.InvalidValue;
        try w.writeString(self.error_list);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::Type`.
pub const LegacyTelemetryType = enum(i32) {
    achievement = 0,
    interaction = 1,
    portalcreated = 2,
    portalused = 3,
    mobkilled = 4,
    cauldronused = 5,
    playerdied = 6,
    bosskilled = 7,
    agentcommand_obsolete = 8,
    agentcreated = 9,
    patternremoved_obsolete = 10,
    slashcommand = 11,
    fishbucketed_obsolete = 12,
    mobborn = 13,
    petdied_obsolete = 14,
    poicauldronused = 15,
    composterused = 16,
    bellused = 17,
    actordefinition = 18,
    raidupdate = 19,
    playermovementanomaly_obsolete = 20,
    playermovementcorrected_obsolete = 21,
    honeyharvested = 22,
    targetblockhit = 23,
    piglinbarter = 24,
    playerwaxedorunwaxedcopper = 25,
    codebuilderruntimeaction = 26,
    codebuilderscoreboard = 27,
    striderriddeninlavainoverworld = 28,
    sneakclosetosculksensor = 29,
    carefulrestoration = 30,
    itemused = 31,
    _,

    pub fn decode(r: *Reader) DecodeError!LegacyTelemetryType {
        return @enumFromInt(try r.readVarI32());
    }

    pub fn encode(self: LegacyTelemetryType, w: anytype) EncodeError!void {
        try w.writeVarI32(@intFromEnum(self));
    }
};

/// Wire type `MinecraftEventing::AchievementIds`.
pub const MinecraftEventingAchievementIds = enum(u8) {
    chestfullofcobblestone = 7,
    diamondforyou = 10,
    ironbelly = 20,
    ironman = 21,
    onarail = 29,
    overkill = 30,
    returntosender = 37,
    sniperduel = 38,
    stayinfrosty = 39,
    takeinventory = 40,
    maproom = 50,
    freightstation = 52,
    smelteverything = 53,
    tasteofyourownmedicine = 54,
    whenpigsfly = 56,
    inception = 58,
    artificialselection = 60,
    freediver = 61,
    spawnthewither = 62,
    beaconator = 63,
    greatview = 64,
    supersonic = 65,
    theendagain = 66,
    treasurehunter = 67,
    shootingstar = 68,
    fashionshow = 69,
    selfpublishedauthor = 71,
    alternativefuel = 72,
    sleepwiththefishes = 73,
    castaway = 74,
    imamarinebiologist = 75,
    sailthe7seas = 76,
    megold = 77,
    ahoy = 78,
    atlantis = 79,
    onepickletwopickleseapicklefour = 80,
    doabarrelroll = 81,
    moskstraumen = 82,
    echolocation = 83,
    wherehaveyoubeen = 84,
    topoftheworld = 85,
    fruitontheloom = 86,
    soundthealarm = 87,
    buylowsellhigh = 88,
    disenchanted = 89,
    timeforstew = 90,
    beeourguest = 91,
    totalbeelocation = 92,
    stickysituation = 93,
    covermeindebris = 94,
    floatyourgoat = 95,
    friend = 96,
    waxonwaxoff = 97,
    striderriddeninlavainoverworld = 98,
    goathornacquired = 99,
    jukeboxusedinmeadows = 100,
    tradedatworldheight = 101,
    survivedfallfromworldheight = 102,
    sneakclosetosculksensor = 103,
    itspreads = 104,
    birthdaysong = 105,
    withourpowerscombined = 106,
    plantingthepast = 107,
    carefulrestoration = 108,
    revaulting = 109,
    crafterscraftingcrafters = 110,
    whoneedsrockets = 111,
    overoverkill = 112,
    hearttransplanter = 113,
    stayhydrated = 114,
    mobkabob = 115,
    adventuringtime = 116,
    uhoh = 117,
    gettingwood = 118,
    benchmaking = 119,
    timetomine = 120,
    hottopic = 121,
    acquirehardware = 122,
    gettinganupgrade = 123,
    monsterhunter = 124,
    diamonds = 125,
    plethoraofcats = 126,
    _,

    pub fn decode(r: *Reader) DecodeError!MinecraftEventingAchievementIds {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: MinecraftEventingAchievementIds, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};

/// Wire type `MinecraftEventing::InteractionType`.
pub const MinecraftEventingInteractionType = enum(u8) {
    breeding = 1,
    taming = 2,
    curing = 3,
    crafted = 4,
    shearing = 5,
    milking = 6,
    trading = 7,
    feeding = 8,
    igniting = 9,
    coloring = 10,
    naming = 11,
    leashing = 12,
    unleashing = 13,
    petsleep = 14,
    trusting = 15,
    commanding = 16,
    equipping = 17,
    _,

    pub fn decode(r: *Reader) DecodeError!MinecraftEventingInteractionType {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: MinecraftEventingInteractionType, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};

/// Wire type `MinecraftEventing::POIBlockInteractionType`.
pub const MinecraftEventingPoiBlockInteractionType = enum(u8) {
    none = 0,
    extend = 1,
    clone = 2,
    lock = 3,
    create = 4,
    createlocator = 5,
    rename = 6,
    itemplaced = 7,
    itemremoved = 8,
    cooking = 9,
    dousing = 10,
    lighting = 11,
    haystack = 12,
    filled = 13,
    emptied = 14,
    adddye = 15,
    dyeitem = 16,
    clearitem = 17,
    enchantarrow = 18,
    compostitemplaced = 19,
    recoveredbonemeal = 20,
    bookplaced = 21,
    bookopened = 22,
    disenchant = 23,
    repair = 24,
    disenchantandrepair = 25,
    _,

    pub fn decode(r: *Reader) DecodeError!MinecraftEventingPoiBlockInteractionType {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: MinecraftEventingPoiBlockInteractionType, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::MobBorn`.
pub const MobBornEvent = struct {
    born_baby_entity_type: i32,
    born_baby_entity_variant: i32,
    born_baby_color: u8,

    pub fn decode(r: *Reader) DecodeError!MobBornEvent {
        var value: MobBornEvent = undefined;
        value.born_baby_entity_type = try r.readVarI32();
        value.born_baby_entity_variant = try r.readVarI32();
        value.born_baby_color = try r.readU8();
        return value;
    }

    pub fn encode(self: MobBornEvent, w: anytype) EncodeError!void {
        try w.writeVarI32(self.born_baby_entity_type);
        try w.writeVarI32(self.born_baby_entity_variant);
        try w.writeU8(self.born_baby_color);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::MobKilled`.
pub const MobKilledEvent = struct {
    instigator_actor_id: i64,
    target_actor_id: i64,
    instigators_child_actor_type: types.ActorType,
    damage_source: i32,
    trade_tier: i32,
    trader_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!MobKilledEvent {
        var value: MobKilledEvent = undefined;
        value.instigator_actor_id = try r.readVarI64();
        value.target_actor_id = try r.readVarI64();
        value.instigators_child_actor_type = try types.ActorType.decode(r);
        value.damage_source = try r.readVarI32();
        value.trade_tier = try r.readVarI32();
        value.trader_name = try r.readString();
        if (value.trader_name.len > 128) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: MobKilledEvent, w: anytype) EncodeError!void {
        try w.writeVarI64(self.instigator_actor_id);
        try w.writeVarI64(self.target_actor_id);
        try self.instigators_child_actor_type.encode(w);
        try w.writeVarI32(self.damage_source);
        try w.writeVarI32(self.trade_tier);
        if (self.trader_name.len > 128) return error.InvalidValue;
        try w.writeString(self.trader_name);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::PiglinBarter`.
pub const PiglinBarterEvent = struct {
    item_id: i32,
    was_targeting_bartering_player: bool,

    pub fn decode(r: *Reader) DecodeError!PiglinBarterEvent {
        var value: PiglinBarterEvent = undefined;
        value.item_id = try r.readVarI32();
        value.was_targeting_bartering_player = try r.readBool();
        return value;
    }

    pub fn encode(self: PiglinBarterEvent, w: anytype) EncodeError!void {
        try w.writeVarI32(self.item_id);
        try w.writeBool(self.was_targeting_bartering_player);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::PlayerDied`.
pub const PlayerDiedEvent = struct {
    instigator_actor_id: i32,
    instigator_mob_variant: i32,
    damage_source: i32,
    died_in_raid: bool,

    pub fn decode(r: *Reader) DecodeError!PlayerDiedEvent {
        var value: PlayerDiedEvent = undefined;
        value.instigator_actor_id = try r.readVarI32();
        value.instigator_mob_variant = try r.readVarI32();
        value.damage_source = try r.readVarI32();
        value.died_in_raid = try r.readBool();
        return value;
    }

    pub fn encode(self: PlayerDiedEvent, w: anytype) EncodeError!void {
        try w.writeVarI32(self.instigator_actor_id);
        try w.writeVarI32(self.instigator_mob_variant);
        try w.writeVarI32(self.damage_source);
        try w.writeBool(self.died_in_raid);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::PortalUsed`.
pub const PortalUsedEvent = struct {
    source_dimension_id: i32,
    target_dimension_id: i32,

    pub fn decode(r: *Reader) DecodeError!PortalUsedEvent {
        var value: PortalUsedEvent = undefined;
        value.source_dimension_id = try r.readVarI32();
        value.target_dimension_id = try r.readVarI32();
        return value;
    }

    pub fn encode(self: PortalUsedEvent, w: anytype) EncodeError!void {
        try w.writeVarI32(self.source_dimension_id);
        try w.writeVarI32(self.target_dimension_id);
    }
};

/// Wire type `LegacyTelemetryEventPacketPayload::RaidUpdate`.
pub const RaidUpdateEvent = struct {
    current_wave: i32,
    total_waves: i32,
    success: bool,

    pub fn decode(r: *Reader) DecodeError!RaidUpdateEvent {
        var value: RaidUpdateEvent = undefined;
        value.current_wave = try r.readVarI32();
        value.total_waves = try r.readVarI32();
        value.success = try r.readBool();
        return value;
    }

    pub fn encode(self: RaidUpdateEvent, w: anytype) EncodeError!void {
        try w.writeVarI32(self.current_wave);
        try w.writeVarI32(self.total_waves);
        try w.writeBool(self.success);
    }
};
