//! FeatureRegistryPacket (ID 191), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    features_data_list: codec.List(FeatureRegistryFeatureBinaryJsonFormat, FeatureRegistryFeatureBinaryJsonFormat),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.features_data_list = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(FeatureRegistryFeatureBinaryJsonFormat, FeatureRegistryFeatureBinaryJsonFormat).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.features_data_list.len);
        try self.features_data_list.encode(w);
    }
};

/// Wire type `FeatureRegistry::FeatureBinaryJsonFormat`.
pub const FeatureRegistryFeatureBinaryJsonFormat = struct {
    feature_name: []const u8,
    binary_json_output: []const u8,

    pub fn decode(r: *Reader) DecodeError!FeatureRegistryFeatureBinaryJsonFormat {
        var value: FeatureRegistryFeatureBinaryJsonFormat = undefined;
        value.feature_name = try r.readString();
        value.binary_json_output = try r.readByteArray();
        return value;
    }

    pub fn encode(self: FeatureRegistryFeatureBinaryJsonFormat, w: anytype) EncodeError!void {
        try w.writeString(self.feature_name);
        try w.writeByteArray(self.binary_json_output);
    }
};
