//! GraphicsOverrideParameterPacket (ID 331), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    parameter_keyframe_values: codec.List(PacketParameterKeyframeValuesEntry, PacketParameterKeyframeValuesEntry),
    float_value: ?f32,
    vec3_value: ?codec.Vec3f,
    biome_identifier: []const u8,
    player_identifier: ?[]const u8,
    identifier_for_parameter: GraphicsOverrideParameterType,
    reset_parameter: bool,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.parameter_keyframe_values = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 255) return error.InvalidValue;
            break :blk try codec.List(PacketParameterKeyframeValuesEntry, PacketParameterKeyframeValuesEntry).decode(r, count);
        };
        value.float_value = if (try r.readBool()) try r.readF32() else null;
        value.vec3_value = if (try r.readBool()) try r.readVec3f() else null;
        value.biome_identifier = try r.readString();
        if (value.biome_identifier.len > 255) return error.InvalidValue;
        value.player_identifier = null;
        if (try r.readBool()) {
            var present: []const u8 = undefined;
            present = try r.readString();
            if (present.len > 255) return error.InvalidValue;
            value.player_identifier = present;
        }
        value.identifier_for_parameter = try GraphicsOverrideParameterType.decode(r);
        value.reset_parameter = try r.readBool();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        if (self.parameter_keyframe_values.len > 255) return error.InvalidValue;
        try w.writeCount(.var_u32, self.parameter_keyframe_values.len);
        try self.parameter_keyframe_values.encode(w);
        try w.writeBool(self.float_value != null);
        if (self.float_value) |present| {
            try w.writeF32(present);
        }
        try w.writeBool(self.vec3_value != null);
        if (self.vec3_value) |present| {
            try w.writeVec3f(present);
        }
        if (self.biome_identifier.len > 255) return error.InvalidValue;
        try w.writeString(self.biome_identifier);
        try w.writeBool(self.player_identifier != null);
        if (self.player_identifier) |present| {
            if (present.len > 255) return error.InvalidValue;
            try w.writeString(present);
        }
        try self.identifier_for_parameter.encode(w);
        try w.writeBool(self.reset_parameter);
    }
};

/// Wire type `GraphicsOverrideParameterType`.
pub const GraphicsOverrideParameterType = enum(u8) {
    skyzenithcolor = 0,
    skyhorizoncolor = 1,
    horizonblendmin = 2,
    horizonblendmax = 3,
    horizonblendstart = 4,
    horizonblendmiestart = 5,
    rayleighstrength = 6,
    sunmiestrength = 7,
    moonmiestrength = 8,
    sunglareshape = 9,
    chlorophyll = 10,
    cdom = 11,
    suspendedsediment = 12,
    wavesdepth = 13,
    wavesfrequency = 14,
    wavesfrequencyscaling = 15,
    wavesspeed = 16,
    wavesspeedscaling = 17,
    wavesshape = 18,
    wavesoctaves = 19,
    wavesmix = 20,
    wavespull = 21,
    wavesdirectionincrement = 22,
    midtonescontrast = 23,
    highlightscontrast = 24,
    shadowscontrast = 25,
    highlightsgain = 26,
    highlightsgamma = 27,
    highlightsoffset = 28,
    highlightssaturation = 29,
    midtonesgain = 30,
    midtonesgamma = 31,
    midtonesoffset = 32,
    midtonessaturation = 33,
    shadowsgain = 34,
    shadowsgamma = 35,
    shadowsoffset = 36,
    shadowssaturation = 37,
    highlightsmin = 38,
    shadowsmax = 39,
    temperature = 40,
    suncolor = 41,
    sunilluminance = 42,
    mooncolor = 43,
    moonilluminance = 44,
    flashcolor = 45,
    flashilluminance = 46,
    ambientcolor = 47,
    ambientilluminance = 48,
    emissivedesaturation = 49,
    skyintensity = 50,
    orbitaloffsetdegrees = 51,
    _,

    pub fn decode(r: *Reader) DecodeError!GraphicsOverrideParameterType {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: GraphicsOverrideParameterType, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};

pub const PacketParameterKeyframeValuesEntry = struct {
    key: f32,
    value: codec.Vec3f,

    pub fn decode(r: *Reader) DecodeError!PacketParameterKeyframeValuesEntry {
        var value: PacketParameterKeyframeValuesEntry = undefined;
        value.key = try r.readF32();
        value.value = try r.readVec3f();
        return value;
    }

    pub fn encode(self: PacketParameterKeyframeValuesEntry, w: anytype) EncodeError!void {
        try w.writeF32(self.key);
        try w.writeVec3f(self.value);
    }
};
