//! HurtArmorPacket (ID 38), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    cause: i32,
    damage: i32,
    armor_slots: u64,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.cause = try r.readVarI32();
        value.damage = try r.readVarI32();
        value.armor_slots = try r.readVarU64();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI32(self.cause);
        try w.writeVarI32(self.damage);
        try w.writeVarU64(self.armor_slots);
    }
};
