//! InventoryTransactionPacket (ID 30), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    legacy_request_id: i32,
    legacy_set_item_slots: ?codec.List(types.LegacySetSlot, types.LegacySetSlot),
    transaction: InventoryTransactionTransaction,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.legacy_request_id = try r.readVarI32();
        value.legacy_set_item_slots = null;
        if (try r.readBool()) {
            var present: codec.List(types.LegacySetSlot, types.LegacySetSlot) = undefined;
            present = blk: {
                const count = try r.readCount(.var_u32);
                break :blk try codec.List(types.LegacySetSlot, types.LegacySetSlot).decode(r, count);
            };
            value.legacy_set_item_slots = present;
        }
        value.transaction = try InventoryTransactionTransaction.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI32(self.legacy_request_id);
        try w.writeBool(self.legacy_set_item_slots != null);
        if (self.legacy_set_item_slots) |present| {
            try w.writeCount(.var_u32, present.len);
            try present.encode(w);
        }
        try self.transaction.encode(w);
    }
};

pub const InventoryTransactionTransaction = union(enum(u32)) {
    normal_transaction_data: codec.List(types.InventoryAction, types.InventoryAction),
    inventory_mismatch_data: codec.List(types.InventoryAction, types.InventoryAction),
    item_use_inventory_transaction: types.ItemUseInventoryTransaction,
    item_use_on_actor_inventory_transaction: ItemUseOnActorInventoryTransaction,
    item_release_inventory_transaction: ItemReleaseInventoryTransaction,

    pub fn decode(r: *Reader) DecodeError!InventoryTransactionTransaction {
        switch (try r.readVarU32()) {
            0 => {
                var value: codec.List(types.InventoryAction, types.InventoryAction) = undefined;
                value = blk: {
                    const count = try r.readCount(.var_u32);
                    break :blk try codec.List(types.InventoryAction, types.InventoryAction).decode(r, count);
                };
                return .{ .normal_transaction_data = value };
            },
            1 => {
                var value: codec.List(types.InventoryAction, types.InventoryAction) = undefined;
                value = blk: {
                    const count = try r.readCount(.var_u32);
                    break :blk try codec.List(types.InventoryAction, types.InventoryAction).decode(r, count);
                };
                return .{ .inventory_mismatch_data = value };
            },
            2 => return .{ .item_use_inventory_transaction = try types.ItemUseInventoryTransaction.decode(r) },
            3 => return .{ .item_use_on_actor_inventory_transaction = try ItemUseOnActorInventoryTransaction.decode(r) },
            4 => return .{ .item_release_inventory_transaction = try ItemReleaseInventoryTransaction.decode(r) },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: InventoryTransactionTransaction, w: anytype) EncodeError!void {
        try w.writeVarU32(@intFromEnum(self));
        switch (self) {
            .normal_transaction_data => |value| {
                try w.writeCount(.var_u32, value.len);
                try value.encode(w);
            },
            .inventory_mismatch_data => |value| {
                try w.writeCount(.var_u32, value.len);
                try value.encode(w);
            },
            .item_use_inventory_transaction => |value| {
                try value.encode(w);
            },
            .item_use_on_actor_inventory_transaction => |value| {
                try value.encode(w);
            },
            .item_release_inventory_transaction => |value| {
                try value.encode(w);
            },
        }
    }
};

/// Wire type `ItemReleaseInventoryTransaction`.
pub const ItemReleaseInventoryTransaction = struct {
    actions: codec.List(types.InventoryAction, types.InventoryAction),
    action_type: ItemReleaseInventoryTransactionActionType,
    slot: i32,
    item: types.NetworkItemStackDescriptor,
    from_position: codec.Vec3f,

    pub fn decode(r: *Reader) DecodeError!ItemReleaseInventoryTransaction {
        var value: ItemReleaseInventoryTransaction = undefined;
        value.actions = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(types.InventoryAction, types.InventoryAction).decode(r, count);
        };
        value.action_type = try ItemReleaseInventoryTransactionActionType.decode(r);
        value.slot = try r.readVarI32();
        value.item = try types.NetworkItemStackDescriptor.decode(r);
        value.from_position = try r.readVec3f();
        return value;
    }

    pub fn encode(self: ItemReleaseInventoryTransaction, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.actions.len);
        try self.actions.encode(w);
        try self.action_type.encode(w);
        try w.writeVarI32(self.slot);
        try self.item.encode(w);
        try w.writeVec3f(self.from_position);
    }
};

/// Wire type `ItemReleaseInventoryTransaction::ActionType`.
pub const ItemReleaseInventoryTransactionActionType = enum(i32) {
    release = 0,
    use = 1,
    _,

    pub fn decode(r: *Reader) DecodeError!ItemReleaseInventoryTransactionActionType {
        return @enumFromInt(try r.readVarI32());
    }

    pub fn encode(self: ItemReleaseInventoryTransactionActionType, w: anytype) EncodeError!void {
        try w.writeVarI32(@intFromEnum(self));
    }
};

/// Wire type `ItemUseOnActorInventoryTransaction`.
pub const ItemUseOnActorInventoryTransaction = struct {
    actions: codec.List(types.InventoryAction, types.InventoryAction),
    runtime_id: u64,
    action_type: ItemUseOnActorInventoryTransactionActionType,
    slot: i32,
    item: types.NetworkItemStackDescriptor,
    from_position: codec.Vec3f,
    hit_position: codec.Vec3f,

    pub fn decode(r: *Reader) DecodeError!ItemUseOnActorInventoryTransaction {
        var value: ItemUseOnActorInventoryTransaction = undefined;
        value.actions = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(types.InventoryAction, types.InventoryAction).decode(r, count);
        };
        value.runtime_id = try r.readVarU64();
        value.action_type = try ItemUseOnActorInventoryTransactionActionType.decode(r);
        value.slot = try r.readVarI32();
        value.item = try types.NetworkItemStackDescriptor.decode(r);
        value.from_position = try r.readVec3f();
        value.hit_position = try r.readVec3f();
        return value;
    }

    pub fn encode(self: ItemUseOnActorInventoryTransaction, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.actions.len);
        try self.actions.encode(w);
        try w.writeVarU64(self.runtime_id);
        try self.action_type.encode(w);
        try w.writeVarI32(self.slot);
        try self.item.encode(w);
        try w.writeVec3f(self.from_position);
        try w.writeVec3f(self.hit_position);
    }
};

/// Wire type `ItemUseOnActorInventoryTransaction::ActionType`.
pub const ItemUseOnActorInventoryTransactionActionType = enum(i32) {
    interact = 0,
    attack = 1,
    item_interact = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!ItemUseOnActorInventoryTransactionActionType {
        return @enumFromInt(try r.readVarI32());
    }

    pub fn encode(self: ItemUseOnActorInventoryTransactionActionType, w: anytype) EncodeError!void {
        try w.writeVarI32(@intFromEnum(self));
    }
};
