//! LevelChunkPacket (ID 58), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    chunk_position: codec.ChunkPosition,
    dimension_id: i32,
    sub_chunks_count: u32,
    client_request_sub_chunk_limit: ?i32,
    cache_enabled: bool,
    cache_metadata: codec.List(u64, codec.Prim(.u64le)),
    serialized_chunk_data: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.chunk_position = try r.readChunkPosition();
        value.dimension_id = try r.readVarI32();
        value.sub_chunks_count = try r.readVarU32();
        if (value.sub_chunks_count > 64) return error.InvalidValue;
        value.client_request_sub_chunk_limit = null;
        if (try r.readBool()) {
            var present: i32 = undefined;
            present = try r.readVarI32();
            if (present < -1) return error.InvalidValue;
            if (present > 64) return error.InvalidValue;
            value.client_request_sub_chunk_limit = present;
        }
        value.cache_enabled = try r.readBool();
        value.cache_metadata = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 65) return error.InvalidValue;
            break :blk try codec.List(u64, codec.Prim(.u64le)).decode(r, count);
        };
        value.serialized_chunk_data = try r.readByteArray();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeChunkPosition(self.chunk_position);
        try w.writeVarI32(self.dimension_id);
        if (self.sub_chunks_count > 64) return error.InvalidValue;
        try w.writeVarU32(self.sub_chunks_count);
        try w.writeBool(self.client_request_sub_chunk_limit != null);
        if (self.client_request_sub_chunk_limit) |present| {
            if (present < -1) return error.InvalidValue;
            if (present > 64) return error.InvalidValue;
            try w.writeVarI32(present);
        }
        try w.writeBool(self.cache_enabled);
        if (self.cache_metadata.len > 65) return error.InvalidValue;
        try w.writeCount(.var_u32, self.cache_metadata.len);
        try self.cache_metadata.encode(w);
        try w.writeByteArray(self.serialized_chunk_data);
    }
};
