//! MapInfoRequestPacket (ID 68), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    map_unique_id: i64,
    client_pixels_list: codec.List(PixelRequest, PixelRequest),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.map_unique_id = try r.readVarI64();
        value.client_pixels_list = blk: {
            const count = try r.readCount(.u32le);
            if (count > 16384) return error.InvalidValue;
            break :blk try codec.List(PixelRequest, PixelRequest).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI64(self.map_unique_id);
        if (self.client_pixels_list.len > 16384) return error.InvalidValue;
        try w.writeCount(.u32le, self.client_pixels_list.len);
        try self.client_pixels_list.encode(w);
    }
};

/// Wire type `MapInfoRequestPacketAnon::ClientPixelsProxy`.
pub const PixelRequest = struct {
    pixel: u32,
    index: u16,

    pub fn decode(r: *Reader) DecodeError!PixelRequest {
        var value: PixelRequest = undefined;
        value.pixel = try r.readU32();
        value.index = try r.readU16();
        return value;
    }

    pub fn encode(self: PixelRequest, w: anytype) EncodeError!void {
        try w.writeU32(self.pixel);
        try w.writeU16(self.index);
    }
};
