//! MovePlayerPacket (ID 19), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    player_runtime_id: u64,
    position: codec.Vec3f,
    rotation: codec.Vec2f,
    y_head_rotation: f32,
    position_mode: PlayerPositionModeComponentPositionMode,
    on_ground: bool,
    riding_runtime_id: u64,
    teleport_data: ?MovePlayerTeleportData,
    tick: u64,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.player_runtime_id = try r.readVarU64();
        value.position = try r.readVec3f();
        value.rotation = try r.readVec2f();
        value.y_head_rotation = try r.readF32();
        value.position_mode = try PlayerPositionModeComponentPositionMode.decode(r);
        value.on_ground = try r.readBool();
        value.riding_runtime_id = try r.readVarU64();
        value.teleport_data = if (try r.readBool()) try MovePlayerTeleportData.decode(r) else null;
        value.tick = try r.readVarU64();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarU64(self.player_runtime_id);
        try w.writeVec3f(self.position);
        try w.writeVec2f(self.rotation);
        try w.writeF32(self.y_head_rotation);
        try self.position_mode.encode(w);
        try w.writeBool(self.on_ground);
        try w.writeVarU64(self.riding_runtime_id);
        try w.writeBool(self.teleport_data != null);
        if (self.teleport_data) |present| {
            try present.encode(w);
        }
        try w.writeVarU64(self.tick);
    }
};

/// Wire type `MovePlayerTeleportData`.
pub const MovePlayerTeleportData = struct {
    teleportation_cause: i32,
    source_actor_type: i32,

    pub fn decode(r: *Reader) DecodeError!MovePlayerTeleportData {
        var value: MovePlayerTeleportData = undefined;
        value.teleportation_cause = try r.readI32();
        value.source_actor_type = try r.readI32();
        return value;
    }

    pub fn encode(self: MovePlayerTeleportData, w: anytype) EncodeError!void {
        try w.writeI32(self.teleportation_cause);
        try w.writeI32(self.source_actor_type);
    }
};

/// Wire type `PlayerPositionModeComponent::PositionMode`.
pub const PlayerPositionModeComponentPositionMode = enum(u8) {
    normal = 0,
    respawn = 1,
    teleport = 2,
    onlyheadrot = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!PlayerPositionModeComponentPositionMode {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: PlayerPositionModeComponentPositionMode, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};
