//! PlayerFogPacket (ID 160), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    fog_stack: codec.List([]const u8, codec.Prim(.string)),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.fog_stack = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.fog_stack.len);
        try self.fog_stack.encode(w);
    }
};
