//! PlayerSkinPacket (ID 93), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    uuid: [16]u8,
    serialized_skin: types.SerializedSkinRef,
    localized_new_skin_name: []const u8,
    localized_old_skin_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.uuid = try r.readUuid();
        value.serialized_skin = try types.SerializedSkinRef.decode(r);
        value.localized_new_skin_name = try r.readString();
        value.localized_old_skin_name = try r.readString();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeUuid(self.uuid);
        try self.serialized_skin.encode(w);
        try w.writeString(self.localized_new_skin_name);
        try w.writeString(self.localized_old_skin_name);
    }
};
