//! RecordStartedPacket (ID 352), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    block_position: codec.BlockPosition,
    server_sound_handle: u64,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.block_position = try r.readBlockPosition();
        value.server_sound_handle = try r.readU64();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeBlockPosition(self.block_position);
        try w.writeU64(self.server_sound_handle);
    }
};
