//! ResourcePackChunkRequestPacket (ID 84), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    resource_name: []const u8,
    chunk: i32,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.resource_name = try r.readString();
        value.chunk = try r.readI32();
        if (value.chunk < 0) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeString(self.resource_name);
        if (self.chunk < 0) return error.InvalidValue;
        try w.writeI32(self.chunk);
    }
};
