//! RespawnPacket (ID 45), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    position: codec.Vec3f,
    state: PlayerRespawnState,
    player_runtime_id: u64,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.position = try r.readVec3f();
        value.state = try PlayerRespawnState.decode(r);
        value.player_runtime_id = try r.readVarU64();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVec3f(self.position);
        try self.state.encode(w);
        try w.writeVarU64(self.player_runtime_id);
    }
};

/// Wire type `PlayerRespawnState`.
pub const PlayerRespawnState = enum(u8) {
    searchingforspawn = 0,
    readytospawn = 1,
    clientreadytospawn = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!PlayerRespawnState {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: PlayerRespawnState, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};
