//! ServerboundDataStorePacket (ID 332), sent by the client.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    update: types.DduiDataStoreUpdate,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.update = try types.DduiDataStoreUpdate.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.update.encode(w);
    }
};
