//! SetLastHurtByPacket (ID 96), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    last_hurt_by: types.ActorType,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.last_hurt_by = try types.ActorType.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.last_hurt_by.encode(w);
    }
};
