//! SetActorDataPacket (ID 39), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    target_runtime_id: u64,
    actor_data: codec.List(types.DataItemEntry, types.DataItemEntry),
    synched_properties: types.PropertySyncData,
    tick: u64,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.target_runtime_id = try r.readVarU64();
        value.actor_data = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(types.DataItemEntry, types.DataItemEntry).decode(r, count);
        };
        value.synched_properties = try types.PropertySyncData.decode(r);
        value.tick = try r.readVarU64();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarU64(self.target_runtime_id);
        try w.writeCount(.var_u32, self.actor_data.len);
        try self.actor_data.encode(w);
        try self.synched_properties.encode(w);
        try w.writeVarU64(self.tick);
    }
};
