//! SetDisplayObjectivePacket (ID 107), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    display_slot_name: []const u8,
    objective_name: []const u8,
    objective_display_name: []const u8,
    criteria_name: []const u8,
    sort_order: i32,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.display_slot_name = try r.readString();
        value.objective_name = try r.readString();
        value.objective_display_name = try r.readString();
        value.criteria_name = try r.readString();
        value.sort_order = try r.readVarI32();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeString(self.display_slot_name);
        try w.writeString(self.objective_name);
        try w.writeString(self.objective_display_name);
        try w.writeString(self.criteria_name);
        try w.writeVarI32(self.sort_order);
    }
};
