//! SpawnParticleEffectPacket (ID 118), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    dimension_id: u8,
    actor_id: i64,
    position: codec.Vec3f,
    effect_name: []const u8,
    molang_variables: ?[]const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.dimension_id = try r.readU8();
        value.actor_id = try r.readVarI64();
        value.position = try r.readVec3f();
        value.effect_name = try r.readString();
        value.molang_variables = if (try r.readBool()) try r.readString() else null;
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeU8(self.dimension_id);
        try w.writeVarI64(self.actor_id);
        try w.writeVec3f(self.position);
        try w.writeString(self.effect_name);
        try w.writeBool(self.molang_variables != null);
        if (self.molang_variables) |present| {
            try w.writeString(present);
        }
    }
};
