//! StructureTemplateDataResponsePacket (ID 133), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    structure_name: []const u8,
    structures_nbt: []const u8,
    response_type: StructureTemplateResponseType,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.structure_name = try r.readString();
        value.structures_nbt = try r.readNbt();
        value.response_type = try StructureTemplateResponseType.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeString(self.structure_name);
        try w.writeNbt(self.structures_nbt);
        try self.response_type.encode(w);
    }
};

/// Wire type `StructureTemplateResponseType`.
pub const StructureTemplateResponseType = enum(u8) {
    none = 0,
    @"export" = 1,
    query = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!StructureTemplateResponseType {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: StructureTemplateResponseType, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};
