//! SubChunkPacket (ID 174), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    cache_enabled: bool,
    dimension_type: i32,
    center_pos: codec.SubChunkPosition,
    sub_chunk_data: codec.List(SubChunkData, SubChunkData),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.cache_enabled = try r.readBool();
        value.dimension_type = try r.readVarI32();
        value.center_pos = try r.readSubChunkPosition();
        value.sub_chunk_data = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 8192) return error.InvalidValue;
            break :blk try codec.List(SubChunkData, SubChunkData).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeBool(self.cache_enabled);
        try w.writeVarI32(self.dimension_type);
        try w.writeSubChunkPosition(self.center_pos);
        if (self.sub_chunk_data.len > 8192) return error.InvalidValue;
        try w.writeCount(.var_u32, self.sub_chunk_data.len);
        try self.sub_chunk_data.encode(w);
    }
};

/// Wire type `SubChunkPacketPayload::SubChunkPacketData`.
pub const SubChunkData = struct {
    sub_chunk_pos_offset: types.SubChunkPosOffset,
    sub_chunk_request_result: SubChunkRequestResult,
    serialized_sub_chunk: ?[]const u8,
    height_map_data: SubChunkHeightmapData,
    blob_id: ?u64,

    pub fn decode(r: *Reader) DecodeError!SubChunkData {
        var value: SubChunkData = undefined;
        value.sub_chunk_pos_offset = try types.SubChunkPosOffset.decode(r);
        value.sub_chunk_request_result = try SubChunkRequestResult.decode(r);
        value.serialized_sub_chunk = if (try r.readBool()) try r.readByteArray() else null;
        value.height_map_data = try SubChunkHeightmapData.decode(r);
        value.blob_id = if (try r.readBool()) try r.readU64() else null;
        return value;
    }

    pub fn encode(self: SubChunkData, w: anytype) EncodeError!void {
        try self.sub_chunk_pos_offset.encode(w);
        try self.sub_chunk_request_result.encode(w);
        try w.writeBool(self.serialized_sub_chunk != null);
        if (self.serialized_sub_chunk) |present| {
            try w.writeByteArray(present);
        }
        try self.height_map_data.encode(w);
        try w.writeBool(self.blob_id != null);
        if (self.blob_id) |present| {
            try w.writeU64(present);
        }
    }
};

/// Wire type `SubChunkPacketPayload::HeightMapDataType`.
pub const SubChunkHeightMapDataType = enum(u8) {
    nodata = 0,
    hasdata = 1,
    alltoohigh = 2,
    alltoolow = 3,
    allcopied = 4,
    _,

    pub fn decode(r: *Reader) DecodeError!SubChunkHeightMapDataType {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: SubChunkHeightMapDataType, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};

/// Wire type `SubChunkPacketPayload::HeightmapData`.
pub const SubChunkHeightmapData = struct {
    height_map_type: SubChunkHeightMapDataType,
    subchunk_height_map: ?[16]codec.List(i8, codec.Prim(.i8)),
    render_height_map_type: SubChunkHeightMapDataType,
    subchunk_render_height_map: ?[16]codec.List(i8, codec.Prim(.i8)),

    pub fn decode(r: *Reader) DecodeError!SubChunkHeightmapData {
        var value: SubChunkHeightmapData = undefined;
        value.height_map_type = try SubChunkHeightMapDataType.decode(r);
        value.subchunk_height_map = null;
        if (try r.readBool()) {
            var present: [16]codec.List(i8, codec.Prim(.i8)) = undefined;
            for (&present) |*item1| {
                item1.* = blk: {
                    const count = try r.readCount(.var_u32);
                    if (count < 16) return error.InvalidValue;
                    if (count > 16) return error.InvalidValue;
                    break :blk try codec.List(i8, codec.Prim(.i8)).decode(r, count);
                };
            }
            value.subchunk_height_map = present;
        }
        value.render_height_map_type = try SubChunkHeightMapDataType.decode(r);
        value.subchunk_render_height_map = null;
        if (try r.readBool()) {
            var present: [16]codec.List(i8, codec.Prim(.i8)) = undefined;
            for (&present) |*item1| {
                item1.* = blk: {
                    const count = try r.readCount(.var_u32);
                    if (count < 16) return error.InvalidValue;
                    if (count > 16) return error.InvalidValue;
                    break :blk try codec.List(i8, codec.Prim(.i8)).decode(r, count);
                };
            }
            value.subchunk_render_height_map = present;
        }
        return value;
    }

    pub fn encode(self: SubChunkHeightmapData, w: anytype) EncodeError!void {
        try self.height_map_type.encode(w);
        try w.writeBool(self.subchunk_height_map != null);
        if (self.subchunk_height_map) |present| {
            for (present) |item1| {
                if (item1.len < 16) return error.InvalidValue;
                if (item1.len > 16) return error.InvalidValue;
                try w.writeCount(.var_u32, item1.len);
                try item1.encode(w);
            }
        }
        try self.render_height_map_type.encode(w);
        try w.writeBool(self.subchunk_render_height_map != null);
        if (self.subchunk_render_height_map) |present| {
            for (present) |item1| {
                if (item1.len < 16) return error.InvalidValue;
                if (item1.len > 16) return error.InvalidValue;
                try w.writeCount(.var_u32, item1.len);
                try item1.encode(w);
            }
        }
    }
};

/// Wire type `SubChunkPacketPayload::SubChunkRequestResult`.
pub const SubChunkRequestResult = enum(u8) {
    success = 1,
    levelchunkdoesntexist = 2,
    wrongdimension = 3,
    playerdoesntexist = 4,
    indexoutofbounds = 5,
    successallair = 6,
    _,

    pub fn decode(r: *Reader) DecodeError!SubChunkRequestResult {
        return @enumFromInt(try r.readU8());
    }

    pub fn encode(self: SubChunkRequestResult, w: anytype) EncodeError!void {
        try w.writeU8(@intFromEnum(self));
    }
};
