//! SyncWorldClocksPacket (ID 344), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    data: SyncWorldClocksData,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.data = try SyncWorldClocksData.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.data.encode(w);
    }
};

/// Wire type `SyncWorldClockStateData`.
pub const SyncWorldClockStateData = struct {
    clock_id: u64,
    time: i32,
    is_paused: bool,

    pub fn decode(r: *Reader) DecodeError!SyncWorldClockStateData {
        var value: SyncWorldClockStateData = undefined;
        value.clock_id = try r.readVarU64();
        value.time = try r.readVarI32();
        value.is_paused = try r.readBool();
        return value;
    }

    pub fn encode(self: SyncWorldClockStateData, w: anytype) EncodeError!void {
        try w.writeVarU64(self.clock_id);
        try w.writeVarI32(self.time);
        try w.writeBool(self.is_paused);
    }
};

/// Wire type `SyncWorldClocksPacketPayload::AddTimeMarkerData`.
pub const SyncWorldClocksAddTimeMarkerData = struct {
    clock_id: u64,
    time_markers: codec.List(TimeMarkerData, TimeMarkerData),

    pub fn decode(r: *Reader) DecodeError!SyncWorldClocksAddTimeMarkerData {
        var value: SyncWorldClocksAddTimeMarkerData = undefined;
        value.clock_id = try r.readVarU64();
        value.time_markers = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 256) return error.InvalidValue;
            break :blk try codec.List(TimeMarkerData, TimeMarkerData).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: SyncWorldClocksAddTimeMarkerData, w: anytype) EncodeError!void {
        try w.writeVarU64(self.clock_id);
        if (self.time_markers.len > 256) return error.InvalidValue;
        try w.writeCount(.var_u32, self.time_markers.len);
        try self.time_markers.encode(w);
    }
};

pub const SyncWorldClocksData = union(enum(u32)) {
    sync_state: codec.List(SyncWorldClockStateData, SyncWorldClockStateData),
    initialize_registry: codec.List(WorldClockData, WorldClockData),
    add_time_marker: SyncWorldClocksAddTimeMarkerData,
    remove_time_marker: SyncWorldClocksRemoveTimeMarkerData,

    pub fn decode(r: *Reader) DecodeError!SyncWorldClocksData {
        switch (try r.readVarU32()) {
            0 => {
                var value: codec.List(SyncWorldClockStateData, SyncWorldClockStateData) = undefined;
                value = blk: {
                    const count = try r.readCount(.var_u32);
                    if (count > 256) return error.InvalidValue;
                    break :blk try codec.List(SyncWorldClockStateData, SyncWorldClockStateData).decode(r, count);
                };
                return .{ .sync_state = value };
            },
            1 => {
                var value: codec.List(WorldClockData, WorldClockData) = undefined;
                value = blk: {
                    const count = try r.readCount(.var_u32);
                    if (count > 256) return error.InvalidValue;
                    break :blk try codec.List(WorldClockData, WorldClockData).decode(r, count);
                };
                return .{ .initialize_registry = value };
            },
            2 => return .{ .add_time_marker = try SyncWorldClocksAddTimeMarkerData.decode(r) },
            3 => return .{ .remove_time_marker = try SyncWorldClocksRemoveTimeMarkerData.decode(r) },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: SyncWorldClocksData, w: anytype) EncodeError!void {
        try w.writeVarU32(@intFromEnum(self));
        switch (self) {
            .sync_state => |value| {
                if (value.len > 256) return error.InvalidValue;
                try w.writeCount(.var_u32, value.len);
                try value.encode(w);
            },
            .initialize_registry => |value| {
                if (value.len > 256) return error.InvalidValue;
                try w.writeCount(.var_u32, value.len);
                try value.encode(w);
            },
            .add_time_marker => |value| {
                try value.encode(w);
            },
            .remove_time_marker => |value| {
                try value.encode(w);
            },
        }
    }
};

/// Wire type `SyncWorldClocksPacketPayload::RemoveTimeMarkerData`.
pub const SyncWorldClocksRemoveTimeMarkerData = struct {
    clock_id: u64,
    time_marker_ids: codec.List(u64, codec.Prim(.var_u64)),

    pub fn decode(r: *Reader) DecodeError!SyncWorldClocksRemoveTimeMarkerData {
        var value: SyncWorldClocksRemoveTimeMarkerData = undefined;
        value.clock_id = try r.readVarU64();
        value.time_marker_ids = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 256) return error.InvalidValue;
            break :blk try codec.List(u64, codec.Prim(.var_u64)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: SyncWorldClocksRemoveTimeMarkerData, w: anytype) EncodeError!void {
        try w.writeVarU64(self.clock_id);
        if (self.time_marker_ids.len > 256) return error.InvalidValue;
        try w.writeCount(.var_u32, self.time_marker_ids.len);
        try self.time_marker_ids.encode(w);
    }
};

/// Wire type `TimeMarkerData`.
pub const TimeMarkerData = struct {
    id: u64,
    name: []const u8,
    time: i32,
    period: ?i32,

    pub fn decode(r: *Reader) DecodeError!TimeMarkerData {
        var value: TimeMarkerData = undefined;
        value.id = try r.readVarU64();
        value.name = try r.readString();
        if (value.name.len > 128) return error.InvalidValue;
        value.time = try r.readVarI32();
        value.period = if (try r.readBool()) try r.readI32() else null;
        return value;
    }

    pub fn encode(self: TimeMarkerData, w: anytype) EncodeError!void {
        try w.writeVarU64(self.id);
        if (self.name.len > 128) return error.InvalidValue;
        try w.writeString(self.name);
        try w.writeVarI32(self.time);
        try w.writeBool(self.period != null);
        if (self.period) |present| {
            try w.writeI32(present);
        }
    }
};

/// Wire type `WorldClockData`.
pub const WorldClockData = struct {
    id: u64,
    name: []const u8,
    time: i32,
    is_paused: bool,
    time_markers: codec.List(TimeMarkerData, TimeMarkerData),

    pub fn decode(r: *Reader) DecodeError!WorldClockData {
        var value: WorldClockData = undefined;
        value.id = try r.readVarU64();
        value.name = try r.readString();
        if (value.name.len > 128) return error.InvalidValue;
        value.time = try r.readVarI32();
        value.is_paused = try r.readBool();
        value.time_markers = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 256) return error.InvalidValue;
            break :blk try codec.List(TimeMarkerData, TimeMarkerData).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: WorldClockData, w: anytype) EncodeError!void {
        try w.writeVarU64(self.id);
        if (self.name.len > 128) return error.InvalidValue;
        try w.writeString(self.name);
        try w.writeVarI32(self.time);
        try w.writeBool(self.is_paused);
        if (self.time_markers.len > 256) return error.InvalidValue;
        try w.writeCount(.var_u32, self.time_markers.len);
        try self.time_markers.encode(w);
    }
};
