//! TakeItemActorPacket (ID 17), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    item_runtime_id: u64,
    actor_runtime_id: u64,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.item_runtime_id = try r.readVarU64();
        value.actor_runtime_id = try r.readVarU64();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarU64(self.item_runtime_id);
        try w.writeVarU64(self.actor_runtime_id);
    }
};
