//! UpdateBlockPacket (ID 21), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    block_position: codec.BlockPosition,
    block_runtime_id: u32,
    flags: u32,
    layer: u32,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.block_position = try r.readBlockPosition();
        value.block_runtime_id = try r.readVarU32();
        value.flags = try r.readVarU32();
        value.layer = try r.readVarU32();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeBlockPosition(self.block_position);
        try w.writeVarU32(self.block_runtime_id);
        try w.writeVarU32(self.flags);
        try w.writeVarU32(self.layer);
    }
};
