//! VoxelShapesPacket (ID 337), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    shapes: codec.List(VoxelShape, VoxelShape),
    name_map: codec.List(PacketNameMapEntry, PacketNameMapEntry),
    custom_shape_count: u16,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.shapes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(VoxelShape, VoxelShape).decode(r, count);
        };
        value.name_map = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(PacketNameMapEntry, PacketNameMapEntry).decode(r, count);
        };
        value.custom_shape_count = try r.readU16();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.shapes.len);
        try self.shapes.encode(w);
        try w.writeCount(.var_u32, self.name_map.len);
        try self.name_map.encode(w);
        try w.writeU16(self.custom_shape_count);
    }
};

/// Wire type `VoxelShapes::SerializableCells`.
pub const VoxelCells = struct {
    x_size: u8,
    y_size: u8,
    z_size: u8,
    storage: []const u8,

    pub fn decode(r: *Reader) DecodeError!VoxelCells {
        var value: VoxelCells = undefined;
        value.x_size = try r.readU8();
        if (value.x_size > 127) return error.InvalidValue;
        value.y_size = try r.readU8();
        if (value.y_size > 127) return error.InvalidValue;
        value.z_size = try r.readU8();
        if (value.z_size > 127) return error.InvalidValue;
        value.storage = try r.readByteArray();
        if (value.storage.len > 256048) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: VoxelCells, w: anytype) EncodeError!void {
        if (self.x_size > 127) return error.InvalidValue;
        try w.writeU8(self.x_size);
        if (self.y_size > 127) return error.InvalidValue;
        try w.writeU8(self.y_size);
        if (self.z_size > 127) return error.InvalidValue;
        try w.writeU8(self.z_size);
        if (self.storage.len > 256048) return error.InvalidValue;
        try w.writeByteArray(self.storage);
    }
};

/// Wire type `VoxelShapes::SerializableVoxelShape`.
pub const VoxelShape = struct {
    cells: VoxelCells,
    x_coordinates: codec.List(f32, codec.Prim(.f32le)),
    y_coordinates: codec.List(f32, codec.Prim(.f32le)),
    z_coordinates: codec.List(f32, codec.Prim(.f32le)),

    pub fn decode(r: *Reader) DecodeError!VoxelShape {
        var value: VoxelShape = undefined;
        value.cells = try VoxelCells.decode(r);
        value.x_coordinates = blk: {
            const count = try r.readCount(.var_u32);
            if (count < 1) return error.InvalidValue;
            if (count > 128) return error.InvalidValue;
            break :blk try codec.List(f32, codec.Prim(.f32le)).decode(r, count);
        };
        value.y_coordinates = blk: {
            const count = try r.readCount(.var_u32);
            if (count < 1) return error.InvalidValue;
            if (count > 128) return error.InvalidValue;
            break :blk try codec.List(f32, codec.Prim(.f32le)).decode(r, count);
        };
        value.z_coordinates = blk: {
            const count = try r.readCount(.var_u32);
            if (count < 1) return error.InvalidValue;
            if (count > 128) return error.InvalidValue;
            break :blk try codec.List(f32, codec.Prim(.f32le)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: VoxelShape, w: anytype) EncodeError!void {
        try self.cells.encode(w);
        if (self.x_coordinates.len < 1) return error.InvalidValue;
        if (self.x_coordinates.len > 128) return error.InvalidValue;
        try w.writeCount(.var_u32, self.x_coordinates.len);
        try self.x_coordinates.encode(w);
        if (self.y_coordinates.len < 1) return error.InvalidValue;
        if (self.y_coordinates.len > 128) return error.InvalidValue;
        try w.writeCount(.var_u32, self.y_coordinates.len);
        try self.y_coordinates.encode(w);
        if (self.z_coordinates.len < 1) return error.InvalidValue;
        if (self.z_coordinates.len > 128) return error.InvalidValue;
        try w.writeCount(.var_u32, self.z_coordinates.len);
        try self.z_coordinates.encode(w);
    }
};

pub const PacketNameMapEntry = struct {
    key: []const u8,
    value: u16,

    pub fn decode(r: *Reader) DecodeError!PacketNameMapEntry {
        var value: PacketNameMapEntry = undefined;
        value.key = try r.readString();
        value.value = try r.readU16();
        return value;
    }

    pub fn encode(self: PacketNameMapEntry, w: anytype) EncodeError!void {
        try w.writeString(self.key);
        try w.writeU16(self.value);
    }
};
