// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

/// Wire type `ActorLink`.
pub const EntityLink = struct {
    target_a: i64,
    target_b: i64,
    type: types.ActorLinkType,
    immediate: bool,
    passenger_initiated: bool,
    vehicle_angular_velocity: f32,

    pub fn decode(r: *Reader) DecodeError!EntityLink {
        var value: EntityLink = undefined;
        value.target_a = try r.readVarI64();
        value.target_b = try r.readVarI64();
        value.type = try types.ActorLinkType.decode(r);
        value.immediate = try r.readBool();
        value.passenger_initiated = try r.readBool();
        value.vehicle_angular_velocity = try r.readF32();
        return value;
    }

    pub fn encode(self: EntityLink, w: anytype) EncodeError!void {
        try w.writeVarI64(self.target_a);
        try w.writeVarI64(self.target_b);
        try self.type.encode(w);
        try w.writeBool(self.immediate);
        try w.writeBool(self.passenger_initiated);
        try w.writeF32(self.vehicle_angular_velocity);
    }
};
