// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

/// Wire type `ItemStackRequestCereal::RecipeIngredientData`.
pub const RecipeIngredient = struct {
    item_descriptor: types.ItemDescriptor,
    stack_size: u16,

    pub fn decode(r: *Reader) DecodeError!RecipeIngredient {
        var value: RecipeIngredient = undefined;
        value.item_descriptor = try types.ItemDescriptor.decode(r);
        value.stack_size = try r.readU16();
        if (value.stack_size < 1) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: RecipeIngredient, w: anytype) EncodeError!void {
        try self.item_descriptor.encode(w);
        if (self.stack_size < 1) return error.InvalidValue;
        try w.writeU16(self.stack_size);
    }
};
