// Generated by tools/codegen from protocol/schema/bedrock-2193.json. Do not edit.
const codec = @import("../../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

/// Wire type `SubChunkPacketPayload::SubChunkPosOffset`.
pub const SubChunkPosOffset = struct {
    subchunk_offset_x: i8,
    subchunk_offset_y: i8,
    subchunk_offset_z: i8,

    pub fn decode(r: *Reader) DecodeError!SubChunkPosOffset {
        var value: SubChunkPosOffset = undefined;
        value.subchunk_offset_x = try r.readI8();
        value.subchunk_offset_y = try r.readI8();
        value.subchunk_offset_z = try r.readI8();
        return value;
    }

    pub fn encode(self: SubChunkPosOffset, w: anytype) EncodeError!void {
        try w.writeI8(self.subchunk_offset_x);
        try w.writeI8(self.subchunk_offset_y);
        try w.writeI8(self.subchunk_offset_z);
    }
};
