//! AddBehaviorTreePacket (ID 89), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    behavior_tree_structure_json: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.behavior_tree_structure_json = try r.readString();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeString(self.behavior_tree_structure_json);
    }
};
