//! AddVolumeEntityPacket (ID 166), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    entity_network_id: u32,
    components: []const u8,
    json_identifier: []const u8,
    instance_name: []const u8,
    min_bounds: codec.BlockPosition,
    max_bounds: codec.BlockPosition,
    dimension_type: i32,
    engine_version: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.entity_network_id = try r.readVarU32();
        value.components = try r.readNbt();
        value.json_identifier = try r.readString();
        if (value.json_identifier.len < 1) return error.InvalidValue;
        value.instance_name = try r.readString();
        if (value.instance_name.len < 1) return error.InvalidValue;
        value.min_bounds = try r.readBlockPosition();
        value.max_bounds = try r.readBlockPosition();
        value.dimension_type = try r.readVarI32();
        value.engine_version = try r.readString();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarU32(self.entity_network_id);
        try w.writeNbt(self.components);
        if (self.json_identifier.len < 1) return error.InvalidValue;
        try w.writeString(self.json_identifier);
        if (self.instance_name.len < 1) return error.InvalidValue;
        try w.writeString(self.instance_name);
        try w.writeBlockPosition(self.min_bounds);
        try w.writeBlockPosition(self.max_bounds);
        try w.writeVarI32(self.dimension_type);
        try w.writeString(self.engine_version);
    }
};
