//! AgentActionEventPacket (ID 181), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    request_id: []const u8,
    action: AgentActionType,
    response: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.request_id = try r.readString();
        value.action = try AgentActionType.decode(r);
        value.response = try r.readString();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeString(self.request_id);
        try self.action.encode(w);
        try w.writeString(self.response);
    }
};

/// Wire type `AgentActionType`.
pub const AgentActionType = enum(i32) {
    attack = 1,
    collect = 2,
    destroy = 3,
    detectredstone = 4,
    detectobstacle = 5,
    drop = 6,
    dropall = 7,
    inspect = 8,
    inspectdata = 9,
    inspectitemcount = 10,
    inspectitemdetail = 11,
    inspectitemspace = 12,
    interact = 13,
    move = 14,
    placeblock = 15,
    till = 16,
    transferitemto = 17,
    turn = 18,
    _,

    pub fn decode(r: *Reader) DecodeError!AgentActionType {
        return @fromBackingInt(@intCast(try r.readI32()));
    }

    pub fn encode(self: AgentActionType, w: anytype) EncodeError!void {
        try w.writeI32(@backingInt(self));
    }
};
