//! BiomeDefinitionListPacket (ID 122), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    map_of_biome_names_to_data: codec.List(PacketMapOfBiomeNamesToDataEntry, PacketMapOfBiomeNamesToDataEntry),
    string_list: codec.List([]const u8, codec.Prim(.string)),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.map_of_biome_names_to_data = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(PacketMapOfBiomeNamesToDataEntry, PacketMapOfBiomeNamesToDataEntry).decode(r, count);
        };
        value.string_list = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.map_of_biome_names_to_data.len);
        try self.map_of_biome_names_to_data.encode(w);
        try w.writeCount(.var_u32, self.string_list.len);
        try self.string_list.encode(w);
    }
};

/// Wire type `BiomeCappedSurfaceData`.
pub const BiomeCappedSurface = struct {
    floor_blocks: codec.List(u32, codec.Prim(.u32le)),
    ceiling_blocks: codec.List(u32, codec.Prim(.u32le)),
    sea_block: ?u32,
    foundation_block: ?u32,
    beach_block: ?u32,

    pub fn decode(r: *Reader) DecodeError!BiomeCappedSurface {
        var value: BiomeCappedSurface = undefined;
        value.floor_blocks = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(u32, codec.Prim(.u32le)).decode(r, count);
        };
        value.ceiling_blocks = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(u32, codec.Prim(.u32le)).decode(r, count);
        };
        value.sea_block = if (try r.readBool()) try r.readU32() else null;
        value.foundation_block = if (try r.readBool()) try r.readU32() else null;
        value.beach_block = if (try r.readBool()) try r.readU32() else null;
        return value;
    }

    pub fn encode(self: BiomeCappedSurface, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.floor_blocks.len);
        try self.floor_blocks.encode(w);
        try w.writeCount(.var_u32, self.ceiling_blocks.len);
        try self.ceiling_blocks.encode(w);
        try w.writeBool(self.sea_block != null);
        if (self.sea_block) |present| {
            try w.writeU32(present);
        }
        try w.writeBool(self.foundation_block != null);
        if (self.foundation_block) |present| {
            try w.writeU32(present);
        }
        try w.writeBool(self.beach_block != null);
        if (self.beach_block) |present| {
            try w.writeU32(present);
        }
    }
};

/// Wire type `BiomeClimateData`.
pub const BiomeClimate = struct {
    temperature: f32,
    downfall: f32,
    snow_accumulation_min: f32,
    snow_accumulation_max: f32,

    pub fn decode(r: *Reader) DecodeError!BiomeClimate {
        var value: BiomeClimate = undefined;
        value.temperature = try r.readF32();
        value.downfall = try r.readF32();
        value.snow_accumulation_min = try r.readF32();
        value.snow_accumulation_max = try r.readF32();
        return value;
    }

    pub fn encode(self: BiomeClimate, w: anytype) EncodeError!void {
        try w.writeF32(self.temperature);
        try w.writeF32(self.downfall);
        try w.writeF32(self.snow_accumulation_min);
        try w.writeF32(self.snow_accumulation_max);
    }
};

/// Wire type `BiomeConditionalTransformationData`.
pub const BiomeConditionalTransformation = struct {
    transforms_into: codec.List(BiomeWeightedData, BiomeWeightedData),
    condition_json: u16,
    min_passing_neighbors: u32,

    pub fn decode(r: *Reader) DecodeError!BiomeConditionalTransformation {
        var value: BiomeConditionalTransformation = undefined;
        value.transforms_into = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(BiomeWeightedData, BiomeWeightedData).decode(r, count);
        };
        value.condition_json = try r.readU16();
        value.min_passing_neighbors = try r.readU32();
        return value;
    }

    pub fn encode(self: BiomeConditionalTransformation, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.transforms_into.len);
        try self.transforms_into.encode(w);
        try w.writeU16(self.condition_json);
        try w.writeU32(self.min_passing_neighbors);
    }
};

/// Wire type `BiomeConsolidatedFeatureData`.
pub const BiomeConsolidatedFeature = struct {
    scatter: BiomeScatterParameter,
    feature: u16,
    identifier: u16,
    pass: u16,
    can_use_internal_feature: bool,

    pub fn decode(r: *Reader) DecodeError!BiomeConsolidatedFeature {
        var value: BiomeConsolidatedFeature = undefined;
        value.scatter = try BiomeScatterParameter.decode(r);
        value.feature = try r.readU16();
        value.identifier = try r.readU16();
        value.pass = try r.readU16();
        value.can_use_internal_feature = try r.readBool();
        return value;
    }

    pub fn encode(self: BiomeConsolidatedFeature, w: anytype) EncodeError!void {
        try self.scatter.encode(w);
        try w.writeU16(self.feature);
        try w.writeU16(self.identifier);
        try w.writeU16(self.pass);
        try w.writeBool(self.can_use_internal_feature);
    }
};

/// Wire type `BiomeCoordinateData`.
pub const BiomeCoordinate = struct {
    min_value_type: i32,
    min_value: u16,
    max_value_type: i32,
    max_value: u16,
    grid_offset: u32,
    grid_step_size: u32,
    distribution: RandomDistributionType,

    pub fn decode(r: *Reader) DecodeError!BiomeCoordinate {
        var value: BiomeCoordinate = undefined;
        value.min_value_type = try r.readVarI32();
        value.min_value = try r.readU16();
        value.max_value_type = try r.readVarI32();
        value.max_value = try r.readU16();
        value.grid_offset = try r.readU32();
        value.grid_step_size = try r.readU32();
        value.distribution = try RandomDistributionType.decode(r);
        return value;
    }

    pub fn encode(self: BiomeCoordinate, w: anytype) EncodeError!void {
        try w.writeVarI32(self.min_value_type);
        try w.writeU16(self.min_value);
        try w.writeVarI32(self.max_value_type);
        try w.writeU16(self.max_value);
        try w.writeU32(self.grid_offset);
        try w.writeU32(self.grid_step_size);
        try self.distribution.encode(w);
    }
};

/// Wire type `BiomeDefinitionData`.
pub const BiomeDefinition = struct {
    id: u16,
    temperature: f32,
    downfall: f32,
    foliage_snow: f32,
    depth: f32,
    scale: f32,
    map_water_color_argb: i32,
    rain: bool,
    tags: ?codec.List(u16, codec.Prim(.u16le)),
    chunk_gen_data: ?BiomeDefinitionChunkGenData,

    pub fn decode(r: *Reader) DecodeError!BiomeDefinition {
        var value: BiomeDefinition = undefined;
        value.id = try r.readU16();
        value.temperature = try r.readF32();
        value.downfall = try r.readF32();
        value.foliage_snow = try r.readF32();
        value.depth = try r.readF32();
        value.scale = try r.readF32();
        value.map_water_color_argb = try r.readI32();
        value.rain = try r.readBool();
        value.tags = null;
        if (try r.readBool()) {
            var present: codec.List(u16, codec.Prim(.u16le)) = undefined;
            present = blk: {
                const count = try r.readCount(.var_u32);
                break :blk try codec.List(u16, codec.Prim(.u16le)).decode(r, count);
            };
            value.tags = present;
        }
        value.chunk_gen_data = if (try r.readBool()) try BiomeDefinitionChunkGenData.decode(r) else null;
        return value;
    }

    pub fn encode(self: BiomeDefinition, w: anytype) EncodeError!void {
        try w.writeU16(self.id);
        try w.writeF32(self.temperature);
        try w.writeF32(self.downfall);
        try w.writeF32(self.foliage_snow);
        try w.writeF32(self.depth);
        try w.writeF32(self.scale);
        try w.writeI32(self.map_water_color_argb);
        try w.writeBool(self.rain);
        try w.writeBool(self.tags != null);
        if (self.tags) |present| {
            try w.writeCount(.var_u32, present.len);
            try present.encode(w);
        }
        try w.writeBool(self.chunk_gen_data != null);
        if (self.chunk_gen_data) |present| {
            try present.encode(w);
        }
    }
};

/// Wire type `BiomeDefinitionChunkGenData`.
pub const BiomeDefinitionChunkGenData = struct {
    climate: ?BiomeClimate,
    consolidated_features: ?codec.List(BiomeConsolidatedFeature, BiomeConsolidatedFeature),
    mountain_params: ?BiomeMountainParameters,
    surface_material_adjustments: ?codec.List(BiomeElementData, BiomeElementData),
    overworld_gen_rules: ?BiomeOverworldGenRulesData,
    multinoise_gen_rules: ?BiomeMultiNoiseRules,
    legacy_world_gen_rules: ?codec.List(BiomeConditionalTransformation, BiomeConditionalTransformation),
    replacement_biomes: ?codec.List(BiomeReplacementData, BiomeReplacementData),
    village_type: ?VillageType,
    surface_builder_data: ?BiomeSurfaceBuilder,
    subsurface_builder_data: ?BiomeSurfaceBuilder,

    pub fn decode(r: *Reader) DecodeError!BiomeDefinitionChunkGenData {
        var value: BiomeDefinitionChunkGenData = undefined;
        value.climate = if (try r.readBool()) try BiomeClimate.decode(r) else null;
        value.consolidated_features = null;
        if (try r.readBool()) {
            var present: codec.List(BiomeConsolidatedFeature, BiomeConsolidatedFeature) = undefined;
            present = blk: {
                const count = try r.readCount(.var_u32);
                break :blk try codec.List(BiomeConsolidatedFeature, BiomeConsolidatedFeature).decode(r, count);
            };
            value.consolidated_features = present;
        }
        value.mountain_params = if (try r.readBool()) try BiomeMountainParameters.decode(r) else null;
        value.surface_material_adjustments = null;
        if (try r.readBool()) {
            var present: codec.List(BiomeElementData, BiomeElementData) = undefined;
            present = blk: {
                const count = try r.readCount(.var_u32);
                break :blk try codec.List(BiomeElementData, BiomeElementData).decode(r, count);
            };
            value.surface_material_adjustments = present;
        }
        value.overworld_gen_rules = if (try r.readBool()) try BiomeOverworldGenRulesData.decode(r) else null;
        value.multinoise_gen_rules = if (try r.readBool()) try BiomeMultiNoiseRules.decode(r) else null;
        value.legacy_world_gen_rules = null;
        if (try r.readBool()) {
            var present: codec.List(BiomeConditionalTransformation, BiomeConditionalTransformation) = undefined;
            present = blk: {
                const count = try r.readCount(.var_u32);
                break :blk try codec.List(BiomeConditionalTransformation, BiomeConditionalTransformation).decode(r, count);
            };
            value.legacy_world_gen_rules = present;
        }
        value.replacement_biomes = null;
        if (try r.readBool()) {
            var present: codec.List(BiomeReplacementData, BiomeReplacementData) = undefined;
            present = blk: {
                const count = try r.readCount(.var_u32);
                break :blk try codec.List(BiomeReplacementData, BiomeReplacementData).decode(r, count);
            };
            value.replacement_biomes = present;
        }
        value.village_type = if (try r.readBool()) try VillageType.decode(r) else null;
        value.surface_builder_data = if (try r.readBool()) try BiomeSurfaceBuilder.decode(r) else null;
        value.subsurface_builder_data = if (try r.readBool()) try BiomeSurfaceBuilder.decode(r) else null;
        return value;
    }

    pub fn encode(self: BiomeDefinitionChunkGenData, w: anytype) EncodeError!void {
        try w.writeBool(self.climate != null);
        if (self.climate) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.consolidated_features != null);
        if (self.consolidated_features) |present| {
            try w.writeCount(.var_u32, present.len);
            try present.encode(w);
        }
        try w.writeBool(self.mountain_params != null);
        if (self.mountain_params) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.surface_material_adjustments != null);
        if (self.surface_material_adjustments) |present| {
            try w.writeCount(.var_u32, present.len);
            try present.encode(w);
        }
        try w.writeBool(self.overworld_gen_rules != null);
        if (self.overworld_gen_rules) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.multinoise_gen_rules != null);
        if (self.multinoise_gen_rules) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.legacy_world_gen_rules != null);
        if (self.legacy_world_gen_rules) |present| {
            try w.writeCount(.var_u32, present.len);
            try present.encode(w);
        }
        try w.writeBool(self.replacement_biomes != null);
        if (self.replacement_biomes) |present| {
            try w.writeCount(.var_u32, present.len);
            try present.encode(w);
        }
        try w.writeBool(self.village_type != null);
        if (self.village_type) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.surface_builder_data != null);
        if (self.surface_builder_data) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.subsurface_builder_data != null);
        if (self.subsurface_builder_data) |present| {
            try present.encode(w);
        }
    }
};

/// Wire type `BiomeElementData`.
pub const BiomeElementData = struct {
    noise_freq_scale: f32,
    noise_lower_bound: f32,
    noise_upper_bound: f32,
    height_min_type: i32,
    height_min: u16,
    height_max_type: i32,
    height_max: u16,
    adjusted_materials: BiomeSurfaceMaterial,

    pub fn decode(r: *Reader) DecodeError!BiomeElementData {
        var value: BiomeElementData = undefined;
        value.noise_freq_scale = try r.readF32();
        value.noise_lower_bound = try r.readF32();
        value.noise_upper_bound = try r.readF32();
        value.height_min_type = try r.readVarI32();
        value.height_min = try r.readU16();
        value.height_max_type = try r.readVarI32();
        value.height_max = try r.readU16();
        value.adjusted_materials = try BiomeSurfaceMaterial.decode(r);
        return value;
    }

    pub fn encode(self: BiomeElementData, w: anytype) EncodeError!void {
        try w.writeF32(self.noise_freq_scale);
        try w.writeF32(self.noise_lower_bound);
        try w.writeF32(self.noise_upper_bound);
        try w.writeVarI32(self.height_min_type);
        try w.writeU16(self.height_min);
        try w.writeVarI32(self.height_max_type);
        try w.writeU16(self.height_max);
        try self.adjusted_materials.encode(w);
    }
};

/// Wire type `BiomeMesaSurfaceData`.
pub const BiomeMesaSurface = struct {
    clay_material: u32,
    hard_clay_material: u32,
    bryce_pillars: bool,
    has_forest: bool,

    pub fn decode(r: *Reader) DecodeError!BiomeMesaSurface {
        var value: BiomeMesaSurface = undefined;
        value.clay_material = try r.readU32();
        value.hard_clay_material = try r.readU32();
        value.bryce_pillars = try r.readBool();
        value.has_forest = try r.readBool();
        return value;
    }

    pub fn encode(self: BiomeMesaSurface, w: anytype) EncodeError!void {
        try w.writeU32(self.clay_material);
        try w.writeU32(self.hard_clay_material);
        try w.writeBool(self.bryce_pillars);
        try w.writeBool(self.has_forest);
    }
};

/// Wire type `BiomeMountainParamsData`.
pub const BiomeMountainParameters = struct {
    steep_block: u32,
    north_slopes: bool,
    south_slopes: bool,
    west_slopes: bool,
    east_slopes: bool,
    top_slide_enabled: bool,

    pub fn decode(r: *Reader) DecodeError!BiomeMountainParameters {
        var value: BiomeMountainParameters = undefined;
        value.steep_block = try r.readU32();
        value.north_slopes = try r.readBool();
        value.south_slopes = try r.readBool();
        value.west_slopes = try r.readBool();
        value.east_slopes = try r.readBool();
        value.top_slide_enabled = try r.readBool();
        return value;
    }

    pub fn encode(self: BiomeMountainParameters, w: anytype) EncodeError!void {
        try w.writeU32(self.steep_block);
        try w.writeBool(self.north_slopes);
        try w.writeBool(self.south_slopes);
        try w.writeBool(self.west_slopes);
        try w.writeBool(self.east_slopes);
        try w.writeBool(self.top_slide_enabled);
    }
};

/// Wire type `BiomeMultinoiseGenRulesData`.
pub const BiomeMultiNoiseRules = struct {
    temperature: f32,
    humidity: f32,
    altitude: f32,
    weirdness: f32,
    weight: f32,

    pub fn decode(r: *Reader) DecodeError!BiomeMultiNoiseRules {
        var value: BiomeMultiNoiseRules = undefined;
        value.temperature = try r.readF32();
        value.humidity = try r.readF32();
        value.altitude = try r.readF32();
        value.weirdness = try r.readF32();
        value.weight = try r.readF32();
        return value;
    }

    pub fn encode(self: BiomeMultiNoiseRules, w: anytype) EncodeError!void {
        try w.writeF32(self.temperature);
        try w.writeF32(self.humidity);
        try w.writeF32(self.altitude);
        try w.writeF32(self.weirdness);
        try w.writeF32(self.weight);
    }
};

/// Wire type `BiomeNoiseGradientSurfaceData`.
pub const BiomeNoiseGradientSurface = struct {
    non_replaceable_blocks: codec.List(u32, codec.Prim(.u32le)),
    gradient_blocks: codec.List(NoiseBlockSpecifier, NoiseBlockSpecifier),
    noise: NoiseDescriptor,

    pub fn decode(r: *Reader) DecodeError!BiomeNoiseGradientSurface {
        var value: BiomeNoiseGradientSurface = undefined;
        value.non_replaceable_blocks = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(u32, codec.Prim(.u32le)).decode(r, count);
        };
        value.gradient_blocks = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(NoiseBlockSpecifier, NoiseBlockSpecifier).decode(r, count);
        };
        value.noise = try NoiseDescriptor.decode(r);
        return value;
    }

    pub fn encode(self: BiomeNoiseGradientSurface, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.non_replaceable_blocks.len);
        try self.non_replaceable_blocks.encode(w);
        try w.writeCount(.var_u32, self.gradient_blocks.len);
        try self.gradient_blocks.encode(w);
        try self.noise.encode(w);
    }
};

/// Wire type `BiomeOverworldGenRulesData`.
pub const BiomeOverworldGenRulesData = struct {
    hills_transformations: codec.List(BiomeWeightedData, BiomeWeightedData),
    mutate_transformations: codec.List(BiomeWeightedData, BiomeWeightedData),
    river_transformations: codec.List(BiomeWeightedData, BiomeWeightedData),
    shore_transformations: codec.List(BiomeWeightedData, BiomeWeightedData),
    pre_hills_edge: codec.List(BiomeConditionalTransformation, BiomeConditionalTransformation),
    post_shore_edge: codec.List(BiomeConditionalTransformation, BiomeConditionalTransformation),
    climate: codec.List(BiomeTemperatureWeight, BiomeTemperatureWeight),

    pub fn decode(r: *Reader) DecodeError!BiomeOverworldGenRulesData {
        var value: BiomeOverworldGenRulesData = undefined;
        value.hills_transformations = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(BiomeWeightedData, BiomeWeightedData).decode(r, count);
        };
        value.mutate_transformations = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(BiomeWeightedData, BiomeWeightedData).decode(r, count);
        };
        value.river_transformations = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(BiomeWeightedData, BiomeWeightedData).decode(r, count);
        };
        value.shore_transformations = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(BiomeWeightedData, BiomeWeightedData).decode(r, count);
        };
        value.pre_hills_edge = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(BiomeConditionalTransformation, BiomeConditionalTransformation).decode(r, count);
        };
        value.post_shore_edge = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(BiomeConditionalTransformation, BiomeConditionalTransformation).decode(r, count);
        };
        value.climate = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(BiomeTemperatureWeight, BiomeTemperatureWeight).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: BiomeOverworldGenRulesData, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.hills_transformations.len);
        try self.hills_transformations.encode(w);
        try w.writeCount(.var_u32, self.mutate_transformations.len);
        try self.mutate_transformations.encode(w);
        try w.writeCount(.var_u32, self.river_transformations.len);
        try self.river_transformations.encode(w);
        try w.writeCount(.var_u32, self.shore_transformations.len);
        try self.shore_transformations.encode(w);
        try w.writeCount(.var_u32, self.pre_hills_edge.len);
        try self.pre_hills_edge.encode(w);
        try w.writeCount(.var_u32, self.post_shore_edge.len);
        try self.post_shore_edge.encode(w);
        try w.writeCount(.var_u32, self.climate.len);
        try self.climate.encode(w);
    }
};

/// Wire type `BiomeReplacementData`.
pub const BiomeReplacementData = struct {
    replacement_biome: u16,
    dimension: u16,
    target_biomes: codec.List(u16, codec.Prim(.u16le)),
    amount: f32,
    noise_frequency_scale: f32,
    replacement_index: u32,

    pub fn decode(r: *Reader) DecodeError!BiomeReplacementData {
        var value: BiomeReplacementData = undefined;
        value.replacement_biome = try r.readU16();
        value.dimension = try r.readU16();
        value.target_biomes = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(u16, codec.Prim(.u16le)).decode(r, count);
        };
        value.amount = try r.readF32();
        value.noise_frequency_scale = try r.readF32();
        value.replacement_index = try r.readU32();
        return value;
    }

    pub fn encode(self: BiomeReplacementData, w: anytype) EncodeError!void {
        try w.writeU16(self.replacement_biome);
        try w.writeU16(self.dimension);
        try w.writeCount(.var_u32, self.target_biomes.len);
        try self.target_biomes.encode(w);
        try w.writeF32(self.amount);
        try w.writeF32(self.noise_frequency_scale);
        try w.writeU32(self.replacement_index);
    }
};

/// Wire type `BiomeScatterParamData`.
pub const BiomeScatterParameter = struct {
    coordinates: codec.List(BiomeCoordinate, BiomeCoordinate),
    eval_order: CoordinateEvaluationOrder,
    chance_percent_type: i32,
    chance_percent: u16,
    chance_numerator: i32,
    chance_denominator: i32,
    iterations_type: i32,
    iterations: u16,

    pub fn decode(r: *Reader) DecodeError!BiomeScatterParameter {
        var value: BiomeScatterParameter = undefined;
        value.coordinates = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(BiomeCoordinate, BiomeCoordinate).decode(r, count);
        };
        value.eval_order = try CoordinateEvaluationOrder.decode(r);
        value.chance_percent_type = try r.readVarI32();
        value.chance_percent = try r.readU16();
        value.chance_numerator = try r.readI32();
        value.chance_denominator = try r.readI32();
        value.iterations_type = try r.readVarI32();
        value.iterations = try r.readU16();
        return value;
    }

    pub fn encode(self: BiomeScatterParameter, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.coordinates.len);
        try self.coordinates.encode(w);
        try self.eval_order.encode(w);
        try w.writeVarI32(self.chance_percent_type);
        try w.writeU16(self.chance_percent);
        try w.writeI32(self.chance_numerator);
        try w.writeI32(self.chance_denominator);
        try w.writeVarI32(self.iterations_type);
        try w.writeU16(self.iterations);
    }
};

/// Wire type `BiomeSurfaceBuilderData`.
pub const BiomeSurfaceBuilder = struct {
    surface_materials: ?BiomeSurfaceMaterial,
    has_default_overworld_surface: bool,
    has_swamp_surface: bool,
    has_frozen_ocean_surface: bool,
    has_the_end_surface: bool,
    mesa_surface: ?BiomeMesaSurface,
    capped_surface: ?BiomeCappedSurface,
    noise_gradient_surface: ?BiomeNoiseGradientSurface,

    pub fn decode(r: *Reader) DecodeError!BiomeSurfaceBuilder {
        var value: BiomeSurfaceBuilder = undefined;
        value.surface_materials = if (try r.readBool()) try BiomeSurfaceMaterial.decode(r) else null;
        value.has_default_overworld_surface = try r.readBool();
        value.has_swamp_surface = try r.readBool();
        value.has_frozen_ocean_surface = try r.readBool();
        value.has_the_end_surface = try r.readBool();
        value.mesa_surface = if (try r.readBool()) try BiomeMesaSurface.decode(r) else null;
        value.capped_surface = if (try r.readBool()) try BiomeCappedSurface.decode(r) else null;
        value.noise_gradient_surface = if (try r.readBool()) try BiomeNoiseGradientSurface.decode(r) else null;
        return value;
    }

    pub fn encode(self: BiomeSurfaceBuilder, w: anytype) EncodeError!void {
        try w.writeBool(self.surface_materials != null);
        if (self.surface_materials) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.has_default_overworld_surface);
        try w.writeBool(self.has_swamp_surface);
        try w.writeBool(self.has_frozen_ocean_surface);
        try w.writeBool(self.has_the_end_surface);
        try w.writeBool(self.mesa_surface != null);
        if (self.mesa_surface) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.capped_surface != null);
        if (self.capped_surface) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.noise_gradient_surface != null);
        if (self.noise_gradient_surface) |present| {
            try present.encode(w);
        }
    }
};

/// Wire type `BiomeSurfaceMaterialData`.
pub const BiomeSurfaceMaterial = struct {
    top_block: u32,
    mid_block: u32,
    sea_floor_block: u32,
    foundation_block: u32,
    sea_block: u32,
    sea_floor_depth: i32,

    pub fn decode(r: *Reader) DecodeError!BiomeSurfaceMaterial {
        var value: BiomeSurfaceMaterial = undefined;
        value.top_block = try r.readU32();
        value.mid_block = try r.readU32();
        value.sea_floor_block = try r.readU32();
        value.foundation_block = try r.readU32();
        value.sea_block = try r.readU32();
        value.sea_floor_depth = try r.readI32();
        return value;
    }

    pub fn encode(self: BiomeSurfaceMaterial, w: anytype) EncodeError!void {
        try w.writeU32(self.top_block);
        try w.writeU32(self.mid_block);
        try w.writeU32(self.sea_floor_block);
        try w.writeU32(self.foundation_block);
        try w.writeU32(self.sea_block);
        try w.writeI32(self.sea_floor_depth);
    }
};

/// Wire type `BiomeWeightedTemperatureData`.
pub const BiomeTemperatureWeight = struct {
    temperature: i32,
    weight: u32,

    pub fn decode(r: *Reader) DecodeError!BiomeTemperatureWeight {
        var value: BiomeTemperatureWeight = undefined;
        value.temperature = try r.readVarI32();
        value.weight = try r.readU32();
        return value;
    }

    pub fn encode(self: BiomeTemperatureWeight, w: anytype) EncodeError!void {
        try w.writeVarI32(self.temperature);
        try w.writeU32(self.weight);
    }
};

/// Wire type `BiomeWeightedData`.
pub const BiomeWeightedData = struct {
    biome_identifier: u16,
    weight: u32,

    pub fn decode(r: *Reader) DecodeError!BiomeWeightedData {
        var value: BiomeWeightedData = undefined;
        value.biome_identifier = try r.readU16();
        value.weight = try r.readU32();
        return value;
    }

    pub fn encode(self: BiomeWeightedData, w: anytype) EncodeError!void {
        try w.writeU16(self.biome_identifier);
        try w.writeU32(self.weight);
    }
};

/// Wire type `SharedTypes::v1_21_10::CoordinateEvaluationOrder`.
pub const CoordinateEvaluationOrder = enum(i32) {
    xyz = 0,
    xzy = 1,
    yxz = 2,
    yzx = 3,
    zxy = 4,
    zyx = 5,
    _,

    pub fn decode(r: *Reader) DecodeError!CoordinateEvaluationOrder {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: CoordinateEvaluationOrder, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

/// Wire type `SharedTypes::FloatRange`.
pub const FloatRange = struct {
    min: f32,
    max: f32,

    pub fn decode(r: *Reader) DecodeError!FloatRange {
        var value: FloatRange = undefined;
        value.min = try r.readF32();
        value.max = try r.readF32();
        return value;
    }

    pub fn encode(self: FloatRange, w: anytype) EncodeError!void {
        try w.writeF32(self.min);
        try w.writeF32(self.max);
    }
};

/// Wire type `SerializedNoiseBlockSpecifier`.
pub const NoiseBlockSpecifier = struct {
    noise: []const u8,
    threshold: f32,
    range: FloatRange,
    block: u32,

    pub fn decode(r: *Reader) DecodeError!NoiseBlockSpecifier {
        var value: NoiseBlockSpecifier = undefined;
        value.noise = try r.readString();
        value.threshold = try r.readF32();
        value.range = try FloatRange.decode(r);
        value.block = try r.readU32();
        return value;
    }

    pub fn encode(self: NoiseBlockSpecifier, w: anytype) EncodeError!void {
        try w.writeString(self.noise);
        try w.writeF32(self.threshold);
        try self.range.encode(w);
        try w.writeU32(self.block);
    }
};

/// Wire type `SharedTypes::v1_26_30::NoiseDescriptor`.
pub const NoiseDescriptor = struct {
    name: []const u8,
    first_octave: i32,
    amplitudes: codec.List(f32, codec.Prim(.f32le)),

    pub fn decode(r: *Reader) DecodeError!NoiseDescriptor {
        var value: NoiseDescriptor = undefined;
        value.name = try r.readString();
        value.first_octave = try r.readI32();
        value.amplitudes = blk: {
            const count = try r.readCount(.var_u32);
            if (count < 1) return error.InvalidValue;
            if (count > 100) return error.InvalidValue;
            break :blk try codec.List(f32, codec.Prim(.f32le)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: NoiseDescriptor, w: anytype) EncodeError!void {
        try w.writeString(self.name);
        try w.writeI32(self.first_octave);
        if (self.amplitudes.len < 1) return error.InvalidValue;
        if (self.amplitudes.len > 100) return error.InvalidValue;
        try w.writeCount(.var_u32, self.amplitudes.len);
        try self.amplitudes.encode(w);
    }
};

/// Wire type `SharedTypes::v1_21_10::RandomDistributionType`.
pub const RandomDistributionType = enum(i32) {
    singlevalued = 0,
    uniform = 1,
    gaussian = 2,
    inversegaussian = 3,
    fixedgrid = 4,
    jitteredgrid = 5,
    triangle = 6,
    _,

    pub fn decode(r: *Reader) DecodeError!RandomDistributionType {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: RandomDistributionType, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

/// Wire type `SharedTypes::VillageType`.
pub const VillageType = enum(u8) {
    desert = 0,
    ice = 1,
    savanna = 2,
    taiga = 3,
    default = 4,
    _,

    pub fn decode(r: *Reader) DecodeError!VillageType {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: VillageType, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

pub const PacketMapOfBiomeNamesToDataEntry = struct {
    key: u16,
    value: BiomeDefinition,

    pub fn decode(r: *Reader) DecodeError!PacketMapOfBiomeNamesToDataEntry {
        var value: PacketMapOfBiomeNamesToDataEntry = undefined;
        value.key = try r.readU16();
        value.value = try BiomeDefinition.decode(r);
        return value;
    }

    pub fn encode(self: PacketMapOfBiomeNamesToDataEntry, w: anytype) EncodeError!void {
        try w.writeU16(self.key);
        try self.value.encode(w);
    }
};
