//! BlockActorDataPacket (ID 56), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    block_position: codec.BlockPosition,
    actor_data_tags: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.block_position = try r.readBlockPosition();
        value.actor_data_tags = try r.readNbt();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeBlockPosition(self.block_position);
        try w.writeNbt(self.actor_data_tags);
    }
};
