//! BlockPickRequestPacket (ID 34), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    position: codec.BlockPosition,
    with_data: bool,
    max_slots: u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.position = try r.readBlockPosition();
        value.with_data = try r.readBool();
        value.max_slots = try r.readU8();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeBlockPosition(self.position);
        try w.writeBool(self.with_data);
        try w.writeU8(self.max_slots);
    }
};
