//! CameraAimAssistPresetsPacket (ID 320), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    camera_aim_assist_presets: codec.List(CameraAimAssistCategory, CameraAimAssistCategory),
    camera_aim_assist_categories: codec.List(CameraAimAssistPresetDefinition, CameraAimAssistPresetDefinition),
    operation: CameraAimAssistPresetOperation,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.camera_aim_assist_presets = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraAimAssistCategory, CameraAimAssistCategory).decode(r, count);
        };
        value.camera_aim_assist_categories = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraAimAssistPresetDefinition, CameraAimAssistPresetDefinition).decode(r, count);
        };
        value.operation = try CameraAimAssistPresetOperation.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.camera_aim_assist_presets.len);
        try self.camera_aim_assist_presets.encode(w);
        try w.writeCount(.var_u32, self.camera_aim_assist_categories.len);
        try self.camera_aim_assist_categories.encode(w);
        try self.operation.encode(w);
    }
};

/// Wire type `SharedTypes::v1_21_50::CameraAimAssistCategoryDefinition`.
pub const CameraAimAssistCategory = struct {
    name: []const u8,
    priorities: CameraAimAssistPriorities,

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistCategory {
        var value: CameraAimAssistCategory = undefined;
        value.name = try r.readString();
        value.priorities = try CameraAimAssistPriorities.decode(r);
        return value;
    }

    pub fn encode(self: CameraAimAssistCategory, w: anytype) EncodeError!void {
        try w.writeString(self.name);
        try self.priorities.encode(w);
    }
};

/// Wire type `SharedTypes::v1_21_120::CameraAimAssistPresetDefinition`.
pub const CameraAimAssistPresetDefinition = struct {
    identifier: []const u8,
    exclusion_settings: CameraAimAssistPresetExclusionDefinition,
    liquid_targeting_list: codec.List([]const u8, codec.Prim(.string)),
    item_settings: codec.List(CameraAimAssistPresetDefinitionItemSettingsEntry, CameraAimAssistPresetDefinitionItemSettingsEntry),
    default_item_settings: ?[]const u8,
    hand_settings: ?[]const u8,

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistPresetDefinition {
        var value: CameraAimAssistPresetDefinition = undefined;
        value.identifier = try r.readString();
        value.exclusion_settings = try CameraAimAssistPresetExclusionDefinition.decode(r);
        value.liquid_targeting_list = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        value.item_settings = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraAimAssistPresetDefinitionItemSettingsEntry, CameraAimAssistPresetDefinitionItemSettingsEntry).decode(r, count);
        };
        value.default_item_settings = if (try r.readBool()) try r.readString() else null;
        value.hand_settings = if (try r.readBool()) try r.readString() else null;
        return value;
    }

    pub fn encode(self: CameraAimAssistPresetDefinition, w: anytype) EncodeError!void {
        try w.writeString(self.identifier);
        try self.exclusion_settings.encode(w);
        try w.writeCount(.var_u32, self.liquid_targeting_list.len);
        try self.liquid_targeting_list.encode(w);
        try w.writeCount(.var_u32, self.item_settings.len);
        try self.item_settings.encode(w);
        try w.writeBool(self.default_item_settings != null);
        if (self.default_item_settings) |present| {
            try w.writeString(present);
        }
        try w.writeBool(self.hand_settings != null);
        if (self.hand_settings) |present| {
            try w.writeString(present);
        }
    }
};

/// Wire type `SharedTypes::v1_21_120::CameraAimAssistPresetExclusionDefinition`.
pub const CameraAimAssistPresetExclusionDefinition = struct {
    blocks: codec.List([]const u8, codec.Prim(.string)),
    entities: codec.List([]const u8, codec.Prim(.string)),
    block_tags: codec.List([]const u8, codec.Prim(.string)),
    entity_type_families: codec.List([]const u8, codec.Prim(.string)),

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistPresetExclusionDefinition {
        var value: CameraAimAssistPresetExclusionDefinition = undefined;
        value.blocks = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        value.entities = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        value.block_tags = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        value.entity_type_families = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: CameraAimAssistPresetExclusionDefinition, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.blocks.len);
        try self.blocks.encode(w);
        try w.writeCount(.var_u32, self.entities.len);
        try self.entities.encode(w);
        try w.writeCount(.var_u32, self.block_tags.len);
        try self.block_tags.encode(w);
        try w.writeCount(.var_u32, self.entity_type_families.len);
        try self.entity_type_families.encode(w);
    }
};

/// Wire type `CameraAimAssistPresetsPacketOperation`.
pub const CameraAimAssistPresetOperation = enum(u8) {
    set = 0,
    addtoexisting = 1,
    _,

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistPresetOperation {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: CameraAimAssistPresetOperation, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `SharedTypes::v1_21_50::CameraAimAssistCategoryPriorities`.
pub const CameraAimAssistPriorities = struct {
    entities: codec.List(CameraAimAssistPrioritiesEntitiesEntry, CameraAimAssistPrioritiesEntitiesEntry),
    blocks: codec.List(CameraAimAssistPrioritiesBlocksEntry, CameraAimAssistPrioritiesBlocksEntry),
    block_tags: codec.List(CameraAimAssistPrioritiesBlockTagsEntry, CameraAimAssistPrioritiesBlockTagsEntry),
    entity_type_families: codec.List(CameraAimAssistPrioritiesEntityTypeFamiliesEntry, CameraAimAssistPrioritiesEntityTypeFamiliesEntry),
    entity_default: ?i32,
    block_default: ?i32,

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistPriorities {
        var value: CameraAimAssistPriorities = undefined;
        value.entities = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraAimAssistPrioritiesEntitiesEntry, CameraAimAssistPrioritiesEntitiesEntry).decode(r, count);
        };
        value.blocks = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraAimAssistPrioritiesBlocksEntry, CameraAimAssistPrioritiesBlocksEntry).decode(r, count);
        };
        value.block_tags = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraAimAssistPrioritiesBlockTagsEntry, CameraAimAssistPrioritiesBlockTagsEntry).decode(r, count);
        };
        value.entity_type_families = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraAimAssistPrioritiesEntityTypeFamiliesEntry, CameraAimAssistPrioritiesEntityTypeFamiliesEntry).decode(r, count);
        };
        value.entity_default = null;
        if (try r.readBool()) {
            var present: i32 = undefined;
            present = try r.readI32();
            if (present < 0) return error.InvalidValue;
            if (present > 100) return error.InvalidValue;
            value.entity_default = present;
        }
        value.block_default = null;
        if (try r.readBool()) {
            var present: i32 = undefined;
            present = try r.readI32();
            if (present < 0) return error.InvalidValue;
            if (present > 100) return error.InvalidValue;
            value.block_default = present;
        }
        return value;
    }

    pub fn encode(self: CameraAimAssistPriorities, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.entities.len);
        try self.entities.encode(w);
        try w.writeCount(.var_u32, self.blocks.len);
        try self.blocks.encode(w);
        try w.writeCount(.var_u32, self.block_tags.len);
        try self.block_tags.encode(w);
        try w.writeCount(.var_u32, self.entity_type_families.len);
        try self.entity_type_families.encode(w);
        try w.writeBool(self.entity_default != null);
        if (self.entity_default) |present| {
            if (present < 0) return error.InvalidValue;
            if (present > 100) return error.InvalidValue;
            try w.writeI32(present);
        }
        try w.writeBool(self.block_default != null);
        if (self.block_default) |present| {
            if (present < 0) return error.InvalidValue;
            if (present > 100) return error.InvalidValue;
            try w.writeI32(present);
        }
    }
};

pub const CameraAimAssistPresetDefinitionItemSettingsEntry = struct {
    key: []const u8,
    value: []const u8,

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistPresetDefinitionItemSettingsEntry {
        var value: CameraAimAssistPresetDefinitionItemSettingsEntry = undefined;
        value.key = try r.readString();
        value.value = try r.readString();
        return value;
    }

    pub fn encode(self: CameraAimAssistPresetDefinitionItemSettingsEntry, w: anytype) EncodeError!void {
        try w.writeString(self.key);
        try w.writeString(self.value);
    }
};

pub const CameraAimAssistPrioritiesEntitiesEntry = struct {
    key: []const u8,
    value: i32,

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistPrioritiesEntitiesEntry {
        var value: CameraAimAssistPrioritiesEntitiesEntry = undefined;
        value.key = try r.readString();
        value.value = try r.readI32();
        if (value.value < 0) return error.InvalidValue;
        if (value.value > 100) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: CameraAimAssistPrioritiesEntitiesEntry, w: anytype) EncodeError!void {
        try w.writeString(self.key);
        if (self.value < 0) return error.InvalidValue;
        if (self.value > 100) return error.InvalidValue;
        try w.writeI32(self.value);
    }
};

pub const CameraAimAssistPrioritiesBlocksEntry = struct {
    key: []const u8,
    value: i32,

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistPrioritiesBlocksEntry {
        var value: CameraAimAssistPrioritiesBlocksEntry = undefined;
        value.key = try r.readString();
        value.value = try r.readI32();
        if (value.value < 0) return error.InvalidValue;
        if (value.value > 100) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: CameraAimAssistPrioritiesBlocksEntry, w: anytype) EncodeError!void {
        try w.writeString(self.key);
        if (self.value < 0) return error.InvalidValue;
        if (self.value > 100) return error.InvalidValue;
        try w.writeI32(self.value);
    }
};

pub const CameraAimAssistPrioritiesBlockTagsEntry = struct {
    key: []const u8,
    value: i32,

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistPrioritiesBlockTagsEntry {
        var value: CameraAimAssistPrioritiesBlockTagsEntry = undefined;
        value.key = try r.readString();
        value.value = try r.readI32();
        if (value.value < 0) return error.InvalidValue;
        if (value.value > 100) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: CameraAimAssistPrioritiesBlockTagsEntry, w: anytype) EncodeError!void {
        try w.writeString(self.key);
        if (self.value < 0) return error.InvalidValue;
        if (self.value > 100) return error.InvalidValue;
        try w.writeI32(self.value);
    }
};

pub const CameraAimAssistPrioritiesEntityTypeFamiliesEntry = struct {
    key: []const u8,
    value: i32,

    pub fn decode(r: *Reader) DecodeError!CameraAimAssistPrioritiesEntityTypeFamiliesEntry {
        var value: CameraAimAssistPrioritiesEntityTypeFamiliesEntry = undefined;
        value.key = try r.readString();
        value.value = try r.readI32();
        if (value.value < 0) return error.InvalidValue;
        if (value.value > 100) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: CameraAimAssistPrioritiesEntityTypeFamiliesEntry, w: anytype) EncodeError!void {
        try w.writeString(self.key);
        if (self.value < 0) return error.InvalidValue;
        if (self.value > 100) return error.InvalidValue;
        try w.writeI32(self.value);
    }
};
