//! CameraPacket (ID 73), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    camera_id: i64,
    target_player_id: i64,

    pub const actor_refs = .{
        .camera_id = codec.ActorRef.unique,
        .target_player_id = codec.ActorRef.unique,
    };

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.camera_id = try r.readVarI64();
        value.target_player_id = try r.readVarI64();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI64(self.camera_id);
        try w.writeVarI64(self.target_player_id);
    }
};
