//! CameraSplinePacket (ID 338), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    camera_data_splines: codec.List(CameraSplineDefinition, CameraSplineDefinition),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.camera_data_splines = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraSplineDefinition, CameraSplineDefinition).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.camera_data_splines.len);
        try self.camera_data_splines.encode(w);
    }
};

/// Wire type `SharedTypes::v1_26_0::CameraSplineDefinition`.
pub const CameraSplineDefinition = struct {
    name: []const u8,
    total_time: f32,
    spline_type: []const u8,
    control_points: codec.List(codec.Vec3f, codec.Prim(.vec3f)),
    progress_key_frames: codec.List(CameraSplineProgressKeyFrame, CameraSplineProgressKeyFrame),
    rotation_key_frames: codec.List(CameraSplineRotationKeyFrame, CameraSplineRotationKeyFrame),

    pub fn decode(r: *Reader) DecodeError!CameraSplineDefinition {
        var value: CameraSplineDefinition = undefined;
        value.name = try r.readString();
        if (!codec.patterns.namespacedWord(value.name)) return error.InvalidValue;
        value.total_time = try r.readF32();
        if (!(value.total_time >= 0)) return error.InvalidValue;
        value.spline_type = try r.readString();
        if (!codec.patterns.splineType(value.spline_type)) return error.InvalidValue;
        value.control_points = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(codec.Vec3f, codec.Prim(.vec3f)).decode(r, count);
        };
        value.progress_key_frames = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraSplineProgressKeyFrame, CameraSplineProgressKeyFrame).decode(r, count);
        };
        value.rotation_key_frames = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(CameraSplineRotationKeyFrame, CameraSplineRotationKeyFrame).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: CameraSplineDefinition, w: anytype) EncodeError!void {
        if (!codec.patterns.namespacedWord(self.name)) return error.InvalidValue;
        try w.writeString(self.name);
        if (!(self.total_time >= 0)) return error.InvalidValue;
        try w.writeF32(self.total_time);
        if (!codec.patterns.splineType(self.spline_type)) return error.InvalidValue;
        try w.writeString(self.spline_type);
        try w.writeCount(.var_u32, self.control_points.len);
        try self.control_points.encode(w);
        try w.writeCount(.var_u32, self.progress_key_frames.len);
        try self.progress_key_frames.encode(w);
        try w.writeCount(.var_u32, self.rotation_key_frames.len);
        try self.rotation_key_frames.encode(w);
    }
};

/// Wire type `SharedTypes::v1_26_0::CameraSplineProgressKeyFrame`.
pub const CameraSplineProgressKeyFrame = struct {
    progress: f32,
    time: f32,
    easing: ?[]const u8,

    pub fn decode(r: *Reader) DecodeError!CameraSplineProgressKeyFrame {
        var value: CameraSplineProgressKeyFrame = undefined;
        value.progress = try r.readF32();
        if (!(value.progress >= 0)) return error.InvalidValue;
        if (!(value.progress <= 1)) return error.InvalidValue;
        value.time = try r.readF32();
        if (!(value.time >= 0)) return error.InvalidValue;
        value.easing = if (try r.readBool()) try r.readString() else null;
        return value;
    }

    pub fn encode(self: CameraSplineProgressKeyFrame, w: anytype) EncodeError!void {
        if (!(self.progress >= 0)) return error.InvalidValue;
        if (!(self.progress <= 1)) return error.InvalidValue;
        try w.writeF32(self.progress);
        if (!(self.time >= 0)) return error.InvalidValue;
        try w.writeF32(self.time);
        try w.writeBool(self.easing != null);
        if (self.easing) |present| {
            try w.writeString(present);
        }
    }
};

/// Wire type `SharedTypes::v1_26_0::CameraSplineRotationKeyFrame`.
pub const CameraSplineRotationKeyFrame = struct {
    rotation: codec.Vec3f,
    time: f32,
    easing: ?[]const u8,

    pub fn decode(r: *Reader) DecodeError!CameraSplineRotationKeyFrame {
        var value: CameraSplineRotationKeyFrame = undefined;
        value.rotation = try r.readVec3f();
        value.time = try r.readF32();
        if (!(value.time >= 0)) return error.InvalidValue;
        value.easing = if (try r.readBool()) try r.readString() else null;
        return value;
    }

    pub fn encode(self: CameraSplineRotationKeyFrame, w: anytype) EncodeError!void {
        try w.writeVec3f(self.rotation);
        if (!(self.time >= 0)) return error.InvalidValue;
        try w.writeF32(self.time);
        try w.writeBool(self.easing != null);
        if (self.easing) |present| {
            try w.writeString(present);
        }
    }
};
