//! ClientboundDebugRendererPacket (ID 164), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    type: []const u8,
    debug_marker_data: ?ClientboundDebugRendererDebugMarkerData,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.type = try r.readString();
        value.debug_marker_data = if (try r.readBool()) try ClientboundDebugRendererDebugMarkerData.decode(r) else null;
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeString(self.type);
        try w.writeBool(self.debug_marker_data != null);
        if (self.debug_marker_data) |present| {
            try present.encode(w);
        }
    }
};

/// Wire type `ClientboundDebugRendererPacketPayload::DebugMarkerData`.
pub const ClientboundDebugRendererDebugMarkerData = struct {
    text: []const u8,
    position: codec.Vec3f,
    color: i32,
    duration: u64,

    pub fn decode(r: *Reader) DecodeError!ClientboundDebugRendererDebugMarkerData {
        var value: ClientboundDebugRendererDebugMarkerData = undefined;
        value.text = try r.readString();
        if (value.text.len > 4096) return error.InvalidValue;
        value.position = try r.readVec3f();
        value.color = try r.readI32();
        value.duration = try r.readU64();
        return value;
    }

    pub fn encode(self: ClientboundDebugRendererDebugMarkerData, w: anytype) EncodeError!void {
        if (self.text.len > 4096) return error.InvalidValue;
        try w.writeString(self.text);
        try w.writeVec3f(self.position);
        try w.writeI32(self.color);
        try w.writeU64(self.duration);
    }
};
