//! ClientboundUpdateSoundDataPacket (ID 348), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    server_sound_handle: u64,
    stop: SoundDataEvent,
    set_volume: SoundDataEvent,
    set_pitch: SoundDataEvent,
    fade: SoundDataEvent,
    seek_to: SoundDataEvent,
    pause: SoundDataEvent,
    @"resume": SoundDataEvent,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.server_sound_handle = try r.readU64();
        value.stop = try SoundDataEvent.decode(r);
        value.set_volume = try SoundDataEvent.decode(r);
        value.set_pitch = try SoundDataEvent.decode(r);
        value.fade = try SoundDataEvent.decode(r);
        value.seek_to = try SoundDataEvent.decode(r);
        value.pause = try SoundDataEvent.decode(r);
        value.@"resume" = try SoundDataEvent.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeU64(self.server_sound_handle);
        try self.stop.encode(w);
        try self.set_volume.encode(w);
        try self.set_pitch.encode(w);
        try self.fade.encode(w);
        try self.seek_to.encode(w);
        try self.pause.encode(w);
        try self.@"resume".encode(w);
    }
};

pub const SoundDataEvent = union(enum(u32)) {
    stop: SoundDataEventStop,
    set_volume: f32,
    set_pitch: f32,
    fade: SoundDataEventFade,
    seek_to: f32,
    pause: SoundDataEventPause,
    @"resume": SoundDataEventResume,

    pub fn decode(r: *Reader) DecodeError!SoundDataEvent {
        switch (try r.readVarU32()) {
            0 => return .{ .stop = try SoundDataEventStop.decode(r) },
            1 => return .{ .set_volume = try r.readF32() },
            2 => return .{ .set_pitch = try r.readF32() },
            3 => return .{ .fade = try SoundDataEventFade.decode(r) },
            4 => return .{ .seek_to = try r.readF32() },
            5 => return .{ .pause = try SoundDataEventPause.decode(r) },
            6 => return .{ .@"resume" = try SoundDataEventResume.decode(r) },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: SoundDataEvent, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .stop => |value| {
                try value.encode(w);
            },
            .set_volume => |value| {
                try w.writeF32(value);
            },
            .set_pitch => |value| {
                try w.writeF32(value);
            },
            .fade => |value| {
                try value.encode(w);
            },
            .seek_to => |value| {
                try w.writeF32(value);
            },
            .pause => |value| {
                try value.encode(w);
            },
            .@"resume" => |value| {
                try value.encode(w);
            },
        }
    }
};

/// Wire type `SoundDataEvent::Fade`.
pub const SoundDataEventFade = struct {
    duration: f32,
    target_volume: f32,

    pub fn decode(r: *Reader) DecodeError!SoundDataEventFade {
        var value: SoundDataEventFade = undefined;
        value.duration = try r.readF32();
        value.target_volume = try r.readF32();
        return value;
    }

    pub fn encode(self: SoundDataEventFade, w: anytype) EncodeError!void {
        try w.writeF32(self.duration);
        try w.writeF32(self.target_volume);
    }
};

/// Wire type `SoundDataEvent::Pause`.
pub const SoundDataEventPause = struct {
    pub fn decode(r: *Reader) DecodeError!SoundDataEventPause {
        _ = r;
        return .{};
    }

    pub fn encode(self: SoundDataEventPause, w: anytype) EncodeError!void {
        _ = self;
        _ = w;
    }
};

/// Wire type `SoundDataEvent::Resume`.
pub const SoundDataEventResume = struct {
    pub fn decode(r: *Reader) DecodeError!SoundDataEventResume {
        _ = r;
        return .{};
    }

    pub fn encode(self: SoundDataEventResume, w: anytype) EncodeError!void {
        _ = self;
        _ = w;
    }
};

/// Wire type `SoundDataEvent::Stop`.
pub const SoundDataEventStop = struct {
    pub fn decode(r: *Reader) DecodeError!SoundDataEventStop {
        _ = r;
        return .{};
    }

    pub fn encode(self: SoundDataEventStop, w: anytype) EncodeError!void {
        _ = self;
        _ = w;
    }
};
