//! ClientCacheMissResponsePacket (ID 136), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    missing_blobs: codec.List(MissingBlobData, MissingBlobData),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.missing_blobs = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 4095) return error.InvalidValue;
            break :blk try codec.List(MissingBlobData, MissingBlobData).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        if (self.missing_blobs.len > 4095) return error.InvalidValue;
        try w.writeCount(.var_u32, self.missing_blobs.len);
        try self.missing_blobs.encode(w);
    }
};

/// Wire type `MissingBlobData`.
pub const MissingBlobData = struct {
    blob_id: u64,
    blob_data: []const u8,

    pub fn decode(r: *Reader) DecodeError!MissingBlobData {
        var value: MissingBlobData = undefined;
        value.blob_id = try r.readU64();
        value.blob_data = try r.readByteArray();
        return value;
    }

    pub fn encode(self: MissingBlobData, w: anytype) EncodeError!void {
        try w.writeU64(self.blob_id);
        try w.writeByteArray(self.blob_data);
    }
};
