//! ClientCacheBlobStatusPacket (ID 135), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    missing_ids: codec.List(u64, codec.Prim(.u64le)),
    found_ids: codec.List(u64, codec.Prim(.u64le)),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.missing_ids = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 4095) return error.InvalidValue;
            break :blk try codec.List(u64, codec.Prim(.u64le)).decode(r, count);
        };
        value.found_ids = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 4095) return error.InvalidValue;
            break :blk try codec.List(u64, codec.Prim(.u64le)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        if (self.missing_ids.len > 4095) return error.InvalidValue;
        try w.writeCount(.var_u32, self.missing_ids.len);
        try self.missing_ids.encode(w);
        if (self.found_ids.len > 4095) return error.InvalidValue;
        try w.writeCount(.var_u32, self.found_ids.len);
        try self.found_ids.encode(w);
    }
};
