//! CodeBuilderSourcePacket (ID 178), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    operation: CodeBuilderStorageQueryOptionsOperation,
    category: CodeBuilderStorageQueryOptionsCategory,
    code_status: CodeBuilderExecutionStateCodeStatus,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.operation = try CodeBuilderStorageQueryOptionsOperation.decode(r);
        value.category = try CodeBuilderStorageQueryOptionsCategory.decode(r);
        value.code_status = try CodeBuilderExecutionStateCodeStatus.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.operation.encode(w);
        try self.category.encode(w);
        try self.code_status.encode(w);
    }
};

/// Wire type `CodeBuilderExecutionState::CodeStatus`.
pub const CodeBuilderExecutionStateCodeStatus = enum(u8) {
    none = 0,
    notstarted = 1,
    inprogress = 2,
    paused = 3,
    @"error" = 4,
    succeeded = 5,
    _,

    pub fn decode(r: *Reader) DecodeError!CodeBuilderExecutionStateCodeStatus {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: CodeBuilderExecutionStateCodeStatus, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `CodeBuilderStorageQueryOptions::Category`.
pub const CodeBuilderStorageQueryOptionsCategory = enum(u8) {
    none = 0,
    codestatus = 1,
    instantiation = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!CodeBuilderStorageQueryOptionsCategory {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: CodeBuilderStorageQueryOptionsCategory, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `CodeBuilderStorageQueryOptions::Operation`.
pub const CodeBuilderStorageQueryOptionsOperation = enum(u8) {
    none = 0,
    get = 1,
    set = 2,
    reset = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!CodeBuilderStorageQueryOptionsOperation {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: CodeBuilderStorageQueryOptionsOperation, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};
