//! CompletedUsingItemPacket (ID 142), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    item_id: i16,
    item_use_method: i32,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.item_id = try r.readI16();
        value.item_use_method = try r.readI32();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeI16(self.item_id);
        try w.writeI32(self.item_use_method);
    }
};
