//! ContainerRegistryCleanupPacket (ID 317), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    removed_containers: codec.List(types.FullContainerName, types.FullContainerName),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.removed_containers = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(types.FullContainerName, types.FullContainerName).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.removed_containers.len);
        try self.removed_containers.encode(w);
    }
};
