//! DeathInfoPacket (ID 189), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    death_cause_attack_name: []const u8,
    death_cause_message_list: codec.List([]const u8, codec.Prim(.string)),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.death_cause_attack_name = try r.readString();
        value.death_cause_message_list = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeString(self.death_cause_attack_name);
        try w.writeCount(.var_u32, self.death_cause_message_list.len);
        try self.death_cause_message_list.encode(w);
    }
};
