//! DimensionDataPacket (ID 180), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    definitions: codec.List(PacketDefinitionsEntry, PacketDefinitionsEntry),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.definitions = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(PacketDefinitionsEntry, PacketDefinitionsEntry).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.definitions.len);
        try self.definitions.encode(w);
    }
};

/// Wire type `DimensionDefinitionGroup::DimensionDefinition`.
pub const DimensionDefinitionGroupDimensionDefinition = struct {
    minimum_y: i32,
    height_range: i32,
    generator_type: types.GeneratorType,
    dimension_type: i32,
    pack_id: [16]u8,
    default_biome: []const u8,

    pub fn decode(r: *Reader) DecodeError!DimensionDefinitionGroupDimensionDefinition {
        var value: DimensionDefinitionGroupDimensionDefinition = undefined;
        value.minimum_y = try r.readVarI32();
        value.height_range = try r.readVarI32();
        value.generator_type = try types.GeneratorType.decode(r);
        value.dimension_type = try r.readVarI32();
        value.pack_id = try r.readUuid();
        value.default_biome = try r.readString();
        if (value.default_biome.len > 256) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: DimensionDefinitionGroupDimensionDefinition, w: anytype) EncodeError!void {
        try w.writeVarI32(self.minimum_y);
        try w.writeVarI32(self.height_range);
        try self.generator_type.encode(w);
        try w.writeVarI32(self.dimension_type);
        try w.writeUuid(self.pack_id);
        if (self.default_biome.len > 256) return error.InvalidValue;
        try w.writeString(self.default_biome);
    }
};

pub const PacketDefinitionsEntry = struct {
    key: []const u8,
    value: DimensionDefinitionGroupDimensionDefinition,

    pub fn decode(r: *Reader) DecodeError!PacketDefinitionsEntry {
        var value: PacketDefinitionsEntry = undefined;
        value.key = try r.readString();
        if (value.key.len > 256) return error.InvalidValue;
        value.value = try DimensionDefinitionGroupDimensionDefinition.decode(r);
        return value;
    }

    pub fn encode(self: PacketDefinitionsEntry, w: anytype) EncodeError!void {
        if (self.key.len > 256) return error.InvalidValue;
        try w.writeString(self.key);
        try self.value.encode(w);
    }
};
