//! EduUriResourcePacket (ID 170), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    edu_shared_uri_resource: types.EducationSharedResourceURI,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.edu_shared_uri_resource = try types.EducationSharedResourceURI.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.edu_shared_uri_resource.encode(w);
    }
};
