//! EducationSettingsPacket (ID 137), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    education_level_settings: EducationLevelSettings,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.education_level_settings = try EducationLevelSettings.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.education_level_settings.encode(w);
    }
};

/// Wire type `ExternalLinkSettings`.
pub const EducationExternalLinkSettings = struct {
    url: []const u8,
    display_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!EducationExternalLinkSettings {
        var value: EducationExternalLinkSettings = undefined;
        value.url = try r.readString();
        value.display_name = try r.readString();
        return value;
    }

    pub fn encode(self: EducationExternalLinkSettings, w: anytype) EncodeError!void {
        try w.writeString(self.url);
        try w.writeString(self.display_name);
    }
};

/// Wire type `EducationLevelSettings`.
pub const EducationLevelSettings = struct {
    code_builder_default_uri: []const u8,
    code_builder_title: []const u8,
    can_resize_code_builder: bool,
    disable_legacy_title_bar: bool,
    post_process_filter: []const u8,
    screenshot_border_resource_path: []const u8,
    agent_capabilities: ?bool,
    local_settings: ?[]const u8,
    deprecated_always_false: bool,
    external_link_settings: ?EducationExternalLinkSettings,

    pub fn decode(r: *Reader) DecodeError!EducationLevelSettings {
        var value: EducationLevelSettings = undefined;
        value.code_builder_default_uri = try r.readString();
        value.code_builder_title = try r.readString();
        value.can_resize_code_builder = try r.readBool();
        value.disable_legacy_title_bar = try r.readBool();
        value.post_process_filter = try r.readString();
        value.screenshot_border_resource_path = try r.readString();
        value.agent_capabilities = if (try r.readBool()) try r.readBool() else null;
        value.local_settings = if (try r.readBool()) try r.readString() else null;
        value.deprecated_always_false = try r.readBool();
        value.external_link_settings = if (try r.readBool()) try EducationExternalLinkSettings.decode(r) else null;
        return value;
    }

    pub fn encode(self: EducationLevelSettings, w: anytype) EncodeError!void {
        try w.writeString(self.code_builder_default_uri);
        try w.writeString(self.code_builder_title);
        try w.writeBool(self.can_resize_code_builder);
        try w.writeBool(self.disable_legacy_title_bar);
        try w.writeString(self.post_process_filter);
        try w.writeString(self.screenshot_border_resource_path);
        try w.writeBool(self.agent_capabilities != null);
        if (self.agent_capabilities) |present| {
            try w.writeBool(present);
        }
        try w.writeBool(self.local_settings != null);
        if (self.local_settings) |present| {
            try w.writeString(present);
        }
        try w.writeBool(self.deprecated_always_false);
        try w.writeBool(self.external_link_settings != null);
        if (self.external_link_settings) |present| {
            try present.encode(w);
        }
    }
};
