//! GameTestRequestPacket (ID 194), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    max_tests_per_batch: i32,
    repeat_count: i32,
    rotation: types.Rotation,
    stop_on_failure: bool,
    test_pos: codec.BlockPosition,
    tests_per_row: i32,
    test_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.max_tests_per_batch = try r.readVarI32();
        value.repeat_count = try r.readVarI32();
        value.rotation = try types.Rotation.decode(r);
        value.stop_on_failure = try r.readBool();
        value.test_pos = try r.readBlockPosition();
        value.tests_per_row = try r.readVarI32();
        value.test_name = try r.readString();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI32(self.max_tests_per_batch);
        try w.writeVarI32(self.repeat_count);
        try self.rotation.encode(w);
        try w.writeBool(self.stop_on_failure);
        try w.writeBlockPosition(self.test_pos);
        try w.writeVarI32(self.tests_per_row);
        try w.writeString(self.test_name);
    }
};
