//! InventoryContentPacket (ID 49), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    container_id: u32,
    slots: codec.List(types.NetworkItemStackDescriptor, types.NetworkItemStackDescriptor),
    full_container_name: types.FullContainerName,
    storage_item: types.NetworkItemStackDescriptor,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.container_id = try r.readVarU32();
        value.slots = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(types.NetworkItemStackDescriptor, types.NetworkItemStackDescriptor).decode(r, count);
        };
        value.full_container_name = try types.FullContainerName.decode(r);
        value.storage_item = try types.NetworkItemStackDescriptor.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarU32(self.container_id);
        try w.writeCount(.var_u32, self.slots.len);
        try self.slots.encode(w);
        try self.full_container_name.encode(w);
        try self.storage_item.encode(w);
    }
};
