//! ItemStackResponsePacket (ID 148), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    responses: codec.List(ItemStackResponseInfo, ItemStackResponseInfo),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.responses = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(ItemStackResponseInfo, ItemStackResponseInfo).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.responses.len);
        try self.responses.encode(w);
    }
};

/// Wire type `ItemStackNetResult`.
pub const ItemStackNetResult = enum(u8) {
    success = 0,
    @"error" = 1,
    invalidrequestactiontype = 2,
    actionrequestnotallowed = 3,
    screenhandlerendrequestfailed = 4,
    itemrequestactionhandlercommitfailed = 5,
    invalidrequestcraftactiontype = 6,
    invalidcraftrequest = 7,
    invalidcraftrequestscreen = 8,
    invalidcraftresult = 9,
    invalidcraftresultindex = 10,
    invalidcraftresultitem = 11,
    invaliditemnetid = 12,
    missingcreatedoutputcontainer = 13,
    failedtosetcreateditemoutputslot = 14,
    requestalreadyinprogress = 15,
    failedtoinitsparsecontainer = 16,
    resulttransferfailed = 17,
    expecteditemslotnotfullyconsumed = 18,
    expectedanywhereitemnotfullyconsumed = 19,
    itemalreadyconsumedfromslot = 20,
    consumedtoomuchfromslot = 21,
    mismatchslotexpectedconsumeditem = 22,
    mismatchslotexpectedconsumeditemnetidvariant = 23,
    failedtomatchexpectedslotconsumeditem = 24,
    failedtomatchexpectedallowedanywhereconsumeditem = 25,
    consumeditemoutofallowedslotrange = 26,
    consumeditemnotallowed = 27,
    playernotincreativemode = 28,
    invalidexperimentalreciperequest = 29,
    failedtocraftcreative = 30,
    failedtogetlevelrecipe = 31,
    failedtofindrecipebynetid = 32,
    mismatchedcraftingsize = 33,
    missinginputsparsecontainer = 34,
    mismatchedrecipeforinputgriditems = 35,
    emptycraftresults = 36,
    failedtoenchant = 37,
    missinginputitem = 38,
    insufficientplayerleveltoenchant = 39,
    missingmaterialitem = 40,
    missingactor = 41,
    unknownprimaryeffect = 42,
    primaryeffectoutofrange = 43,
    primaryeffectunavailable = 44,
    secondaryeffectoutofrange = 45,
    secondaryeffectunavailable = 46,
    dstcontainerequaltocreatedoutputcontainer = 47,
    dstcontainerandslotequaltosrccontainerandslot = 48,
    failedtovalidatesrcslot = 49,
    failedtovalidatedstslot = 50,
    invalidadjustedamount = 51,
    invaliditemsettype = 52,
    invalidtransferamount = 53,
    cannotswapitem = 54,
    cannotplaceitem = 55,
    unhandleditemsettype = 56,
    invalidremovedamount = 57,
    invalidregion = 58,
    cannotdropitem = 59,
    cannotdestroyitem = 60,
    invalidsourcecontainer = 61,
    itemnotconsumed = 62,
    invalidnumcrafts = 63,
    invalidcraftresultstacksize = 64,
    cannotremoveitem = 65,
    cannotconsumeitem = 66,
    screenstackerror = 67,
    _,

    pub fn decode(r: *Reader) DecodeError!ItemStackNetResult {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: ItemStackNetResult, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `ItemStackResponseContainerInfo`.
pub const ItemStackResponseContainerInfo = struct {
    full_container_name: types.FullContainerName,
    slots: codec.List(ItemStackResponseSlotInfo, ItemStackResponseSlotInfo),

    pub fn decode(r: *Reader) DecodeError!ItemStackResponseContainerInfo {
        var value: ItemStackResponseContainerInfo = undefined;
        value.full_container_name = try types.FullContainerName.decode(r);
        value.slots = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(ItemStackResponseSlotInfo, ItemStackResponseSlotInfo).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: ItemStackResponseContainerInfo, w: anytype) EncodeError!void {
        try self.full_container_name.encode(w);
        try w.writeCount(.var_u32, self.slots.len);
        try self.slots.encode(w);
    }
};

/// Wire type `ItemStackResponseInfo`.
pub const ItemStackResponseInfo = struct {
    result: ItemStackNetResult,
    client_request_id: i32,
    containers: ?codec.List(ItemStackResponseContainerInfo, ItemStackResponseContainerInfo),

    pub fn decode(r: *Reader) DecodeError!ItemStackResponseInfo {
        var value: ItemStackResponseInfo = undefined;
        value.result = try ItemStackNetResult.decode(r);
        value.client_request_id = try r.readVarI32();
        value.containers = null;
        if (try r.readBool()) {
            var present: codec.List(ItemStackResponseContainerInfo, ItemStackResponseContainerInfo) = undefined;
            present = blk: {
                const count = try r.readCount(.var_u32);
                break :blk try codec.List(ItemStackResponseContainerInfo, ItemStackResponseContainerInfo).decode(r, count);
            };
            value.containers = present;
        }
        return value;
    }

    pub fn encode(self: ItemStackResponseInfo, w: anytype) EncodeError!void {
        try self.result.encode(w);
        try w.writeVarI32(self.client_request_id);
        try w.writeBool(self.containers != null);
        if (self.containers) |present| {
            try w.writeCount(.var_u32, present.len);
            try present.encode(w);
        }
    }
};

/// Wire type `ItemStackResponseSlotInfo`.
pub const ItemStackResponseSlotInfo = struct {
    requested_slot: u8,
    slot: u8,
    amount: u8,
    item_stack_net_id: ?i32,
    custom_name: SafetyRedactableString,
    durability_correction: i32,

    pub fn decode(r: *Reader) DecodeError!ItemStackResponseSlotInfo {
        var value: ItemStackResponseSlotInfo = undefined;
        value.requested_slot = try r.readU8();
        value.slot = try r.readU8();
        value.amount = try r.readU8();
        value.item_stack_net_id = if (try r.readBool()) try r.readVarI32() else null;
        value.custom_name = try SafetyRedactableString.decode(r);
        value.durability_correction = try r.readVarI32();
        if (value.durability_correction < -32768) return error.InvalidValue;
        if (value.durability_correction > 32767) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: ItemStackResponseSlotInfo, w: anytype) EncodeError!void {
        try w.writeU8(self.requested_slot);
        try w.writeU8(self.slot);
        try w.writeU8(self.amount);
        try w.writeBool(self.item_stack_net_id != null);
        if (self.item_stack_net_id) |present| {
            try w.writeVarI32(present);
        }
        try self.custom_name.encode(w);
        if (self.durability_correction < -32768) return error.InvalidValue;
        if (self.durability_correction > 32767) return error.InvalidValue;
        try w.writeVarI32(self.durability_correction);
    }
};

/// Wire type `Bedrock::Safety::RedactableString`.
pub const SafetyRedactableString = struct {
    unredacted: []const u8,
    redacted: ?[]const u8,

    pub fn decode(r: *Reader) DecodeError!SafetyRedactableString {
        var value: SafetyRedactableString = undefined;
        value.unredacted = try r.readString();
        value.redacted = if (try r.readBool()) try r.readString() else null;
        return value;
    }

    pub fn encode(self: SafetyRedactableString, w: anytype) EncodeError!void {
        try w.writeString(self.unredacted);
        try w.writeBool(self.redacted != null);
        if (self.redacted) |present| {
            try w.writeString(present);
        }
    }
};
