//! ItemRegistryPacket (ID 162), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    item_data: codec.List(ItemData, ItemData),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.item_data = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(ItemData, ItemData).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.item_data.len);
        try self.item_data.encode(w);
    }
};

/// Wire type `ItemData`.
pub const ItemData = struct {
    item_name: []const u8,
    item_id: i16,
    is_component_based: bool,
    item_version: ItemVersion,
    item_component_data: []const u8,

    pub fn decode(r: *Reader) DecodeError!ItemData {
        var value: ItemData = undefined;
        value.item_name = try r.readString();
        value.item_id = try r.readI16();
        value.is_component_based = try r.readBool();
        value.item_version = try ItemVersion.decode(r);
        value.item_component_data = try r.readNbt();
        return value;
    }

    pub fn encode(self: ItemData, w: anytype) EncodeError!void {
        try w.writeString(self.item_name);
        try w.writeI16(self.item_id);
        try w.writeBool(self.is_component_based);
        try self.item_version.encode(w);
        try w.writeNbt(self.item_component_data);
    }
};

/// Wire type `ItemVersion`.
pub const ItemVersion = enum(i32) {
    legacy = 0,
    datadriven = 1,
    none = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!ItemVersion {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: ItemVersion, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};
