//! LabTablePacket (ID 109), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    type: LabTableType,
    position: codec.BlockPosition,
    reaction: LabTableReactionType,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.type = try LabTableType.decode(r);
        value.position = try r.readBlockPosition();
        value.reaction = try LabTableReactionType.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.type.encode(w);
        try w.writeBlockPosition(self.position);
        try self.reaction.encode(w);
    }
};

/// Wire type `LabTableReactionType`.
pub const LabTableReactionType = enum(u8) {
    none = 0,
    icebomb = 1,
    bleach = 2,
    elephanttoothpaste = 3,
    fertilizer = 4,
    heatblock = 5,
    magnesiumsalts = 6,
    miscfire = 7,
    miscexplosion = 8,
    misclava = 9,
    miscmystical = 10,
    miscsmoke = 11,
    misclargesmoke = 12,
    _,

    pub fn decode(r: *Reader) DecodeError!LabTableReactionType {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: LabTableReactionType, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `LabTablePacketPayload::Type`.
pub const LabTableType = enum(u8) {
    startcombine = 0,
    startreaction = 1,
    reset = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!LabTableType {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: LabTableType, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};
