//! LecternUpdatePacket (ID 125), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    new_page_to_show: u8,
    total_pages: u8,
    position_of_lectern_to_update: codec.BlockPosition,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.new_page_to_show = try r.readU8();
        value.total_pages = try r.readU8();
        value.position_of_lectern_to_update = try r.readBlockPosition();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeU8(self.new_page_to_show);
        try w.writeU8(self.total_pages);
        try w.writeBlockPosition(self.position_of_lectern_to_update);
    }
};
