//! LessonProgressPacket (ID 183), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    lesson_action: i32,
    score: i32,
    activity_id: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.lesson_action = try r.readVarI32();
        value.score = try r.readVarI32();
        value.activity_id = try r.readString();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI32(self.lesson_action);
        try w.writeVarI32(self.score);
        try w.writeString(self.activity_id);
    }
};
