//! LocatorBarPacket (ID 341), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    waypoints: codec.List(LocatorBarWaypointPayload, LocatorBarWaypointPayload),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.waypoints = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 40000) return error.InvalidValue;
            break :blk try codec.List(LocatorBarWaypointPayload, LocatorBarWaypointPayload).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        if (self.waypoints.len > 40000) return error.InvalidValue;
        try w.writeCount(.var_u32, self.waypoints.len);
        try self.waypoints.encode(w);
    }
};

/// Wire type `LocatorBarWaypointPayload`.
pub const LocatorBarWaypointPayload = struct {
    group_handle: [16]u8,
    server_waypoint_payload: Waypoint,
    action_flag: ServerWaypointGroupAction,

    pub fn decode(r: *Reader) DecodeError!LocatorBarWaypointPayload {
        var value: LocatorBarWaypointPayload = undefined;
        value.group_handle = try r.readUuid();
        value.server_waypoint_payload = try Waypoint.decode(r);
        value.action_flag = try ServerWaypointGroupAction.decode(r);
        return value;
    }

    pub fn encode(self: LocatorBarWaypointPayload, w: anytype) EncodeError!void {
        try w.writeUuid(self.group_handle);
        try self.server_waypoint_payload.encode(w);
        try self.action_flag.encode(w);
    }
};

/// Wire type `ServerWaypointGroup::Action`.
pub const ServerWaypointGroupAction = enum(u8) {
    none = 0,
    add = 1,
    remove = 2,
    update = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!ServerWaypointGroupAction {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: ServerWaypointGroupAction, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `ServerWaypoint::Payload`.
pub const Waypoint = struct {
    update_flag: u32,
    is_visible: ?bool,
    world_position: ?WorldPosition,
    texture_path: ?[]const u8,
    icon_size: ?codec.Vec2f,
    color: ?i32,
    client_position_authority: ?bool,
    actor_unique_id: ?i64,

    pub const actor_refs = .{
        .actor_unique_id = codec.ActorRef.unique,
    };

    pub fn decode(r: *Reader) DecodeError!Waypoint {
        var value: Waypoint = undefined;
        value.update_flag = try r.readU32();
        value.is_visible = if (try r.readBool()) try r.readBool() else null;
        value.world_position = if (try r.readBool()) try WorldPosition.decode(r) else null;
        value.texture_path = if (try r.readBool()) try r.readString() else null;
        value.icon_size = if (try r.readBool()) try r.readVec2f() else null;
        value.color = if (try r.readBool()) try r.readI32() else null;
        value.client_position_authority = if (try r.readBool()) try r.readBool() else null;
        value.actor_unique_id = if (try r.readBool()) try r.readVarI64() else null;
        return value;
    }

    pub fn encode(self: Waypoint, w: anytype) EncodeError!void {
        try w.writeU32(self.update_flag);
        try w.writeBool(self.is_visible != null);
        if (self.is_visible) |present| {
            try w.writeBool(present);
        }
        try w.writeBool(self.world_position != null);
        if (self.world_position) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.texture_path != null);
        if (self.texture_path) |present| {
            try w.writeString(present);
        }
        try w.writeBool(self.icon_size != null);
        if (self.icon_size) |present| {
            try w.writeVec2f(present);
        }
        try w.writeBool(self.color != null);
        if (self.color) |present| {
            try w.writeI32(present);
        }
        try w.writeBool(self.client_position_authority != null);
        if (self.client_position_authority) |present| {
            try w.writeBool(present);
        }
        try w.writeBool(self.actor_unique_id != null);
        if (self.actor_unique_id) |present| {
            try w.writeVarI64(present);
        }
    }
};

/// Wire type `WorldPosition`.
pub const WorldPosition = struct {
    position: codec.Vec3f,
    dimension_type: i32,

    pub fn decode(r: *Reader) DecodeError!WorldPosition {
        var value: WorldPosition = undefined;
        value.position = try r.readVec3f();
        value.dimension_type = try r.readVarI32();
        return value;
    }

    pub fn encode(self: WorldPosition, w: anytype) EncodeError!void {
        try w.writeVec3f(self.position);
        try w.writeVarI32(self.dimension_type);
    }
};
