//! ModalFormResponsePacket (ID 101), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    form_id: u32,
    json_response: ?[]const u8,
    form_cancel_reason: ?ModalFormCancelReason,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.form_id = try r.readVarU32();
        value.json_response = if (try r.readBool()) try r.readString() else null;
        value.form_cancel_reason = if (try r.readBool()) try ModalFormCancelReason.decode(r) else null;
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarU32(self.form_id);
        try w.writeBool(self.json_response != null);
        if (self.json_response) |present| {
            try w.writeString(present);
        }
        try w.writeBool(self.form_cancel_reason != null);
        if (self.form_cancel_reason) |present| {
            try present.encode(w);
        }
    }
};

/// Wire type `ModalFormCancelReason`.
pub const ModalFormCancelReason = enum(u8) {
    userclosed = 0,
    userbusy = 1,
    _,

    pub fn decode(r: *Reader) DecodeError!ModalFormCancelReason {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: ModalFormCancelReason, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};
