//! NetworkStackLatencyPacket (ID 115), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    creation_time: u64,
    is_from_server: bool,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.creation_time = try r.readU64();
        value.is_from_server = try r.readBool();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeU64(self.creation_time);
        try w.writeBool(self.is_from_server);
    }
};
