//! PacketViolationWarningPacket (ID 156), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    violation_type: PacketViolationType,
    violation_severity: PacketViolationSeverity,
    violation_packet_id: i32,
    violation_context: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.violation_type = try PacketViolationType.decode(r);
        value.violation_severity = try PacketViolationSeverity.decode(r);
        value.violation_packet_id = try r.readVarI32();
        value.violation_context = try r.readString();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.violation_type.encode(w);
        try self.violation_severity.encode(w);
        try w.writeVarI32(self.violation_packet_id);
        try w.writeString(self.violation_context);
    }
};

/// Wire type `PacketViolationSeverity`.
pub const PacketViolationSeverity = enum(i32) {
    unknown = -1,
    warning = 0,
    finalwarning = 1,
    terminatingconnection = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!PacketViolationSeverity {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: PacketViolationSeverity, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

/// Wire type `PacketViolationType`.
pub const PacketViolationType = enum(i32) {
    unknown = -1,
    packetmalformed = 0,
    _,

    pub fn decode(r: *Reader) DecodeError!PacketViolationType {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: PacketViolationType, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};
