//! PlaySoundPacket (ID 86), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    name: []const u8,
    position: codec.BlockPosition,
    volume: f32,
    pitch: f32,
    loop_count: i32,
    bypass_listener_range_check: bool,
    server_sound_handle: ?u64,
    playback_position_seconds: ?f32,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.name = try r.readString();
        value.position = try r.readBlockPosition();
        value.volume = try r.readF32();
        value.pitch = try r.readF32();
        value.loop_count = try r.readVarI32();
        value.bypass_listener_range_check = try r.readBool();
        value.server_sound_handle = if (try r.readBool()) try r.readU64() else null;
        value.playback_position_seconds = if (try r.readBool()) try r.readF32() else null;
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeString(self.name);
        try w.writeBlockPosition(self.position);
        try w.writeF32(self.volume);
        try w.writeF32(self.pitch);
        try w.writeVarI32(self.loop_count);
        try w.writeBool(self.bypass_listener_range_check);
        try w.writeBool(self.server_sound_handle != null);
        if (self.server_sound_handle) |present| {
            try w.writeU64(present);
        }
        try w.writeBool(self.playback_position_seconds != null);
        if (self.playback_position_seconds) |present| {
            try w.writeF32(present);
        }
    }
};
