//! PlayStatusPacket (ID 2), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    status: PlayStatusType,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.status = try PlayStatusType.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.status.encode(w);
    }
};

/// Wire type `PlayStatus`.
pub const PlayStatusType = enum(i32) {
    loginsuccess = 0,
    loginfailed_clientold = 1,
    loginfailed_serverold = 2,
    playerspawn = 3,
    loginfailed_invalidtenant = 4,
    loginfailed_editionmismatchedutovanilla = 5,
    loginfailed_editionmismatchvanillatoedu = 6,
    loginfailed_serverfullsubclient = 7,
    loginfailed_editormismatcheditortovanilla = 8,
    loginfailed_editormismatchvanillatoeditor = 9,
    _,

    pub fn decode(r: *Reader) DecodeError!PlayStatusType {
        return @fromBackingInt(@intCast(try r.readI32Be()));
    }

    pub fn encode(self: PlayStatusType, w: anytype) EncodeError!void {
        try w.writeI32Be(@backingInt(self));
    }
};
