//! PlayerHotbarPacket (ID 48), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    selected_slot: u32,
    container_id: u8,
    should_select_slot: bool,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.selected_slot = try r.readVarU32();
        value.container_id = try r.readU8();
        value.should_select_slot = try r.readBool();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarU32(self.selected_slot);
        try w.writeU8(self.container_id);
        try w.writeBool(self.should_select_slot);
    }
};
