//! PlayerVideoCapturePacket (ID 324), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    action: PlayerVideoCaptureAction,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.action = try PlayerVideoCaptureAction.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.action.encode(w);
    }
};

pub const PlayerVideoCaptureAction = union(enum(u32)) {
    start: PlayerVideoCaptureStartVideoCapture,
    stop: PlayerVideoCaptureStopVideoCapture,

    pub fn decode(r: *Reader) DecodeError!PlayerVideoCaptureAction {
        switch (try r.readVarU32()) {
            0 => return .{ .start = try PlayerVideoCaptureStartVideoCapture.decode(r) },
            1 => return .{ .stop = try PlayerVideoCaptureStopVideoCapture.decode(r) },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: PlayerVideoCaptureAction, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .start => |value| {
                try value.encode(w);
            },
            .stop => |value| {
                try value.encode(w);
            },
        }
    }
};

/// Wire type `PlayerVideoCapturePacketPayload::StartVideoCapture`.
pub const PlayerVideoCaptureStartVideoCapture = struct {
    frame_rate: u32,
    file_prefix: []const u8,

    pub fn decode(r: *Reader) DecodeError!PlayerVideoCaptureStartVideoCapture {
        var value: PlayerVideoCaptureStartVideoCapture = undefined;
        value.frame_rate = try r.readU32();
        value.file_prefix = try r.readString();
        return value;
    }

    pub fn encode(self: PlayerVideoCaptureStartVideoCapture, w: anytype) EncodeError!void {
        try w.writeU32(self.frame_rate);
        try w.writeString(self.file_prefix);
    }
};

/// Wire type `PlayerVideoCapturePacketPayload::StopVideoCapture`.
pub const PlayerVideoCaptureStopVideoCapture = struct {
    pub fn decode(r: *Reader) DecodeError!PlayerVideoCaptureStopVideoCapture {
        _ = r;
        return .{};
    }

    pub fn encode(self: PlayerVideoCaptureStopVideoCapture, w: anytype) EncodeError!void {
        _ = self;
        _ = w;
    }
};
