//! PlayerToggleCrafterSlotRequestPacket (ID 306), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    pos_x: i32,
    pos_y: i32,
    pos_z: i32,
    slot_index: u8,
    is_disabled: bool,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.pos_x = try r.readI32();
        value.pos_y = try r.readI32();
        value.pos_z = try r.readI32();
        value.slot_index = try r.readU8();
        value.is_disabled = try r.readBool();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeI32(self.pos_x);
        try w.writeI32(self.pos_y);
        try w.writeI32(self.pos_z);
        try w.writeU8(self.slot_index);
        try w.writeBool(self.is_disabled);
    }
};
