//! PlayerLocationPacket (ID 326), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    target_actor_id: i64,
    location: PlayerLocationLocation,

    pub const actor_refs = .{
        .target_actor_id = codec.ActorRef.unique,
    };

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.target_actor_id = try r.readVarI64();
        value.location = try PlayerLocationLocation.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI64(self.target_actor_id);
        try self.location.encode(w);
    }
};

/// Wire type `PlayerLocationPacketPayload::CoordinatesLocation`.
pub const PlayerLocationCoordinatesLocation = struct {
    packet_type: PlayerLocationType,
    position: codec.Vec3f,

    pub fn decode(r: *Reader) DecodeError!PlayerLocationCoordinatesLocation {
        var value: PlayerLocationCoordinatesLocation = undefined;
        value.packet_type = try PlayerLocationType.decode(r);
        switch (value.packet_type) {
            .player_location_coordinates => {},
            else => return error.InvalidValue,
        }
        value.position = try r.readVec3f();
        return value;
    }

    pub fn encode(self: PlayerLocationCoordinatesLocation, w: anytype) EncodeError!void {
        switch (self.packet_type) {
            .player_location_coordinates => {},
            else => return error.InvalidValue,
        }
        try self.packet_type.encode(w);
        try w.writeVec3f(self.position);
    }
};

pub const PlayerLocationLocation = union(enum(u32)) {
    coordinates: PlayerLocationCoordinatesLocation,
    hidden: PlayerLocationType,

    pub fn decode(r: *Reader) DecodeError!PlayerLocationLocation {
        switch (try r.readVarU32()) {
            0 => return .{ .coordinates = try PlayerLocationCoordinatesLocation.decode(r) },
            1 => {
                var value: PlayerLocationType = undefined;
                value = try PlayerLocationType.decode(r);
                switch (value) {
                    .player_location_hide => {},
                    else => return error.InvalidValue,
                }
                return .{ .hidden = value };
            },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: PlayerLocationLocation, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .coordinates => |value| {
                try value.encode(w);
            },
            .hidden => |value| {
                switch (value) {
                    .player_location_hide => {},
                    else => return error.InvalidValue,
                }
                try value.encode(w);
            },
        }
    }
};

/// Wire type `PlayerLocationPacketPayload::Type`.
pub const PlayerLocationType = enum(i32) {
    player_location_coordinates = 0,
    player_location_hide = 1,
    _,

    pub fn decode(r: *Reader) DecodeError!PlayerLocationType {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: PlayerLocationType, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};
