//! PositionTrackingDBClientRequestPacket (ID 154), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    action: PositionTrackingDBClientRequestAction,
    id: i32,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.action = try PositionTrackingDBClientRequestAction.decode(r);
        value.id = try r.readVarI32();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.action.encode(w);
        try w.writeVarI32(self.id);
    }
};

/// Wire type `PositionTrackingDBClientRequestPacketPayload::Action`.
pub const PositionTrackingDBClientRequestAction = enum(u8) {
    query = 0,
    _,

    pub fn decode(r: *Reader) DecodeError!PositionTrackingDBClientRequestAction {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: PositionTrackingDBClientRequestAction, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};
