//! PurchaseReceiptPacket (ID 92), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    purchase_receipts: codec.List([]const u8, codec.Prim(.string)),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.purchase_receipts = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 10000) return error.InvalidValue;
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        if (self.purchase_receipts.len > 10000) return error.InvalidValue;
        try w.writeCount(.var_u32, self.purchase_receipts.len);
        try self.purchase_receipts.encode(w);
    }
};
