//! RefreshEntitlementsPacket (ID 305), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    pub fn decode(r: *Reader) DecodeError!Packet {
        _ = r;
        return .{};
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        _ = self;
        _ = w;
    }
};
