//! RequestAbilityPacket (ID 184), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    ability: i32,
    value_type: RequestAbilityType,
    bool: bool,
    float: f32,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.ability = try r.readVarI32();
        if (value.ability < 0) return error.InvalidValue;
        if (value.ability > 19) return error.InvalidValue;
        value.value_type = try RequestAbilityType.decode(r);
        value.bool = try r.readBool();
        value.float = try r.readF32();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        if (self.ability < 0) return error.InvalidValue;
        if (self.ability > 19) return error.InvalidValue;
        try w.writeVarI32(self.ability);
        try self.value_type.encode(w);
        try w.writeBool(self.bool);
        try w.writeF32(self.float);
    }
};

/// Wire type `RequestAbilityPacketPayload::Type`.
pub const RequestAbilityType = enum(u8) {
    unset = 0,
    bool = 1,
    float = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!RequestAbilityType {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: RequestAbilityType, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};
