//! ResourcePackClientResponsePacket (ID 8), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    response: ResourcePackClientResponseResponse,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.response = try ResourcePackClientResponseResponse.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.response.encode(w);
    }
};

/// Wire type `Resource_Pack_Client_Response_-_Downloading`.
pub const Downloading = struct {
    response_type: []const u8,
    downloading_packs: codec.List([]const u8, codec.Prim(.string)),

    pub fn decode(r: *Reader) DecodeError!Downloading {
        var value: Downloading = undefined;
        value.response_type = try r.readString();
        value.downloading_packs = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 65535) return error.InvalidValue;
            break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Downloading, w: anytype) EncodeError!void {
        try w.writeString(self.response_type);
        if (self.downloading_packs.len > 65535) return error.InvalidValue;
        try w.writeCount(.var_u32, self.downloading_packs.len);
        try self.downloading_packs.encode(w);
    }
};

pub const ResourcePackClientResponseResponse = union(enum(u32)) {
    cancel: []const u8,
    downloading: Downloading,
    downloading_finished: []const u8,
    resource_pack_stack_finished: []const u8,

    pub fn decode(r: *Reader) DecodeError!ResourcePackClientResponseResponse {
        switch (try r.readVarU32()) {
            0 => return .{ .cancel = try r.readString() },
            1 => return .{ .downloading = try Downloading.decode(r) },
            2 => return .{ .downloading_finished = try r.readString() },
            3 => return .{ .resource_pack_stack_finished = try r.readString() },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: ResourcePackClientResponseResponse, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .cancel => |value| {
                try w.writeString(value);
            },
            .downloading => |value| {
                try value.encode(w);
            },
            .downloading_finished => |value| {
                try w.writeString(value);
            },
            .resource_pack_stack_finished => |value| {
                try w.writeString(value);
            },
        }
    }
};
