//! ResourcePackStackPacket (ID 7), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    texture_pack_required: bool,
    texture_pack_list: codec.List(StackResourcePack, StackResourcePack),
    base_game_version: []const u8,
    experiments: types.Experiments,
    include_editor_packs: bool,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.texture_pack_required = try r.readBool();
        value.texture_pack_list = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 65535) return error.InvalidValue;
            break :blk try codec.List(StackResourcePack, StackResourcePack).decode(r, count);
        };
        value.base_game_version = try r.readString();
        value.experiments = try types.Experiments.decode(r);
        value.include_editor_packs = try r.readBool();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeBool(self.texture_pack_required);
        if (self.texture_pack_list.len > 65535) return error.InvalidValue;
        try w.writeCount(.var_u32, self.texture_pack_list.len);
        try self.texture_pack_list.encode(w);
        try w.writeString(self.base_game_version);
        try self.experiments.encode(w);
        try w.writeBool(self.include_editor_packs);
    }
};

/// Wire type `PackInstanceId`.
pub const StackResourcePack = struct {
    pack_id: []const u8,
    version: []const u8,
    sub_pack_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!StackResourcePack {
        var value: StackResourcePack = undefined;
        value.pack_id = try r.readString();
        value.version = try r.readString();
        value.sub_pack_name = try r.readString();
        return value;
    }

    pub fn encode(self: StackResourcePack, w: anytype) EncodeError!void {
        try w.writeString(self.pack_id);
        try w.writeString(self.version);
        try w.writeString(self.sub_pack_name);
    }
};
