//! ResourcePacksInfoPacket (ID 6), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    resource_pack_required: bool,
    has_addon_packs: bool,
    has_scripts: bool,
    force_disable_vibrant_visuals: bool,
    world_template_id_and_version: PackIDVersionData,
    resource_packs: codec.List(PackInfoData, PackInfoData),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.resource_pack_required = try r.readBool();
        value.has_addon_packs = try r.readBool();
        value.has_scripts = try r.readBool();
        value.force_disable_vibrant_visuals = try r.readBool();
        value.world_template_id_and_version = try PackIDVersionData.decode(r);
        value.resource_packs = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 65535) return error.InvalidValue;
            break :blk try codec.List(PackInfoData, PackInfoData).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeBool(self.resource_pack_required);
        try w.writeBool(self.has_addon_packs);
        try w.writeBool(self.has_scripts);
        try w.writeBool(self.force_disable_vibrant_visuals);
        try self.world_template_id_and_version.encode(w);
        if (self.resource_packs.len > 65535) return error.InvalidValue;
        try w.writeCount(.var_u32, self.resource_packs.len);
        try self.resource_packs.encode(w);
    }
};

/// Wire type `PackIdVersion`.
pub const PackIDVersionData = struct {
    pack_uuid: [16]u8,
    pack_version: []const u8,

    pub fn decode(r: *Reader) DecodeError!PackIDVersionData {
        var value: PackIDVersionData = undefined;
        value.pack_uuid = try r.readUuid();
        value.pack_version = try r.readString();
        return value;
    }

    pub fn encode(self: PackIDVersionData, w: anytype) EncodeError!void {
        try w.writeUuid(self.pack_uuid);
        try w.writeString(self.pack_version);
    }
};

/// Wire type `PackInfoData`.
pub const PackInfoData = struct {
    pack_id_version: PackIDVersionData,
    pack_size: u64,
    content_key: []const u8,
    subpack_name: []const u8,
    content_identity: []const u8,
    has_scripts: bool,
    is_addon_pack: bool,
    is_ray_tracing_capable: bool,
    cdn_url: []const u8,

    pub fn decode(r: *Reader) DecodeError!PackInfoData {
        var value: PackInfoData = undefined;
        value.pack_id_version = try PackIDVersionData.decode(r);
        value.pack_size = try r.readU64();
        value.content_key = try r.readString();
        value.subpack_name = try r.readString();
        value.content_identity = try r.readString();
        value.has_scripts = try r.readBool();
        value.is_addon_pack = try r.readBool();
        value.is_ray_tracing_capable = try r.readBool();
        value.cdn_url = try r.readString();
        return value;
    }

    pub fn encode(self: PackInfoData, w: anytype) EncodeError!void {
        try self.pack_id_version.encode(w);
        try w.writeU64(self.pack_size);
        try w.writeString(self.content_key);
        try w.writeString(self.subpack_name);
        try w.writeString(self.content_identity);
        try w.writeBool(self.has_scripts);
        try w.writeBool(self.is_addon_pack);
        try w.writeBool(self.is_ray_tracing_capable);
        try w.writeString(self.cdn_url);
    }
};
