//! SendPartyDestinationCookiePacket (ID 349), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    cookie: []const u8,
    intent: []const u8,
    destination_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.cookie = try r.readString();
        if (value.cookie.len > 2048) return error.InvalidValue;
        value.intent = try r.readString();
        value.destination_name = try r.readString();
        if (value.destination_name.len > 64) return error.InvalidValue;
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        if (self.cookie.len > 2048) return error.InvalidValue;
        try w.writeString(self.cookie);
        try w.writeString(self.intent);
        if (self.destination_name.len > 64) return error.InvalidValue;
        try w.writeString(self.destination_name);
    }
};
