//! ServerboundPackSettingChangePacket (ID 329), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    pack_id: [16]u8,
    pack_setting_name: []const u8,
    pack_setting_value: ServerBoundPackSettingChangePackSettingValue,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.pack_id = try r.readUuid();
        value.pack_setting_name = try r.readString();
        if (value.pack_setting_name.len > 128) return error.InvalidValue;
        value.pack_setting_value = try ServerBoundPackSettingChangePackSettingValue.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeUuid(self.pack_id);
        if (self.pack_setting_name.len > 128) return error.InvalidValue;
        try w.writeString(self.pack_setting_name);
        try self.pack_setting_value.encode(w);
    }
};

pub const ServerBoundPackSettingChangePackSettingValue = union(enum(u32)) {
    float: f32,
    bool: bool,
    string: []const u8,
    string_list: codec.List([]const u8, codec.Prim(.string)),

    pub fn decode(r: *Reader) DecodeError!ServerBoundPackSettingChangePackSettingValue {
        switch (try r.readVarU32()) {
            0 => return .{ .float = try r.readF32() },
            1 => return .{ .bool = try r.readBool() },
            2 => return .{ .string = try r.readString() },
            3 => {
                var value: codec.List([]const u8, codec.Prim(.string)) = undefined;
                value = blk: {
                    const count = try r.readCount(.var_u32);
                    break :blk try codec.List([]const u8, codec.Prim(.string)).decode(r, count);
                };
                return .{ .string_list = value };
            },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: ServerBoundPackSettingChangePackSettingValue, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .float => |value| {
                try w.writeF32(value);
            },
            .bool => |value| {
                try w.writeBool(value);
            },
            .string => |value| {
                try w.writeString(value);
            },
            .string_list => |value| {
                try w.writeCount(.var_u32, value.len);
                try value.encode(w);
            },
        }
    }
};
