//! SetScorePacket (ID 108), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    score_info: codec.List(SetScoreScoreInfoItem, SetScoreScoreInfoItem),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.score_info = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(SetScoreScoreInfoItem, SetScoreScoreInfoItem).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.score_info.len);
        try self.score_info.encode(w);
    }
};

/// Wire type `ChangeEntityScore`.
pub const ChangeEntityScore = struct {
    action: []const u8,
    scoreboard_id: i64,
    objective_name: []const u8,
    score_value: i32,
    actor_id: i64,

    pub const actor_refs = .{
        .actor_id = codec.ActorRef.unique,
    };

    pub fn decode(r: *Reader) DecodeError!ChangeEntityScore {
        var value: ChangeEntityScore = undefined;
        value.action = try r.readString();
        value.scoreboard_id = try r.readVarI64();
        value.objective_name = try r.readString();
        value.score_value = try r.readI32();
        value.actor_id = try r.readVarI64();
        return value;
    }

    pub fn encode(self: ChangeEntityScore, w: anytype) EncodeError!void {
        try w.writeString(self.action);
        try w.writeVarI64(self.scoreboard_id);
        try w.writeString(self.objective_name);
        try w.writeI32(self.score_value);
        try w.writeVarI64(self.actor_id);
    }
};

/// Wire type `ChangeFakePlayerScore`.
pub const ChangeFakePlayerScore = struct {
    action: []const u8,
    scoreboard_id: i64,
    objective_name: []const u8,
    score_value: i32,
    fake_player_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!ChangeFakePlayerScore {
        var value: ChangeFakePlayerScore = undefined;
        value.action = try r.readString();
        value.scoreboard_id = try r.readVarI64();
        value.objective_name = try r.readString();
        value.score_value = try r.readI32();
        value.fake_player_name = try r.readString();
        return value;
    }

    pub fn encode(self: ChangeFakePlayerScore, w: anytype) EncodeError!void {
        try w.writeString(self.action);
        try w.writeVarI64(self.scoreboard_id);
        try w.writeString(self.objective_name);
        try w.writeI32(self.score_value);
        try w.writeString(self.fake_player_name);
    }
};

/// Wire type `ChangePlayerScore`.
pub const ChangePlayerScore = struct {
    action: []const u8,
    scoreboard_id: i64,
    objective_name: []const u8,
    score_value: i32,
    player_unique_id: i64,

    pub const actor_refs = .{
        .player_unique_id = codec.ActorRef.unique,
    };

    pub fn decode(r: *Reader) DecodeError!ChangePlayerScore {
        var value: ChangePlayerScore = undefined;
        value.action = try r.readString();
        value.scoreboard_id = try r.readVarI64();
        value.objective_name = try r.readString();
        value.score_value = try r.readI32();
        value.player_unique_id = try r.readVarI64();
        return value;
    }

    pub fn encode(self: ChangePlayerScore, w: anytype) EncodeError!void {
        try w.writeString(self.action);
        try w.writeVarI64(self.scoreboard_id);
        try w.writeString(self.objective_name);
        try w.writeI32(self.score_value);
        try w.writeVarI64(self.player_unique_id);
    }
};

/// Wire type `RemoveScore`.
pub const RemoveScore = struct {
    action: []const u8,
    scoreboard_id: i64,
    objective_name: ?[]const u8,

    pub fn decode(r: *Reader) DecodeError!RemoveScore {
        var value: RemoveScore = undefined;
        value.action = try r.readString();
        value.scoreboard_id = try r.readVarI64();
        value.objective_name = if (try r.readBool()) try r.readString() else null;
        return value;
    }

    pub fn encode(self: RemoveScore, w: anytype) EncodeError!void {
        try w.writeString(self.action);
        try w.writeVarI64(self.scoreboard_id);
        try w.writeBool(self.objective_name != null);
        if (self.objective_name) |present| {
            try w.writeString(present);
        }
    }
};

pub const SetScoreScoreInfoItem = union(enum(u32)) {
    remove: RemoveScore,
    change_player: ChangePlayerScore,
    change_entity: ChangeEntityScore,
    change_fake_player: ChangeFakePlayerScore,

    pub fn decode(r: *Reader) DecodeError!SetScoreScoreInfoItem {
        switch (try r.readVarU32()) {
            0 => return .{ .remove = try RemoveScore.decode(r) },
            1 => return .{ .change_player = try ChangePlayerScore.decode(r) },
            2 => return .{ .change_entity = try ChangeEntityScore.decode(r) },
            3 => return .{ .change_fake_player = try ChangeFakePlayerScore.decode(r) },
            else => return error.InvalidEnum,
        }
    }

    pub fn encode(self: SetScoreScoreInfoItem, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
        switch (self) {
            .remove => |value| {
                try value.encode(w);
            },
            .change_player => |value| {
                try value.encode(w);
            },
            .change_entity => |value| {
                try value.encode(w);
            },
            .change_fake_player => |value| {
                try value.encode(w);
            },
        }
    }
};
