//! SetPlayerFurnaceOptionsPacket (ID 351), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    furnace_type: SetPlayerFurnaceOptionsFurnaceType,
    furnace_options: FurnaceOptions,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.furnace_type = try SetPlayerFurnaceOptionsFurnaceType.decode(r);
        value.furnace_options = try FurnaceOptions.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.furnace_type.encode(w);
        try self.furnace_options.encode(w);
    }
};

/// Wire type `FurnaceLayout`.
pub const FurnaceLayout = enum(i32) {
    none = 0,
    inventoryonly = 1,
    default = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!FurnaceLayout {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: FurnaceLayout, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

/// Wire type `FurnaceLeftTabIndex`.
pub const FurnaceLeftTabIndex = enum(i32) {
    none = 0,
    recipefood = 1,
    recipeitems = 2,
    recipeblocks = 3,
    recipesearch = 4,
    inventory = 5,
    _,

    pub fn decode(r: *Reader) DecodeError!FurnaceLeftTabIndex {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: FurnaceLeftTabIndex, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

/// Wire type `FurnaceOptions`.
pub const FurnaceOptions = struct {
    left_furnace_tab: FurnaceLeftTabIndex,
    filtering: bool,
    layout: FurnaceLayout,

    pub fn decode(r: *Reader) DecodeError!FurnaceOptions {
        var value: FurnaceOptions = undefined;
        value.left_furnace_tab = try FurnaceLeftTabIndex.decode(r);
        value.filtering = try r.readBool();
        value.layout = try FurnaceLayout.decode(r);
        return value;
    }

    pub fn encode(self: FurnaceOptions, w: anytype) EncodeError!void {
        try self.left_furnace_tab.encode(w);
        try w.writeBool(self.filtering);
        try self.layout.encode(w);
    }
};

/// Wire type `SetPlayerFurnaceOptionsPacketPayload::FurnaceType`.
pub const SetPlayerFurnaceOptionsFurnaceType = enum(u8) {
    none = 0,
    furnace = 1,
    blastfurnace = 2,
    smoker = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!SetPlayerFurnaceOptionsFurnaceType {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: SetPlayerFurnaceOptionsFurnaceType, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};
