//! SetSpawnPositionPacket (ID 43), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    spawn_position_type: SpawnPositionType,
    block_position: codec.BlockPosition,
    dimension_type: i32,
    spawn_block_pos: codec.BlockPosition,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.spawn_position_type = try SpawnPositionType.decode(r);
        value.block_position = try r.readBlockPosition();
        value.dimension_type = try r.readVarI32();
        value.spawn_block_pos = try r.readBlockPosition();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.spawn_position_type.encode(w);
        try w.writeBlockPosition(self.block_position);
        try w.writeVarI32(self.dimension_type);
        try w.writeBlockPosition(self.spawn_block_pos);
    }
};

/// Wire type `SpawnPositionType`.
pub const SpawnPositionType = enum(i32) {
    playerrespawn = 0,
    worldspawn = 1,
    _,

    pub fn decode(r: *Reader) DecodeError!SpawnPositionType {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: SpawnPositionType, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};
