//! SetActorLinkPacket (ID 41), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    link: types.EntityLink,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.link = try types.EntityLink.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.link.encode(w);
    }
};
