//! SetPlayerGameTypePacket (ID 62), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    player_game_type: types.GameType,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.player_game_type = try types.GameType.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try self.player_game_type.encode(w);
    }
};
