//! SettingsCommandPacket (ID 140), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    command: []const u8,
    suppress_output: bool,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.command = try r.readString();
        value.suppress_output = try r.readBool();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeString(self.command);
        try w.writeBool(self.suppress_output);
    }
};
