//! StartGamePacket (ID 11), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    entity_id: i64,
    runtime_id: u64,
    game_type: types.GameType,
    position: codec.Vec3f,
    rotation: codec.Vec2f,
    settings: LevelSettings,
    level_id: []const u8,
    level_name: []const u8,
    template_content_identity: []const u8,
    is_trial: bool,
    movement_settings: PlayerMovementSettings,
    level_current_time: u64,
    enchantment_seed: i32,
    block_properties: codec.List(ServerBlockProperty, ServerBlockProperty),
    multiplayer_correlation_id: []const u8,
    enable_item_stack_net_manager: bool,
    server_version: []const u8,
    player_property_data: []const u8,
    server_block_type_registry_checksum: u64,
    world_template_id: [16]u8,
    server_enabled_client_side_generation: bool,
    block_network_ids_are_hashes: bool,
    network_permissions: bool,
    server_configuration_join_info: ?ServerConfigurationJoinInfo,
    server_telemetry_data: EventsServerTelemetryData,

    pub const actor_refs = .{
        .entity_id = codec.ActorRef.unique,
        .runtime_id = codec.ActorRef.runtime,
    };

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.entity_id = try r.readVarI64();
        value.runtime_id = try r.readVarU64();
        value.game_type = try types.GameType.decode(r);
        value.position = try r.readVec3f();
        value.rotation = try r.readVec2f();
        value.settings = try LevelSettings.decode(r);
        value.level_id = try r.readString();
        value.level_name = try r.readString();
        value.template_content_identity = try r.readString();
        value.is_trial = try r.readBool();
        value.movement_settings = try PlayerMovementSettings.decode(r);
        value.level_current_time = try r.readU64();
        value.enchantment_seed = try r.readVarI32();
        value.block_properties = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(ServerBlockProperty, ServerBlockProperty).decode(r, count);
        };
        value.multiplayer_correlation_id = try r.readString();
        value.enable_item_stack_net_manager = try r.readBool();
        value.server_version = try r.readString();
        value.player_property_data = try r.readNbt();
        value.server_block_type_registry_checksum = try r.readU64();
        value.world_template_id = try r.readUuid();
        value.server_enabled_client_side_generation = try r.readBool();
        value.block_network_ids_are_hashes = try r.readBool();
        value.network_permissions = try r.readBool();
        value.server_configuration_join_info = if (try r.readBool()) try ServerConfigurationJoinInfo.decode(r) else null;
        value.server_telemetry_data = try EventsServerTelemetryData.decode(r);
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI64(self.entity_id);
        try w.writeVarU64(self.runtime_id);
        try self.game_type.encode(w);
        try w.writeVec3f(self.position);
        try w.writeVec2f(self.rotation);
        try self.settings.encode(w);
        try w.writeString(self.level_id);
        try w.writeString(self.level_name);
        try w.writeString(self.template_content_identity);
        try w.writeBool(self.is_trial);
        try self.movement_settings.encode(w);
        try w.writeU64(self.level_current_time);
        try w.writeVarI32(self.enchantment_seed);
        try w.writeCount(.var_u32, self.block_properties.len);
        try self.block_properties.encode(w);
        try w.writeString(self.multiplayer_correlation_id);
        try w.writeBool(self.enable_item_stack_net_manager);
        try w.writeString(self.server_version);
        try w.writeNbt(self.player_property_data);
        try w.writeU64(self.server_block_type_registry_checksum);
        try w.writeUuid(self.world_template_id);
        try w.writeBool(self.server_enabled_client_side_generation);
        try w.writeBool(self.block_network_ids_are_hashes);
        try w.writeBool(self.network_permissions);
        try w.writeBool(self.server_configuration_join_info != null);
        if (self.server_configuration_join_info) |present| {
            try present.encode(w);
        }
        try self.server_telemetry_data.encode(w);
    }
};

/// Wire type `ChatRestrictionLevel`.
pub const ChatRestrictionLevel = enum(u8) {
    none = 0,
    dropped = 1,
    disabled = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!ChatRestrictionLevel {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: ChatRestrictionLevel, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};

/// Wire type `Editor::WorldType`.
pub const EditorWorldType = enum(i32) {
    noneditor = 0,
    editorproject = 1,
    editortestlevel = 2,
    editorrealmsupload = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!EditorWorldType {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: EditorWorldType, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

/// Wire type `EducationEditionOffer`.
pub const EducationEditionOffer = enum(u32) {
    none = 0,
    restofworld = 1,
    china_deprecated = 2,
    _,

    pub fn decode(r: *Reader) DecodeError!EducationEditionOffer {
        return @fromBackingInt(@intCast(try r.readVarU32()));
    }

    pub fn encode(self: EducationEditionOffer, w: anytype) EncodeError!void {
        try w.writeVarU32(@backingInt(self));
    }
};

/// Wire type `Social::Events::ServerTelemetryData`.
pub const EventsServerTelemetryData = struct {
    server_id: []const u8,
    scenario_id: []const u8,
    world_id: []const u8,
    owner_id: []const u8,

    pub fn decode(r: *Reader) DecodeError!EventsServerTelemetryData {
        var value: EventsServerTelemetryData = undefined;
        value.server_id = try r.readString();
        value.scenario_id = try r.readString();
        value.world_id = try r.readString();
        value.owner_id = try r.readString();
        return value;
    }

    pub fn encode(self: EventsServerTelemetryData, w: anytype) EncodeError!void {
        try w.writeString(self.server_id);
        try w.writeString(self.scenario_id);
        try w.writeString(self.world_id);
        try w.writeString(self.owner_id);
    }
};

/// Wire type `SharedTypes::Legacy::Difficulty`.
pub const LegacyDifficulty = enum(i32) {
    peaceful = 0,
    easy = 1,
    normal = 2,
    hard = 3,
    count = 4,
    unknown = 5,
    _,

    pub fn decode(r: *Reader) DecodeError!LegacyDifficulty {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: LegacyDifficulty, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

/// Wire type `LevelSettings`.
pub const LevelSettings = struct {
    seed: u64,
    spawn_settings: SpawnSettings,
    generator_type: types.GeneratorType,
    game_type: types.GameType,
    is_hardcore: bool,
    game_difficulty: LegacyDifficulty,
    default_spawn_block_position: codec.BlockPosition,
    achievements_disabled: bool,
    editor_world_type: EditorWorldType,
    is_created_in_editor: bool,
    is_exported_from_editor: bool,
    day_cycle_stop_time: i32,
    education_edition_offer: EducationEditionOffer,
    education_features_enabled: bool,
    education_product_id: []const u8,
    rain_level: f32,
    lightning_level: f32,
    has_confirmed_platform_locked_content: bool,
    multiplayer_game_intent: bool,
    lan_broadcast_intent: bool,
    xbox_live_broadcast_setting: SocialGamePublishSetting,
    platform_broadcast_setting: SocialGamePublishSetting,
    commands_enabled: bool,
    texture_packs_required: bool,
    rule_data: codec.List(types.GameRule, types.GameRule),
    experiments: types.Experiments,
    has_bonus_chest_enabled: bool,
    start_with_map_enabled: bool,
    player_permissions: types.PlayerPermissionLevel,
    server_chunk_tick_range: i32,
    has_locked_behavior_pack: bool,
    has_locked_resource_pack: bool,
    is_from_locked_template: bool,
    use_msa_gamertags_only: bool,
    is_from_world_template: bool,
    is_world_template_option_locked: bool,
    only_spawn_v1_villagers: bool,
    persona_disabled: bool,
    custom_skins_disabled: bool,
    emote_chat_muted: bool,
    base_game_version: []const u8,
    limited_world_width: i32,
    limited_world_depth: i32,
    nether_type: bool,
    edu_shared_uri_resource: types.EducationSharedResourceURI,
    override_force_experimental_gameplay: ?bool,
    chat_restriction_level: ChatRestrictionLevel,
    disable_player_interactions: bool,
    server_editor_connection_policy: ServerEditorConnectionPolicy,
    allow_anonymous_block_drops_in_editor_worlds: bool,

    pub fn decode(r: *Reader) DecodeError!LevelSettings {
        var value: LevelSettings = undefined;
        value.seed = try r.readU64();
        value.spawn_settings = try SpawnSettings.decode(r);
        value.generator_type = try types.GeneratorType.decode(r);
        value.game_type = try types.GameType.decode(r);
        value.is_hardcore = try r.readBool();
        value.game_difficulty = try LegacyDifficulty.decode(r);
        value.default_spawn_block_position = try r.readBlockPosition();
        value.achievements_disabled = try r.readBool();
        value.editor_world_type = try EditorWorldType.decode(r);
        value.is_created_in_editor = try r.readBool();
        value.is_exported_from_editor = try r.readBool();
        value.day_cycle_stop_time = try r.readVarI32();
        value.education_edition_offer = try EducationEditionOffer.decode(r);
        value.education_features_enabled = try r.readBool();
        value.education_product_id = try r.readString();
        value.rain_level = try r.readF32();
        value.lightning_level = try r.readF32();
        value.has_confirmed_platform_locked_content = try r.readBool();
        value.multiplayer_game_intent = try r.readBool();
        value.lan_broadcast_intent = try r.readBool();
        value.xbox_live_broadcast_setting = try SocialGamePublishSetting.decode(r);
        value.platform_broadcast_setting = try SocialGamePublishSetting.decode(r);
        value.commands_enabled = try r.readBool();
        value.texture_packs_required = try r.readBool();
        value.rule_data = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(types.GameRule, types.GameRule).decode(r, count);
        };
        value.experiments = try types.Experiments.decode(r);
        value.has_bonus_chest_enabled = try r.readBool();
        value.start_with_map_enabled = try r.readBool();
        value.player_permissions = try types.PlayerPermissionLevel.decode(r);
        value.server_chunk_tick_range = try r.readI32();
        value.has_locked_behavior_pack = try r.readBool();
        value.has_locked_resource_pack = try r.readBool();
        value.is_from_locked_template = try r.readBool();
        value.use_msa_gamertags_only = try r.readBool();
        value.is_from_world_template = try r.readBool();
        value.is_world_template_option_locked = try r.readBool();
        value.only_spawn_v1_villagers = try r.readBool();
        value.persona_disabled = try r.readBool();
        value.custom_skins_disabled = try r.readBool();
        value.emote_chat_muted = try r.readBool();
        value.base_game_version = try r.readString();
        value.limited_world_width = try r.readI32();
        value.limited_world_depth = try r.readI32();
        value.nether_type = try r.readBool();
        value.edu_shared_uri_resource = try types.EducationSharedResourceURI.decode(r);
        value.override_force_experimental_gameplay = if (try r.readBool()) try r.readBool() else null;
        value.chat_restriction_level = try ChatRestrictionLevel.decode(r);
        value.disable_player_interactions = try r.readBool();
        value.server_editor_connection_policy = try ServerEditorConnectionPolicy.decode(r);
        value.allow_anonymous_block_drops_in_editor_worlds = try r.readBool();
        return value;
    }

    pub fn encode(self: LevelSettings, w: anytype) EncodeError!void {
        try w.writeU64(self.seed);
        try self.spawn_settings.encode(w);
        try self.generator_type.encode(w);
        try self.game_type.encode(w);
        try w.writeBool(self.is_hardcore);
        try self.game_difficulty.encode(w);
        try w.writeBlockPosition(self.default_spawn_block_position);
        try w.writeBool(self.achievements_disabled);
        try self.editor_world_type.encode(w);
        try w.writeBool(self.is_created_in_editor);
        try w.writeBool(self.is_exported_from_editor);
        try w.writeVarI32(self.day_cycle_stop_time);
        try self.education_edition_offer.encode(w);
        try w.writeBool(self.education_features_enabled);
        try w.writeString(self.education_product_id);
        try w.writeF32(self.rain_level);
        try w.writeF32(self.lightning_level);
        try w.writeBool(self.has_confirmed_platform_locked_content);
        try w.writeBool(self.multiplayer_game_intent);
        try w.writeBool(self.lan_broadcast_intent);
        try self.xbox_live_broadcast_setting.encode(w);
        try self.platform_broadcast_setting.encode(w);
        try w.writeBool(self.commands_enabled);
        try w.writeBool(self.texture_packs_required);
        try w.writeCount(.var_u32, self.rule_data.len);
        try self.rule_data.encode(w);
        try self.experiments.encode(w);
        try w.writeBool(self.has_bonus_chest_enabled);
        try w.writeBool(self.start_with_map_enabled);
        try self.player_permissions.encode(w);
        try w.writeI32(self.server_chunk_tick_range);
        try w.writeBool(self.has_locked_behavior_pack);
        try w.writeBool(self.has_locked_resource_pack);
        try w.writeBool(self.is_from_locked_template);
        try w.writeBool(self.use_msa_gamertags_only);
        try w.writeBool(self.is_from_world_template);
        try w.writeBool(self.is_world_template_option_locked);
        try w.writeBool(self.only_spawn_v1_villagers);
        try w.writeBool(self.persona_disabled);
        try w.writeBool(self.custom_skins_disabled);
        try w.writeBool(self.emote_chat_muted);
        try w.writeString(self.base_game_version);
        try w.writeI32(self.limited_world_width);
        try w.writeI32(self.limited_world_depth);
        try w.writeBool(self.nether_type);
        try self.edu_shared_uri_resource.encode(w);
        try w.writeBool(self.override_force_experimental_gameplay != null);
        if (self.override_force_experimental_gameplay) |present| {
            try w.writeBool(present);
        }
        try self.chat_restriction_level.encode(w);
        try w.writeBool(self.disable_player_interactions);
        try self.server_editor_connection_policy.encode(w);
        try w.writeBool(self.allow_anonymous_block_drops_in_editor_worlds);
    }
};

/// Wire type `SyncedPlayerMovementSettings`.
pub const PlayerMovementSettings = struct {
    rewind_history_size: i32,
    server_authoritative_block_breaking: bool,

    pub fn decode(r: *Reader) DecodeError!PlayerMovementSettings {
        var value: PlayerMovementSettings = undefined;
        value.rewind_history_size = try r.readVarI32();
        value.server_authoritative_block_breaking = try r.readBool();
        return value;
    }

    pub fn encode(self: PlayerMovementSettings, w: anytype) EncodeError!void {
        try w.writeVarI32(self.rewind_history_size);
        try w.writeBool(self.server_authoritative_block_breaking);
    }
};

/// Wire type `ServerBlockProperty`.
pub const ServerBlockProperty = struct {
    block_name: []const u8,
    block_definition: []const u8,

    pub fn decode(r: *Reader) DecodeError!ServerBlockProperty {
        var value: ServerBlockProperty = undefined;
        value.block_name = try r.readString();
        value.block_definition = try r.readNbt();
        return value;
    }

    pub fn encode(self: ServerBlockProperty, w: anytype) EncodeError!void {
        try w.writeString(self.block_name);
        try w.writeNbt(self.block_definition);
    }
};

/// Wire type `ServerConfiguration::ServerConfigurationJoinInfo`.
pub const ServerConfigurationJoinInfo = struct {
    gathering: ?types.GatheringJoinInfo,
    client_store_entry_point: ?types.StoreEntryPointInfo,
    presence: ??[]const u8,

    pub fn decode(r: *Reader) DecodeError!ServerConfigurationJoinInfo {
        var value: ServerConfigurationJoinInfo = undefined;
        value.gathering = if (try r.readBool()) try types.GatheringJoinInfo.decode(r) else null;
        value.client_store_entry_point = if (try r.readBool()) try types.StoreEntryPointInfo.decode(r) else null;
        value.presence = null;
        if (try r.readBool()) {
            var present: ?[]const u8 = undefined;
            present = null;
            if (try r.readBool()) {
                var present1: []const u8 = undefined;
                present1 = try r.readString();
                if (present1.len > 50) return error.InvalidValue;
                present = present1;
            }
            value.presence = present;
        }
        return value;
    }

    pub fn encode(self: ServerConfigurationJoinInfo, w: anytype) EncodeError!void {
        try w.writeBool(self.gathering != null);
        if (self.gathering) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.client_store_entry_point != null);
        if (self.client_store_entry_point) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.presence != null);
        if (self.presence) |present| {
            try w.writeBool(present != null);
            if (present) |present1| {
                if (present1.len > 50) return error.InvalidValue;
                try w.writeString(present1);
            }
        }
    }
};

/// Wire type `ServerEditorConnectionPolicy`.
pub const ServerEditorConnectionPolicy = enum(i32) {
    matchworldtype = 0,
    editoronly = 1,
    vanillaonly = 2,
    mixed = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!ServerEditorConnectionPolicy {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: ServerEditorConnectionPolicy, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

/// Wire type `Social::GamePublishSetting`.
pub const SocialGamePublishSetting = enum(i32) {
    nomultiplay = 0,
    inviteonly = 1,
    friendsonly = 2,
    friendsoffriends = 3,
    public = 4,
    _,

    pub fn decode(r: *Reader) DecodeError!SocialGamePublishSetting {
        return @fromBackingInt(@intCast(try r.readVarI32()));
    }

    pub fn encode(self: SocialGamePublishSetting, w: anytype) EncodeError!void {
        try w.writeVarI32(@backingInt(self));
    }
};

/// Wire type `SpawnBiomeType`.
pub const SpawnBiomeType = enum(i16) {
    default = 0,
    userdefined = 1,
    _,

    pub fn decode(r: *Reader) DecodeError!SpawnBiomeType {
        return @fromBackingInt(@intCast(try r.readI16()));
    }

    pub fn encode(self: SpawnBiomeType, w: anytype) EncodeError!void {
        try w.writeI16(@backingInt(self));
    }
};

/// Wire type `SpawnSettings`.
pub const SpawnSettings = struct {
    spawn_biome_type: SpawnBiomeType,
    user_defined_biome_name: []const u8,
    dimension: i32,

    pub fn decode(r: *Reader) DecodeError!SpawnSettings {
        var value: SpawnSettings = undefined;
        value.spawn_biome_type = try SpawnBiomeType.decode(r);
        value.user_defined_biome_name = try r.readString();
        value.dimension = try r.readVarI32();
        return value;
    }

    pub fn encode(self: SpawnSettings, w: anytype) EncodeError!void {
        try self.spawn_biome_type.encode(w);
        try w.writeString(self.user_defined_biome_name);
        try w.writeVarI32(self.dimension);
    }
};
