//! SubChunkRequestPacket (ID 175), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    dimension_type: i32,
    sub_chunk_position_offset_list: codec.List(types.SubChunkPosOffset, types.SubChunkPosOffset),
    center_pos: codec.SubChunkPosition,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.dimension_type = try r.readVarI32();
        value.sub_chunk_position_offset_list = blk: {
            const count = try r.readCount(.var_u32);
            if (count > 8192) return error.InvalidValue;
            break :blk try codec.List(types.SubChunkPosOffset, types.SubChunkPosOffset).decode(r, count);
        };
        value.center_pos = try r.readSubChunkPosition();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeVarI32(self.dimension_type);
        if (self.sub_chunk_position_offset_list.len > 8192) return error.InvalidValue;
        try w.writeCount(.var_u32, self.sub_chunk_position_offset_list.len);
        try self.sub_chunk_position_offset_list.encode(w);
        try w.writeSubChunkPosition(self.center_pos);
    }
};
