//! TransferPacket (ID 85), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    server_address: []const u8,
    server_port: u16,
    reload_world: bool,
    gatherings_configuration: ?types.GatheringJoinInfo,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.server_address = try r.readString();
        value.server_port = try r.readU16();
        value.reload_world = try r.readBool();
        value.gatherings_configuration = if (try r.readBool()) try types.GatheringJoinInfo.decode(r) else null;
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeString(self.server_address);
        try w.writeU16(self.server_port);
        try w.writeBool(self.reload_world);
        try w.writeBool(self.gatherings_configuration != null);
        if (self.gatherings_configuration) |present| {
            try present.encode(w);
        }
    }
};
