//! TrimDataPacket (ID 302), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    trim_pattern_list: codec.List(TrimPattern, TrimPattern),
    trim_material_list: codec.List(TrimMaterial, TrimMaterial),

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.trim_pattern_list = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(TrimPattern, TrimPattern).decode(r, count);
        };
        value.trim_material_list = blk: {
            const count = try r.readCount(.var_u32);
            break :blk try codec.List(TrimMaterial, TrimMaterial).decode(r, count);
        };
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeCount(.var_u32, self.trim_pattern_list.len);
        try self.trim_pattern_list.encode(w);
        try w.writeCount(.var_u32, self.trim_material_list.len);
        try self.trim_material_list.encode(w);
    }
};

/// Wire type `TrimMaterial`.
pub const TrimMaterial = struct {
    material_id: []const u8,
    color: []const u8,
    item_name: []const u8,

    pub fn decode(r: *Reader) DecodeError!TrimMaterial {
        var value: TrimMaterial = undefined;
        value.material_id = try r.readString();
        value.color = try r.readString();
        value.item_name = try r.readString();
        return value;
    }

    pub fn encode(self: TrimMaterial, w: anytype) EncodeError!void {
        try w.writeString(self.material_id);
        try w.writeString(self.color);
        try w.writeString(self.item_name);
    }
};

/// Wire type `TrimPattern`.
pub const TrimPattern = struct {
    item_name: []const u8,
    pattern_id: []const u8,

    pub fn decode(r: *Reader) DecodeError!TrimPattern {
        var value: TrimPattern = undefined;
        value.item_name = try r.readString();
        value.pattern_id = try r.readString();
        return value;
    }

    pub fn encode(self: TrimPattern, w: anytype) EncodeError!void {
        try w.writeString(self.item_name);
        try w.writeString(self.pattern_id);
    }
};
