//! UpdateClientOptionsPacket (ID 323), sent by either peer.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    graphics_mode_change: ?GraphicsMode,
    filter_profanity_change: ?bool,

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.graphics_mode_change = if (try r.readBool()) try GraphicsMode.decode(r) else null;
        value.filter_profanity_change = if (try r.readBool()) try r.readBool() else null;
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeBool(self.graphics_mode_change != null);
        if (self.graphics_mode_change) |present| {
            try present.encode(w);
        }
        try w.writeBool(self.filter_profanity_change != null);
        if (self.filter_profanity_change) |present| {
            try w.writeBool(present);
        }
    }
};

/// Wire type `GraphicsMode`.
pub const GraphicsMode = enum(u8) {
    simple = 0,
    fancy = 1,
    advanced = 2,
    raytraced = 3,
    _,

    pub fn decode(r: *Reader) DecodeError!GraphicsMode {
        return @fromBackingInt(@intCast(try r.readU8()));
    }

    pub fn encode(self: GraphicsMode, w: anytype) EncodeError!void {
        try w.writeU8(@backingInt(self));
    }
};
