//! UpdateTradePacket (ID 80), sent by the server.
// Generated by tools/codegen from protocol/schema/bedrock.json. Do not edit.
const codec = @import("../codec/support.zig");
const types = @import("../types.zig");
const custom = @import("../custom/root.zig");
const Reader = codec.Reader;
const DecodeError = codec.DecodeError;
const EncodeError = codec.EncodeError;

pub const Packet = struct {
    container_id: u8,
    type: u8,
    size: i32,
    trader_tier: i32,
    entity_unique_id: i64,
    last_trading_player: i64,
    display_name: []const u8,
    use_new_trade_screen: bool,
    using_economy_trade: bool,
    data: []const u8,

    pub const actor_refs = .{
        .entity_unique_id = codec.ActorRef.unique,
        .last_trading_player = codec.ActorRef.unique,
    };

    pub fn decode(r: *Reader) DecodeError!Packet {
        var value: Packet = undefined;
        value.container_id = try r.readU8();
        value.type = try r.readU8();
        value.size = try r.readVarI32();
        value.trader_tier = try r.readVarI32();
        value.entity_unique_id = try r.readVarI64();
        value.last_trading_player = try r.readVarI64();
        value.display_name = try r.readString();
        value.use_new_trade_screen = try r.readBool();
        value.using_economy_trade = try r.readBool();
        value.data = try r.readNbt();
        return value;
    }

    pub fn encode(self: Packet, w: anytype) EncodeError!void {
        try w.writeU8(self.container_id);
        try w.writeU8(self.type);
        try w.writeVarI32(self.size);
        try w.writeVarI32(self.trader_tier);
        try w.writeVarI64(self.entity_unique_id);
        try w.writeVarI64(self.last_trading_player);
        try w.writeString(self.display_name);
        try w.writeBool(self.use_new_trade_screen);
        try w.writeBool(self.using_economy_trade);
        try w.writeNbt(self.data);
    }
};
